<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import {
    ArrowLeft, Trash2, Printer, Share2, ChevronDown, Trophy,
    Target, Check, X, MinusCircle, Ticket, Plus, Save, Pencil
  } from '@lucide/svelte';
  import SEO from '$lib/components/SEO.svelte';
  import {
    savedSlips, builderItemCount, builderTotalOdds, builderPotentialWin,
    builderGetTitle, builderGetStake, builderGetItems, builderGetId,
    isInBuilder, startNewBuilder, loadIntoBuilder, setBuilderTitle,
    setBuilderStake, addToBuilder, removeFromBuilder, saveBuilderSlip,
    loadSlips, deleteSavedSlip, slipWhatsAppUrl, type SavedSlip, type BetSlipItem
  } from '$lib/betSlipStore.svelte';
  import { authState } from '$lib/authStore.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  let loaded = $state(false);
  let saving = $state(false);
  let saveMsg = $state('');
  let editingTitle = $state(true);

  onMount(() => {
    void loadSlips().then(() => (loaded = true));
  });

  const slips = $derived(savedSlips());
  const items = $derived(builderGetItems());
  const totalOdds = $derived(builderTotalOdds());
  const potential = $derived(builderPotentialWin());
  const slipId = $derived(builderGetId());
  const userName = $derived(authState.user?.fullName ?? '');

  function kickoffLabel(kickoff: number): string {
    return new Date(kickoff).toLocaleString('en-GB', {
      weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit'
    });
  }

  async function handleSave() {
    if (items.length === 0) return;
    saving = true;
    saveMsg = '';
    const id = await saveBuilderSlip();
    saving = false;
    if (id) {
      saveMsg = 'Slip saved!';
      await loadSlips();
      setTimeout(() => (saveMsg = ''), 2500);
    } else {
      saveMsg = 'Save failed — try again.';
    }
  }

  function slipPdf(slip: { title: string; stake: number; items: BetSlipItem[]; userName?: string }) {
    const total = slip.items.reduce((acc, i) => acc * i.odds, 1);
    const potential = total * slip.stake;
    const w = window.open('', '_blank', 'width=440,height=640');
    if (!w) return;
    const rows = slip.items.map((i, idx) =>
      `<tr><td>${idx + 1}</td><td>${i.homeTeam} vs ${i.awayTeam}</td><td>${i.league}</td><td>${i.selection}</td><td>${i.odds.toFixed(2)}</td>${i.grade ? `<td class="${i.grade}">${i.grade.toUpperCase()}</td>` : '<td>—</td>'}</tr>`
    ).join('');
    w.document.write(`
      <html><head><title>${slip.title} | PulseOdds Bet Slip</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 20px; color: #111; max-width: 520px; margin: 0 auto; }
        .header { text-align: center; margin-bottom: 16px; }
        .site { font-size: 10px; color: #888; letter-spacing: 0.1em; text-transform: uppercase; }
        h1 { font-size: 20px; border-bottom: 2px solid #a3e635; padding-bottom: 8px; margin: 4px 0 4px; }
        .user { font-size: 13px; font-weight: 600; margin-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { text-align: left; padding: 6px; background: #f4f4f4; border-bottom: 1px solid #ddd; font-size: 10px; text-transform: uppercase; }
        td { padding: 6px; border-bottom: 1px solid #eee; }
        .win { color: #16a34a; font-weight: bold; }
        .loss { color: #dc2626; }
        .push { color: #6b7280; }
        .totals { margin-top: 14px; font-size: 14px; }
        .totals div { display: flex; justify-content: space-between; padding: 4px 0; }
        .totals .big { font-size: 18px; font-weight: bold; }
      </style></head><body>
      <div class="header"><div class="site">pulseodds.ewinproject.org</div><h1>⚡ ${slip.title}</h1>${slip.userName ? `<div class="user">${slip.userName}</div>` : ''}</div>
      <table><thead><tr><th>#</th><th>Fixture</th><th>League</th><th>Selection</th><th>Odds</th><th>Result</th></tr></thead>
      <tbody>${rows}</tbody></table>
      <div class="totals">
        <div><span>Total odds:</span><span class="big">${total.toFixed(2)}</span></div>
        <div><span>Stake:</span><span>₦${slip.stake.toLocaleString()}</span></div>
        <div><span>Potential win:</span><span class="big">₦${potential.toLocaleString()}</span></div>
      </div>
      <p style="font-size:10px;color:#888;text-align:center;margin-top:20px;">Generated by PulseOdds — Read the odds. Own the edge. Beat the Bookies.<br>pulseodds.ewinproject.org</p>
      </body></html>
    `);
    w.document.close();
    w.print();
  }
</script>

<SEO seo={data.seo} />

<div class="slip-root">
  <header class="slip-head">
    <button class="icon-btn" aria-label="Back to predictor" onclick={() => void goto('/predictor')} type="button">
      <ArrowLeft size={20} stroke-width={2.4} />
    </button>
    <div class="head-title">
      <span class="eyebrow">Bet Slips</span>
      <h1>My Bet Slips</h1>
    </div>
    <button class="new-slip-btn" onclick={() => { startNewBuilder(); editingTitle = true; }} type="button" aria-label="Create new bet slip">
      <Plus size={16} stroke-width={2.6} /> New
    </button>
  </header>

  <!-- ── Builder (new / editing slip) ── -->
  <section class="builder" aria-label="Bet slip builder">
    <div class="builder-head">
      {#if editingTitle}
        <input
          class="title-input"
          placeholder="Slip title (e.g. Sat ACCA, EuroLeague doubles…)"
          value={builderGetTitle()}
          oninput={(e) => setBuilderTitle((e.currentTarget as HTMLInputElement).value)}
          maxlength="60"
        />
      {:else}
        <button class="title-display" type="button" onclick={() => (editingTitle = true)}>
          {builderGetTitle() || 'Untitled slip'} <Pencil size={12} />
        </button>
      {/if}
      <div class="stake-row">
        <label class="stake-label" for="slip-stake">Stake ₦</label>
        <input
          id="slip-stake"
          class="stake-input"
          type="number"
          min="0"
          placeholder="0"
          value={builderGetStake() || ''}
          oninput={(e) => setBuilderStake(Number((e.currentTarget as HTMLInputElement).value) || 0)}
        />
      </div>
    </div>

    {#if items.length === 0}
      <p class="builder-empty">
        <Target size={16} stroke-width={1.6} />
        Add market options from the AI Predictor's research summary by tapping the <strong>+</strong> button.
      </p>
    {:else}
      <div class="builder-items">
        {#each items as item, idx (item.matchId + item.selection)}
          <div class="b-item">
            <span class="bi-n">{idx + 1}</span>
            <div class="bi-main">
              <span class="bi-teams">{item.homeTeam} vs {item.awayTeam}</span>
              <span class="si-league">{item.league} · {kickoffLabel(item.kickoff)}</span>
              <span class="si-selection">{item.selection} <em>@ {item.odds.toFixed(2)}</em></span>
            </div>
            <button class="bi-remove" aria-label="Remove" onclick={() => removeFromBuilder(item.matchId, item.selection)} type="button">
              <X size={13} />
            </button>
          </div>
        {/each}
      </div>
      <div class="builder-totals">
        <div><span>Picks:</span><strong>{items.length}</strong></div>
        <div><span>Total odds:</span><strong>{totalOdds.toFixed(2)}</strong></div>
        <div><span>Potential win:</span><strong class="pot">₦{potential.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong></div>
      </div>
    {/if}

    <button class="save-btn" type="button" onclick={handleSave} disabled={saving || items.length === 0}>
      <Save size={14} stroke-width={2.4} /> {saving ? 'Saving…' : slipId ? 'Update slip' : 'Save slip'}
    </button>
    {#if saveMsg}<p class="save-msg">{saveMsg}</p>{/if}
  </section>

  <!-- ── Saved slips ── -->
  {#if loaded && slips.length > 0}
    <h2 class="saved-title">Saved slips <span class="tag">{slips.length}</span></h2>
    {#each slips as slip (slip._id)}
      {@const total = slip.items.reduce((acc: number, i: BetSlipItem) => acc * i.odds, 1)}
      {@const potential = total * (slip.stake ?? 0)}
      {@const settled = slip.items.filter((i: BetSlipItem) => i.grade).length}
      {@const won = slip.items.filter((i: BetSlipItem) => i.grade === 'win').length}
      <details class="saved-slip">
        <summary>
          <div class="ss-summary">
            <span class="ss-title">{slip.title}</span>
            <span class="ss-meta">{slip.items.length} picks · odds {total.toFixed(2)}{slip.stake ? ` · ₦${(slip.stake ?? 0).toLocaleString()} stake` : ''}</span>
            {#if settled > 0}<span class="ss-grade">{won}/{settled} won</span>{/if}
          </div>
        </summary>
        <div class="ss-body">
          {#each slip.items as item (item.matchId + item.selection)}
            <div class="b-item">
              <div class="bi-main">
                <span class="bi-teams">{item.homeTeam} vs {item.awayTeam}</span>
                <span class="si-league">{item.league} · {kickoffLabel(item.kickoff)}</span>
                <span class="si-selection">
                  {item.selection} <em>@ {item.odds.toFixed(2)}</em>
                  {#if item.grade === 'win'}<span class="grade-badge win"><Check size={10} /> WON</span>{:else if item.grade === 'loss'}<span class="grade-badge loss"><X size={10} /> LOST</span>{:else if item.grade === 'push'}<span class="grade-badge push"><MinusCircle size={10} /> PUSH</span>{/if}
                  {#if item.finalScore}<span class="ft-score">FT {item.finalScore}</span>{/if}
                </span>
              </div>
              <button class="si-analysis" type="button" onclick={() => void goto(`/predictor/${item.sportId}/${item.matchId}`)}>
                View analysis
              </button>
            </div>
          {/each}
          <div class="ss-totals">
            <div><span>Total odds:</span><strong>{total.toFixed(2)}</strong></div>
            <div><span>Stake:</span><strong>₦{(slip.stake ?? 0).toLocaleString()}</strong></div>
            <div><span>Potential:</span><strong class="pot">₦{potential.toLocaleString(undefined, { maximumFractionDigits: 0 })}</strong></div>
          </div>
          <div class="ss-actions">
            <button class="ss-btn" type="button" onclick={() => { loadIntoBuilder(slip); editingTitle = true; }}>
              <Pencil size={12} /> Edit
            </button>
            <button class="ss-btn" type="button" onclick={() => window.open(slipWhatsAppUrl(slip), '_blank')}>
              <Share2 size={12} /> WhatsApp
            </button>
            <button class="ss-btn" type="button" onclick={() => slipPdf(slip)}>
              <Printer size={12} /> PDF
            </button>
            <button class="ss-btn danger" type="button" onclick={() => void deleteSavedSlip(slip._id)}>
              <Trash2 size={12} /> Delete
            </button>
          </div>
        </div>
      </details>
    {/each}
  {:else if loaded}
    <p class="no-saved">No saved slips yet — build one above and hit "Save slip".</p>
  {/if}
</div>

<style>
  .slip-root { max-width: 560px; margin: 0 auto; padding: 20px 16px 80px; min-height: 100dvh; color: var(--c-text); }

  .slip-head {
    display: flex; align-items: center; justify-content: space-between; gap: 10px;
    padding: 8px 0 18px; position: sticky; top: 0; z-index: 50;
    background: var(--c-surface-2); backdrop-filter: blur(20px); border-bottom: 1px solid var(--c-border);
  }
  .icon-btn {
    width: 44px; height: 44px; border: 1px solid var(--c-border-md); border-radius: 12px;
    background: var(--c-glass-sm); color: var(--c-text); display: inline-flex; align-items: center;
    justify-content: center; cursor: pointer;
  }
  .head-title { text-align: center; flex: 1; }
  .eyebrow { display: block; color: var(--brand); text-transform: uppercase; letter-spacing: 0.1em; font-size: 10px; font-weight: 800; }
  .head-title h1 { font-family: var(--font-display); font-size: clamp(18px, 4vw, 24px); margin: 2px 0; }
  .new-slip-btn {
    display: inline-flex; align-items: center; gap: 5px; padding: 8px 14px; border-radius: 10px;
    border: none; background: linear-gradient(135deg, var(--brand), var(--brand-hover));
    color: var(--c-on-accent); font-weight: 800; font-size: 13px; cursor: pointer; box-shadow: var(--glow-brand);
  }

  .builder { background: var(--c-surface); border: 1px solid var(--c-border); border-radius: 14px; padding: 14px; margin-bottom: 20px; }
  .builder-head { display: flex; flex-direction: column; gap: 8px; margin-bottom: 10px; }
  .title-input, .stake-input {
    width: 100%; min-height: 44px; padding: 10px 12px; border-radius: 10px;
    border: 1px solid var(--c-input-border); background: var(--c-input-bg); color: var(--c-input-text);
    font-size: 14px; font-weight: 700;
  }
  .title-input:focus, .stake-input:focus { outline: none; border-color: color-mix(in srgb, var(--brand) 60%, transparent); }
  .title-display {
    display: flex; align-items: center; gap: 6px; width: 100%; padding: 8px 0; border: none;
    background: transparent; color: var(--c-text); font-size: 15px; font-weight: 800; cursor: pointer; text-align: left;
  }
  .stake-row { display: flex; align-items: center; gap: 8px; }
  .stake-label { font-size: 12px; font-weight: 800; color: var(--c-muted); flex-shrink: 0; }
  .stake-input { flex: 1; }
  .builder-empty { display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 24px 12px; color: var(--c-muted); font-size: 13px; text-align: center; }

  .builder-items { display: flex; flex-direction: column; gap: 6px; margin-bottom: 12px; }
  .b-item {
    display: flex; align-items: flex-start; gap: 8px; padding: 8px 10px;
    border-radius: 10px; border: 1px solid var(--c-border); background: var(--c-glass-sm);
  }
  .bi-n { font-family: var(--font-mono); font-size: 11px; color: var(--c-faint); flex-shrink: 0; margin-top: 2px; }
  .bi-main { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 1px; }
  .bi-teams { font-weight: 800; font-size: 13px; }
  .si-league { font-size: 11px; color: var(--c-muted); }
  .si-selection { font-size: 12px; color: var(--brand); font-weight: 700; }
  .si-selection em { color: var(--c-muted); font-style: normal; font-family: var(--font-mono); font-size: 11px; }
  .bi-remove {
    flex-shrink: 0; width: 28px; height: 28px; border-radius: 8px; border: 1px solid var(--c-border-md);
    background: var(--c-glass-sm); color: var(--c-muted); display: inline-flex; align-items: center;
    justify-content: center; cursor: pointer;
  }
  .bi-remove:hover { border-color: color-mix(in srgb, var(--c-error) 45%, transparent); color: var(--c-error); }

  .builder-totals { display: flex; gap: 14px; flex-wrap: wrap; padding: 8px 0; font-size: 12px; color: var(--c-text-2); }
  .builder-totals strong { font-family: var(--font-mono); font-size: 14px; color: var(--c-text); }
  .builder-totals .pot { color: var(--c-success); }

  .save-btn {
    width: 100%; min-height: 48px; display: inline-flex; align-items: center; justify-content: center; gap: 8px;
    border-radius: 10px; border: none; background: linear-gradient(135deg, var(--brand), var(--brand-hover));
    color: var(--c-on-accent); font-weight: 800; font-size: 14px; cursor: pointer; box-shadow: var(--glow-brand);
  }
  .save-btn:disabled { opacity: 0.5; cursor: not-allowed; }
  .save-msg { text-align: center; font-size: 12px; color: var(--c-success); font-weight: 700; margin: 8px 0 0; }

  .saved-title { display: flex; align-items: center; gap: 6px; font-size: 13px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.05em; color: var(--c-text-2); margin: 0 0 12px; }
  .tag { font-size: 10px; padding: 2px 7px; border-radius: 999px; background: color-mix(in srgb, var(--brand) 12%, transparent); color: var(--brand); }

  .saved-slip { margin-bottom: 12px; border: 1px solid var(--c-border); border-radius: 14px; background: var(--c-surface); overflow: hidden; }
  .saved-slip summary {
    display: flex; align-items: center; padding: 12px 14px; cursor: pointer;
    list-style: none; font-weight: 800; font-size: 14px;
  }
  .saved-slip summary::-webkit-details-marker { display: none; }
  .ss-summary { flex: 1; display: flex; flex-direction: column; gap: 2px; }
  .ss-title { font-weight: 800; font-size: 14px; }
  .ss-meta { font-size: 11px; color: var(--c-muted); }
  .ss-grade { font-size: 11px; font-weight: 800; color: var(--c-success); font-family: var(--font-mono); }
  .ss-body { padding: 0 14px 14px; }
  .ss-totals { display: flex; gap: 14px; flex-wrap: wrap; padding: 8px 0; font-size: 12px; color: var(--c-text-2); border-top: 1px solid var(--c-border-sm); margin-top: 8px; }
  .ss-totals strong { font-family: var(--font-mono); font-size: 14px; color: var(--c-text); }
  .ss-totals .pot { color: var(--c-success); }
  .ss-actions { display: flex; gap: 6px; flex-wrap: wrap; margin-top: 10px; }
  .ss-btn {
    display: inline-flex; align-items: center; gap: 4px; padding: 7px 12px; border-radius: 8px;
    border: 1px solid var(--c-border-md); background: var(--c-glass-sm); color: var(--c-text-2);
    font-size: 11px; font-weight: 700; cursor: pointer;
  }
  .ss-btn:hover { border-color: color-mix(in srgb, var(--brand) 40%, transparent); color: var(--brand); }
  .ss-btn.danger:hover { border-color: color-mix(in srgb, var(--c-error) 45%, transparent); color: var(--c-error); }
  .si-analysis {
    flex-shrink: 0; padding: 4px 10px; border-radius: 8px; font-size: 10.5px; font-weight: 700;
    color: var(--accent2); border-color: color-mix(in srgb, var(--accent2) 35%, transparent);
    border: 1px solid; background: transparent; cursor: pointer;
  }
  .ft-score { font-family: var(--font-mono); font-size: 11px; color: var(--c-muted); margin-left: 4px; }
  .grade-badge {
    display: inline-flex; align-items: center; gap: 3px; padding: 1px 6px; border-radius: 6px;
    font-size: 10px; font-weight: 900; letter-spacing: 0.04em; margin-left: 4px;
  }
  .grade-badge.win { background: color-mix(in srgb, var(--c-success) 15%, transparent); color: var(--c-success); }
  .grade-badge.loss { background: color-mix(in srgb, var(--c-error) 15%, transparent); color: var(--c-error); }
  .grade-badge.push { background: var(--c-glass-md); color: var(--c-muted); }
  .no-saved { text-align: center; padding: 24px; color: var(--c-muted); font-size: 13px; }
</style>
