<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import {
    ArrowLeft, Trash2, Printer, Share2, ChevronDown, History,
    Target, Check, X, MinusCircle, Ticket, Archive, ExternalLink
  } from '@lucide/svelte';
  import SEO from '$lib/components/SEO.svelte';
  import {
    betSlipItems, betSlipCount, totalOdds, settledCount, wonCount, loseCount,
    openCount, finishedCount, archivedSlips, removeFromSlip, clearSlip,
    archiveCurrentSlip, deleteArchivedSlip, loadSlip, whatsappShareUrl,
    whatsAppShareUrlFor, type BetSlipItem
  } from '$lib/betSlipStore.svelte';
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();

  let collapsedFinished = $state(true);
  let collapsedHistory = $state<Record<string, boolean>>({});
  let loaded = $state(false);

  onMount(() => {
    void loadSlip().then(() => (loaded = true));
  });

  // A leg is finished as soon as its final scoreline is known; the win/loss
  // grade may still be missing for markets a plain scoreline cannot settle.
  const open = $derived(betSlipItems().filter((i) => !i.finalScore));
  const finished = $derived(betSlipItems().filter((i) => !!i.finalScore));
  const history = $derived(archivedSlips());
  const combined = $derived(totalOdds());

  function kickoffLabel(kickoff: number): string {
    return new Date(kickoff).toLocaleString('en-GB', {
      weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit'
    });
  }

  function resultSummary(items: BetSlipItem[]): string {
    const won = items.filter((i) => i.grade === 'win').length;
    const lost = items.filter((i) => i.grade === 'loss').length;
    const pending = items.filter((i) => !i.finalScore).length;
    const parts = [`${won}W`, `${lost}L`];
    if (pending) parts.push(`${pending} pending`);
    return parts.join(' · ');
  }

  function slipPdf(list: BetSlipItem[], title = 'PulseOdds Bet Slip') {
    // Print-to-PDF — the browser print dialog writes a clean, shareable slip.
    const w = window.open('', '_blank', 'width=420,height=640');
    if (!w) return;
    const rows = list
      .map(
        (i, idx) =>
          `<tr><td>${idx + 1}</td><td>${i.homeTeam} vs ${i.awayTeam}</td><td>${i.league}</td><td>${i.selection}</td><td>${i.odds.toFixed(2)}</td><td>${i.finalScore ?? '—'}</td><td class="${i.grade ?? ''}">${(i.grade ?? '').toUpperCase() || '—'}</td></tr>`
      )
      .join('');
    const combinedOdds = list.reduce((acc, i) => acc * i.odds, 1);
    w.document.write(`
      <html><head><title>${title}</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 16px; color: #111; }
        h1 { font-size: 18px; border-bottom: 2px solid #a3e635; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th { text-align: left; padding: 5px; background: #f4f4f4; border-bottom: 1px solid #ddd; }
        td { padding: 5px; border-bottom: 1px solid #eee; }
        .win { color: #16a34a; font-weight: bold; }
        .loss { color: #dc2626; font-weight: bold; }
        .push { color: #6b7280; }
        .total { font-weight: bold; font-size: 14px; margin-top: 12px; }
      </style></head><body>
      <h1>⚡ ${title}</h1>
      <table><thead><tr><th>#</th><th>Fixture</th><th>League</th><th>Selection</th><th>Odds</th><th>FT</th><th>Result</th></tr></thead>
      <tbody>${rows}</tbody></table>
      <p class="total">Total odds: ${combinedOdds.toFixed(2)} · ${list.length} pick${list.length === 1 ? '' : 's'}</p>
      <p style="font-size:10px;color:#888;">Generated by PulseOdds — Read the odds. Own the edge. Beat the Bookies.</p>
      </body></html>
    `);
    w.document.close();
    w.print();
  }
</script>

<SEO seo={data.seo} />

<div class="slip-root">
  <header class="slip-head">
    <button class="icon-btn" aria-label="Back" onclick={() => void goto('/predictor')} type="button">
      <ArrowLeft size={20} stroke-width={2.4} />
    </button>
    <div class="head-title">
      <span class="eyebrow">Accumulative Bet Slip</span>
      <h1>Bet Slip</h1>
    </div>
    <span class="slip-count-badge" aria-label="{betSlipCount()} items">
      <Ticket size={16} stroke-width={2} /> {betSlipCount()}
    </span>
  </header>

  {#if !loaded}
    <p class="loading">Loading bet slip…</p>
  {:else if betSlipCount() === 0 && history.length === 0}
    <div class="empty-slip">
      <Ticket size={32} stroke-width={1.6} />
      <p>Your bet slip is empty.</p>
      <p class="hint">
        Add market options from the AI Predictor's <strong>research &amp; analysis summary</strong>
        by tapping <strong>Slip</strong> on any ranked pick — across as many fixtures and sports as you like.
      </p>
      <button class="browse-btn" type="button" onclick={() => void goto('/predictor')}>
        <Target size={14} /> Browse fixtures
      </button>
    </div>
  {:else}
    {#if betSlipCount() === 0}
      <div class="empty-slip small">
        <p>No open picks — seal a slip below or add more from the predictor.</p>
        <button class="browse-btn" type="button" onclick={() => void goto('/predictor')}>
          <Target size={14} /> Browse fixtures
        </button>
      </div>
    {:else}
      <!-- ── Combined odds ── -->
      <div class="odds-strip">
        <div class="odds-box">
          <span class="odds-label">{betSlipCount()} pick{betSlipCount() === 1 ? '' : 's'}</span>
          <span class="odds-val">{combined.toFixed(2)}</span>
          <span class="odds-cap">combined odds</span>
        </div>
        <div class="odds-box">
          <span class="odds-label">Open</span>
          <span class="odds-val">{openCount()}</span>
          <span class="odds-cap">awaiting kick-off</span>
        </div>
        {#if settledCount() > 0}
          <div class="odds-box settled">
            <span class="odds-label">Settled</span>
            <span class="odds-val">{wonCount()}/{wonCount() + loseCount()}</span>
            <span class="odds-cap">won</span>
          </div>
        {/if}
      </div>

      <!-- ── Open picks ── -->
      {#if open.length > 0}
        <section class="slip-section" aria-label="Open selections">
          <h2>Open picks <span class="tag">{open.length}</span></h2>
          {#each open as item (item.matchId + item.selection)}
            <div class="slip-item">
              <div class="si-main">
                <span class="si-teams">{item.homeTeam} vs {item.awayTeam}</span>
                <span class="si-league">{item.league} · {kickoffLabel(item.kickoff)}</span>
                <span class="si-selection">
                  {item.selection} <em>@ {item.odds.toFixed(2)}</em> <em>{item.publishedPct}%</em>
                </span>
              </div>
              <button
                class="si-remove"
                aria-label="Remove {item.selection}"
                onclick={() => void removeFromSlip(item.matchId, item.selection)}
                type="button"
              >
                <Trash2 size={14} />
              </button>
            </div>
          {/each}
        </section>
      {/if}

      <!-- ── Finished picks (collapsible, shows final scorelines) ── -->
      {#if finished.length > 0}
        <section class="slip-section" aria-label="Finished selections">
          <button
            class="section-toggle"
            type="button"
            onclick={() => (collapsedFinished = !collapsedFinished)}
            aria-expanded={!collapsedFinished}
          >
            <h2>Finished <span class="tag">{finished.length}</span></h2>
            <ChevronDown size={16} class={`caret ${collapsedFinished ? '' : 'open'}`} />
          </button>
          {#if !collapsedFinished}
            {#each finished as item (item.matchId + item.selection)}
              <div class="slip-item finished">
                <div class="si-main">
                  <span class="si-teams">{item.homeTeam} vs {item.awayTeam}</span>
                  <span class="si-league">{item.league} · FT {item.finalScore ?? '—'}</span>
                  <span class="si-selection">
                    {item.selection}
                    {#if item.grade === 'win'}<span class="grade-badge win"><Check size={11} /> WON</span>
                    {:else if item.grade === 'loss'}<span class="grade-badge loss"><X size={11} /> LOST</span>
                    {:else if item.grade === 'push'}<span class="grade-badge push"><MinusCircle size={11} /> PUSH</span>
                    {:else}<span class="grade-badge pending">not settleable</span>{/if}
                  </span>
                </div>
                <button
                  class="si-analysis"
                  aria-label="View analysis"
                  title="View the pre-match research & analysis for this fixture"
                  type="button"
                  onclick={() => void goto(`/predictor/${item.sportId}/${item.matchId}`)}
                >
                  <ExternalLink size={11} /> Analysis
                </button>
                <button
                  class="si-remove"
                  aria-label="Delete"
                  onclick={() => void removeFromSlip(item.matchId, item.selection)}
                  type="button"
                >
                  <Trash2 size={14} />
                </button>
              </div>
            {/each}
          {/if}
        </section>
      {/if}

      <!-- ── Actions ── -->
      <div class="slip-actions">
        <button class="action-btn share" type="button" onclick={() => window.open(whatsappShareUrl(), '_blank')} aria-label="Share on WhatsApp">
          <Share2 size={15} stroke-width={2.2} /> Share on WhatsApp
        </button>
        <button class="action-btn pdf" type="button" onclick={() => slipPdf(betSlipItems())} aria-label="Download PDF">
          <Printer size={15} stroke-width={2.2} /> Download PDF
        </button>
        <button class="action-btn seal" type="button" onclick={() => void archiveCurrentSlip()} aria-label="Seal slip into history">
          <Archive size={15} stroke-width={2.2} /> Seal to history
        </button>
        <button class="action-btn clear" type="button" onclick={() => void clearSlip()} aria-label="Clear bet slip">
          <Trash2 size={15} stroke-width={2.2} /> Clear all
        </button>
      </div>
    {/if}

    <!-- ── Slip history ── -->
    {#if history.length > 0}
      <section class="slip-section history" aria-label="Bet slip history">
        <h2><History size={13} /> Slip history <span class="tag">{history.length}</span></h2>
        {#each history as slip (slip.id)}
          <div class="history-card">
            <button
              class="history-head"
              type="button"
              aria-expanded={!collapsedHistory[slip.id]}
              onclick={() =>
                (collapsedHistory = { ...collapsedHistory, [slip.id]: !collapsedHistory[slip.id] })}
            >
              <span class="history-main">
                <span class="history-label">{slip.label}</span>
                <span class="history-meta">{slip.items.length} legs · {resultSummary(slip.items)}</span>
              </span>
              <ChevronDown size={15} class={`caret ${collapsedHistory[slip.id] ? '' : 'open'}`} />
            </button>
            {#if !collapsedHistory[slip.id]}
              <div class="history-body">
                {#each slip.items as item (item.matchId + item.selection)}
                  <div class="slip-item finished compact">
                    <div class="si-main">
                      <span class="si-teams">{item.homeTeam} vs {item.awayTeam}</span>
                      <span class="si-league">{item.league} · FT {item.finalScore ?? '—'}</span>
                      <span class="si-selection">
                        {item.selection}
                        {#if item.grade === 'win'}<span class="grade-badge win"><Check size={11} /> WON</span>
                        {:else if item.grade === 'loss'}<span class="grade-badge loss"><X size={11} /> LOST</span>
                        {:else if item.grade === 'push'}<span class="grade-badge push"><MinusCircle size={11} /> PUSH</span>
                        {:else}<span class="grade-badge pending">not settleable</span>{/if}
                      </span>
                    </div>
                    <button
                      class="si-analysis"
                      type="button"
                      title="View the pre-match research & analysis"
                      onclick={() => void goto(`/predictor/${item.sportId}/${item.matchId}`)}
                    >
                      <ExternalLink size={11} /> Analysis
                    </button>
                  </div>
                {/each}
                <div class="history-actions">
                  <button class="mini-btn" type="button" onclick={() => slipPdf(slip.items, `${slip.label} — slip`)}>
                    <Printer size={12} /> PDF
                  </button>
                  <button
                    class="mini-btn"
                    type="button"
                    onclick={() => window.open(whatsAppShareUrlFor(slip.items, `${slip.label} — PulseOdds slip`), '_blank')}
                  >
                    <Share2 size={12} /> WhatsApp
                  </button>
                  <button class="mini-btn danger" type="button" onclick={() => void deleteArchivedSlip(slip.id)}>
                    <Trash2 size={12} /> Delete
                  </button>
                </div>
              </div>
            {/if}
          </div>
        {/each}
      </section>
    {/if}
  {/if}
</div>

<style>
  .slip-root { max-width: 560px; margin: 0 auto; padding: 20px 16px 80px; min-height: 100dvh; color: var(--c-text); }

  .slip-head {
    display: flex; align-items: center; justify-content: space-between; gap: 10px;
    padding: 8px 0 18px; position: sticky; top: 0; z-index: 50;
    background: var(--c-surface-2); backdrop-filter: blur(20px); border-bottom: 1px solid var(--c-border);
  }
  .icon-btn {
    width: 44px; height: 44px; border: 1px solid var(--c-border-md); border-radius: 12px;
    background: var(--c-glass-sm); color: var(--c-text); display: inline-flex; align-items: center;
    justify-content: center; cursor: pointer;
  }
  .head-title { text-align: center; flex: 1; }
  .eyebrow { display: block; color: var(--brand); text-transform: uppercase; letter-spacing: 0.1em; font-size: 10px; font-weight: 800; }
  .head-title h1 { font-family: var(--font-display); font-size: clamp(18px, 4vw, 24px); margin: 2px 0; }
  .slip-count-badge {
    display: inline-flex; align-items: center; gap: 5px; padding: 6px 12px; border-radius: 999px;
    background: color-mix(in srgb, var(--brand) 12%, transparent); border: 1px solid color-mix(in srgb, var(--brand) 35%, transparent);
    color: var(--brand); font-weight: 800; font-size: 14px; font-family: var(--font-mono);
  }

  .loading { text-align: center; padding: 40px; color: var(--c-muted); }
  .empty-slip {
    display: flex; flex-direction: column; align-items: center; gap: 10px; text-align: center;
    padding: 60px 20px; border: 1px dashed var(--c-border-2); border-radius: 16px; color: var(--c-muted);
  }
  .empty-slip.small { padding: 24px 16px; margin-bottom: 16px; }
  .empty-slip .hint { font-size: 12px; max-width: 44ch; }
  .browse-btn {
    display: inline-flex; align-items: center; gap: 6px; min-height: 44px; padding: 10px 18px;
    border-radius: 10px; border: none; background: linear-gradient(135deg, var(--brand), var(--brand-hover));
    color: var(--c-on-accent); font-weight: 800; cursor: pointer; margin-top: 8px;
  }

  .odds-strip { display: flex; gap: 8px; margin-bottom: 16px; }
  .odds-box {
    flex: 1; padding: 12px 8px; border-radius: 14px; background: var(--c-surface); border: 1px solid var(--c-border);
    display: flex; flex-direction: column; gap: 2px; text-align: center; min-width: 0;
  }
  .odds-box .odds-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: var(--c-muted); font-weight: 700; }
  .odds-box .odds-val { font-family: var(--font-mono); font-size: 24px; font-weight: 900; color: var(--brand); }
  .odds-box .odds-cap { font-size: 10px; color: var(--c-faint); }
  .odds-box.settled .odds-val { color: var(--c-success); }

  .slip-section { margin-bottom: 16px; }
  .slip-section h2 { display: flex; align-items: center; gap: 6px; font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.05em; color: var(--c-text-2); margin: 0 0 8px; }
  .tag { font-size: 10px; padding: 2px 7px; border-radius: 999px; background: color-mix(in srgb, var(--brand) 12%, transparent); color: var(--brand); }

  .section-toggle {
    width: 100%; display: flex; align-items: center; justify-content: space-between;
    background: transparent; border: none; color: inherit; cursor: pointer; padding: 0;
  }
  .caret { transition: transform 200ms ease; color: var(--c-muted); }
  .caret.open { transform: rotate(180deg); }

  .slip-item {
    display: flex; align-items: flex-start; gap: 8px; padding: 10px 12px;
    border-radius: 12px; border: 1px solid var(--c-border); background: var(--c-surface);
    margin-bottom: 6px;
  }
  .slip-item.finished { opacity: 0.85; }
  .slip-item.compact { padding: 8px 10px; }
  .si-main { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 2px; }
  .si-teams { font-weight: 800; font-size: 13px; }
  .si-league { font-size: 11px; color: var(--c-muted); }
  .si-selection { font-size: 12px; color: var(--brand); font-weight: 700; }
  .si-selection em { color: var(--c-muted); font-style: normal; font-family: var(--font-mono); font-size: 11px; }
  .grade-badge {
    display: inline-flex; align-items: center; gap: 3px; padding: 1px 6px; border-radius: 6px;
    font-size: 10px; font-weight: 900; letter-spacing: 0.04em; margin-left: 4px;
  }
  .grade-badge.win { background: color-mix(in srgb, var(--c-success) 15%, transparent); color: var(--c-success); }
  .grade-badge.loss { background: color-mix(in srgb, var(--c-error) 15%, transparent); color: var(--c-error); }
  .grade-badge.push, .grade-badge.pending { background: var(--c-glass-md); color: var(--c-muted); }
  .si-remove, .si-analysis {
    flex-shrink: 0; min-height: 32px; height: 32px; border-radius: 8px; border: 1px solid var(--c-border-md);
    background: var(--c-glass-sm); color: var(--c-muted); display: inline-flex; align-items: center;
    justify-content: center; cursor: pointer;
  }
  .si-remove { width: 32px; }
  .si-remove:hover { border-color: color-mix(in srgb, var(--c-error) 45%, transparent); color: var(--c-error); }
  .si-analysis {
    gap: 4px; padding: 0 9px; font-size: 10.5px; font-weight: 700; color: var(--accent2);
    border-color: color-mix(in srgb, var(--accent2) 35%, transparent);
  }
  .si-analysis:hover { border-color: var(--accent2); }

  .slip-actions { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 16px; }
  .action-btn {
    flex: 1; min-width: 120px; min-height: 44px; display: inline-flex; align-items: center; justify-content: center;
    gap: 6px; border-radius: 10px; font-weight: 800; font-size: 13px; cursor: pointer;
  }
  .action-btn.share { background: #25D366; color: white; border: none; }
  .action-btn.pdf { background: var(--c-glass-md); border: 1px solid var(--c-border-2); color: var(--c-text); }
  .action-btn.seal { background: color-mix(in srgb, var(--brand) 14%, transparent); border: 1px solid color-mix(in srgb, var(--brand) 40%, transparent); color: var(--brand); }
  .action-btn.clear { background: transparent; border: 1px solid color-mix(in srgb, var(--c-error) 35%, transparent); color: var(--c-error); }
  .action-btn:disabled { opacity: 0.5; cursor: not-allowed; }

  .history-card { border: 1px solid var(--c-border); border-radius: 12px; background: var(--c-surface); margin-bottom: 8px; overflow: hidden; }
  .history-head {
    width: 100%; display: flex; align-items: center; justify-content: space-between; gap: 8px;
    background: transparent; border: none; color: inherit; cursor: pointer; padding: 10px 12px; text-align: left;
  }
  .history-main { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
  .history-label { font-weight: 800; font-size: 13px; }
  .history-meta { font-size: 11px; color: var(--c-muted); font-variant-numeric: tabular-nums; }
  .history-body { padding: 0 10px 10px; }
  .history-actions { display: flex; gap: 6px; flex-wrap: wrap; margin-top: 6px; }
  .mini-btn {
    display: inline-flex; align-items: center; gap: 4px; padding: 6px 10px; border-radius: 8px; cursor: pointer;
    font-size: 11px; font-weight: 700; background: var(--c-glass-sm); border: 1px solid var(--c-border-2); color: var(--c-text);
  }
  .mini-btn.danger { color: var(--c-error); border-color: color-mix(in srgb, var(--c-error) 35%, transparent); }
</style>
