<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import SportCard from '$lib/components/SportCard.svelte';
  import BottomNav from '$lib/components/BottomNav.svelte';
  import ThemeToggle from '$lib/components/ThemeToggle.svelte';
  import EWINBanner from '$lib/components/EWINBanner.svelte';
  import SEO from '$lib/components/SEO.svelte';
  import MasterModelShowcase from '$lib/components/MasterModelShowcase.svelte';
  import AiPredictorButton from '$lib/components/AiPredictorButton.svelte';
  import AgentOrbit from '$lib/components/AgentOrbit.svelte';
  import PredictorSportIcon from '$lib/components/PredictorSportIcon.svelte';
  import { AGENT_DEFS } from '$lib/agentUi';
  import { PREDICTOR_SPORTS, type PredictorSportId } from '$lib/predictorTypes';
  import { authState, setUnauthenticated } from '$lib/authStore.svelte';
  import { convexSignOut } from '$lib/convexClient';
  import { notify } from '$lib/notificationStore';
  import { ShieldAlert, CheckCircle2, Zap, HeartHandshake, Sparkles, LogOut, User, MessageSquare, Bot, Clock3, Target, ShieldCheck, TrendingUp } from '@lucide/svelte';
  import type { PageData } from './$types';

  function handleDonateClick() {
    if (!authState.isAuthenticated) {
      notify('Please complete account registration to proceed to subscription payment.', 'info', 'Registration Required');
      try { void goto('/auth?mode=signup&redirect=checkout'); } catch (_) { /* ignore */ }
    } else if (!authState.user?.isSubscribed) {
      notify('Redirecting to subscription payment checkout...', 'info', 'Subscription Checkout');
      try { void goto('/checkout'); } catch (_) { /* ignore */ }
    } else {
      notify('Your monthly subscription pass is active! Enjoy full sports screener access.', 'success', 'Active Subscription');
      try { void goto('/football'); } catch (_) { /* ignore */ }
    }
  }

  // Svelte 5: typed page data from +page.ts load()
  const { data }: { data: PageData } = $props();

  type SportId =
    | 'football'
    | 'basketball'
    | 'tennis'
    | 'rally'
    | 'hockey'
    | 'instant-football'
    | 'instant-basketball'
    | 'vfootball'
    | 'baseball';

  const sports: {
    id: SportId;
    short: string;
    title: string;
    description: string;
    accent: string;
    path: string;
    category: 'real' | 'simulated';
  }[] = [
    {
      id: 'football',
      short: 'Football',
      title: 'Football Matchday Screener',
      description: 'Half-time and full-time profile analysis. Correct score clusters, BTTS, 5-lamp scoreboards, and live market ranking.',
      accent: '#22c55e',
      path: '/football',
      category: 'real'
    },
    {
      id: 'basketball',
      short: 'Basketball',
      title: 'Basketball Matchday Screener',
      description: 'Market Expected Total (MET) analysis. Team totals, quarter pace, spread ranking — all in one view.',
      accent: '#f97316',
      path: '/basketball',
      category: 'real'
    },
    {
      id: 'tennis',
      short: 'Tennis',
      title: 'Tennis Matchday Screener',
      description: 'Market Expected Games (MEG), correct score intelligence, surface modifiers, and dual tiebreak signals.',
      accent: '#e879f9',
      path: '/tennis',
      category: 'real'
    },
    {
      id: 'rally',
      short: 'Table Tennis',
      title: 'Table Tennis Matchday Screener',
      description: 'Full match and first-set multi-market screening. Safest pick, margin rank, sweep shapes and set metrics.',
      accent: '#38bdf8',
      path: '/rally',
      category: 'real'
    },
    {
      id: 'hockey',
      short: 'Ice Hockey',
      title: 'Ice Hockey Matchday Screener',
      description: 'Puck line handicap, 3-period goal pace, Overtime Intelligence, and Correct Score Reconciliation.',
      accent: '#06b6d4',
      path: '/hockey',
      category: 'real'
    },
    {
      id: 'baseball',
      short: 'Baseball',
      title: 'Baseball Matchday Screener',
      description: '21 baseball markets across 9-Inning, 1-5 Innings, 1st Inning, and Extra-Innings probability extraction.',
      accent: '#8b5cf6',
      path: '/baseball',
      category: 'real'
    },
    {
      id: 'instant-football',
      short: 'Flash Line',
      title: 'Instant Football Screener',
      description: '5 target selections focus (Over 0.5/1.5, BTTS, Team Over 0.5) with Teams To Score 4-way triangulation engine.',
      accent: '#10b981',
      path: '/instant-football',
      category: 'simulated'
    },
    {
      id: 'instant-basketball',
      short: 'Court Line',
      title: 'Instant Basketball Screener',
      description: '4 target markets (Match Total, Handicap, Team Totals) with OT Regulation Draw consistency check.',
      accent: '#f59e0b',
      path: '/instant-basketball',
      category: 'simulated'
    },
    {
      id: 'vfootball',
      short: 'Pulse Line',
      title: 'Virtual Football Screener',
      description: 'Fast 3-minute round screening (Over 1.5/2.5, BTTS) with 16-scoreline joint distribution grid.',
      accent: '#06b6d4',
      path: '/vfootball',
      category: 'simulated'
    }
  ];

  const realSports = $derived(sports.filter((s) => s.category === 'real'));
  const simulatedSports = $derived(sports.filter((s) => s.category === 'simulated'));

  const comingSoonSports: Array<{ short: string; title: string; description: string; accent: string; emoji: string }> = [];

  const PREDICTOR_LABEL: Record<PredictorSportId, string> = {
    football: 'Football',
    basketball: 'Basketball',
    tennis: 'Tennis',
    rally: 'Table Tennis',
    hockey: 'Ice Hockey',
    baseball: 'Baseball'
  };

  function nav(p: string) {
    void goto(p);
  }

  const features = [
    { icon: '⚡', label: 'Live Profiles' },
    { icon: '🎯', label: 'Smart Ranking' },
    { icon: '📊', label: 'Decimal Odds' },
    { icon: '💾', label: 'Auto-Save' },
    { icon: '📱', label: 'Works Offline' }
  ];

  const steps = [
    {
      num: 1,
      title: 'Choose Match & Sport',
      desc: 'Select any match/game from sports of Football, Basketball, Tennis, or Table Tennis.'
    },
    {
      num: 2,
      title: 'Launch Screener',
      desc: 'Click the Sport card on the homepage to navigate you to the selected sport screener.'
    },
    {
      num: 3,
      title: 'Input Bookmaker Lines & Odds',
      desc: 'Input by selecting the lines and odds as displayed on your favourite bookmaker or bookies site into the fields.'
    },
    {
      num: 4,
      title: 'Run Odds Screening Magic',
      desc: 'Allow the PulseOdds Screener perform his magic with instant mathematical analysis.'
    },
    {
      num: 5,
      title: 'Manage Your Workspace',
      desc: 'Clear or save to history to screen another match/game seamlessly.'
    },
    {
      num: 6,
      title: 'Build Informed Betslips',
      desc: 'Build your slip with informed verdicts and stake responsibly.'
    },
    {
      num: 7,
      title: 'Beat the Bookies Together',
      desc: 'Lets beat the bookies together as Intelligent and informed punters.'
    }
  ];

  const predictorSteps = [
    { icon: Target, title: 'Pick a sport', desc: 'Football, Basketball, Tennis, Table Tennis, Ice Hockey or Baseball.' },
    { icon: Clock3, title: 'Watch the meter', desc: 'The agent team shows live 0% → 100% progress while they work.' },
    { icon: ShieldCheck, title: 'Review the picks', desc: 'Only matches above the 60% Real Win Chance floor — with top selections, punter edge and risk warnings.' },
    { icon: TrendingUp, title: 'Stake responsibly', desc: 'Refresh anytime; the cache rebuilds automatically each night.' }
  ];
</script>

<!-- SEO component renders all meta, OG, Twitter, canonical, JSON-LD from server load() data -->
<SEO seo={data.seo} />

<div class="landing-root">
  <!-- Aurora background orbs -->
  <div class="aurora-orb orb-1" aria-hidden="true"></div>
  <div class="aurora-orb orb-2" aria-hidden="true"></div>
  <div class="aurora-orb orb-3" aria-hidden="true"></div>

  <main class="landing-inner">

    <!-- Top header actions -->
    <div class="topbar">
      <div class="topbar-brand">
        <span class="pulse-icon" aria-hidden="true">⚡</span>
        <strong>PulseOdds</strong>
      </div>
      <div class="header-actions">
        <ThemeToggle />
        {#if authState.isAuthenticated}
          <button class="auth-btn logout-btn" onclick={() => {
            void convexSignOut().finally(() => setUnauthenticated());
          }}>
            <LogOut size={16} /> Sign Out
          </button>
        {:else}
          <a href="/auth" class="auth-btn login-btn">Log In</a>
          <a href="/auth?mode=signup" class="auth-btn signup-btn">Sign Up</a>
        {/if}
      </div>
    </div>

    <!-- ── E-WIN Project Ecosystem Banner ──────────────────────── -->
    <!-- itemscope/itemtype bind PulseOdds as a member of the E-WIN Organization -->
    <!-- AEO: Signals org hierarchy to LLMs and knowledge graph crawlers -->
    <div class="ewin-banner-wrapper" aria-live="polite">
      <EWINBanner />
    </div>

    <!-- ── Hero ──────────────────────────────────────────── -->
    <section class="hero" aria-label="PulseOdds hero">
      <div class="eyebrow-pill">
        <span class="eyebrow-dot" aria-hidden="true"></span>
        Sports Odds Intelligence
      </div>

      <h1 class="wordmark">
        Pulse<span class="wordmark-accent">Odds</span>
      </h1>

      <p class="tagline">Read the odds. Own the edge. Beat the Bookies</p>

      <p class="hero-copy">
        A mobile-first workspace for screening football, basketball, tennis, ping pong, ice hockey,
        instant football, instant basketball, virtual football and baseball markets.
        Drop in your odds, get instant profile verdicts, live rankings and smart picks — powered by Agnes AI Copilot.
      </p>

      <!-- Feature pills -->
      <ul class="feature-pills" aria-label="Key features">
        {#each features as f}
          <li class="pill">
            <span aria-hidden="true">{f.icon}</span>
            {f.label}
          </li>
        {/each}
      </ul>
    </section>

    <!-- ── Real Sports Section ──────────────────────────────── -->
    <section class="sport-section" aria-label="Real sports matchday screeners">
      <div class="section-head">
        <h2 class="section-title">Real Sports Matchday Screeners</h2>
        <span class="sport-count-badge">{realSports.length} sports</span>
      </div>

      <div class="sport-grid">
        {#each realSports as s}
          <SportCard
            sportId={s.id}
            short={s.short}
            title={s.title}
            description={s.description}
            accent={s.accent}
            onClick={() => nav(s.path)}
          />
        {/each}
      </div>
    </section>

    <!-- ── Virtual & Simulated Section ───────────────────────── -->
    <section class="sport-section" aria-label="Virtual and instant simulated screeners">
      <div class="section-head">
        <h2 class="section-title">Virtual &amp; Instant Simulated Screeners</h2>
        <span class="sport-count-badge">{simulatedSports.length} screeners</span>
      </div>

      <div class="sport-grid">
        {#each simulatedSports as s}
          <SportCard
            sportId={s.id}
            short={s.short}
            title={s.title}
            description={s.description}
            accent={s.accent}
            onClick={() => nav(s.path)}
          />
        {/each}
      </div>
    </section>

    <!-- ── AI Predictor Section ─────────────────────────────── -->
    <section class="ai-predictor-section" aria-label="AI Predictor by the PulseOdds agent team">
      <div class="section-head">
        <h2 class="section-title">AI Predictor &amp; Great AI Minds Consensus Engine</h2>
        <span class="predictor-badge">52% Confidence Floor · 3x Daily Auto-Sync</span>
      </div>

      <div class="predictor-card">
        <div class="predictor-orbit-wrap">
          <AgentOrbit accent="#6366f1" height={300} />
          <div class="orbit-caption">
            <Bot size={14} />
            <span>9 Specialist Agents · Led by Eze Ugo</span>
          </div>
        </div>

        <p class="predictor-copy">
          The <strong>AI Predictor</strong> is an enterprise multi-agent engine synchronized directly with our Convex backend.
          Three times daily (<strong>00:00 UTC, 06:00 UTC &amp; 12:00 UTC</strong>), the 9 specialist agents pull fixtures,
          cross-reference decimal odds from <strong>betwatch.fr</strong> and global betting registries, normalize probability metrics,
          and execute 5-round <strong>Great AI Minds debates</strong> across Claude Opus 4.0, ChatGPT 3.2 Pro, Kimi K2.5, Qwen 3.5, and Grok 4.2.
          Only selections clearing our mathematical probability floor surface as qualifying recommendations.
        </p>

        <div class="predictor-agents" aria-label="The agent team">
          {#each AGENT_DEFS as agent}
            <span class="agent-pill" title={`${agent.name} — ${agent.role}: ${agent.description}`}>
              <span class="agent-dot"></span>
              <span class="agent-name">{agent.name}</span>
            </span>
          {/each}
        </div>

        <!-- Great AI Minds Machine Highlight -->
        <div class="great-minds-highlight">
          <div class="gm-head">
            <span class="gm-sparkle">🧠</span>
            <strong>Great AI Minds 5-Model Consensus Engine</strong>
          </div>
          <div class="gm-grid">
            <div class="gm-chip"><span class="gm-dot"></span><b>Claude Opus 4.0</b> (Moderator &amp; Synthesis)</div>
            <div class="gm-chip"><span class="gm-dot"></span><b>ChatGPT 3.2 Pro</b> (+EV Data Scientist)</div>
            <div class="gm-chip"><span class="gm-dot"></span><b>Kimi K2.5</b> (Tempo &amp; Historical Analyst)</div>
            <div class="gm-chip"><span class="gm-dot"></span><b>Qwen 3.5</b> (Line Efficiency Technician)</div>
            <div class="gm-chip"><span class="gm-dot"></span><b>Grok 4.2</b> (Contrarian Risk Auditor)</div>
          </div>
        </div>

        <div class="predictor-steps">
          <div class="predictor-step title-row">
            <Sparkles size={16} />
            <span>How the SMOA pipeline operates</span>
          </div>
          {#each predictorSteps as step}
            <div class="predictor-step">
              <span class="step-ic"><step.icon size={15} stroke-width={2.3} /></span>
              <div class="step-body">
                <b>{step.title}</b>
                <span>{step.desc}</span>
              </div>
            </div>
          {/each}
        </div>

        <div class="predictor-sports" aria-label="Supported predictor sports">
          {#each PREDICTOR_SPORTS as sport}
            <span class="psport-chip" title={PREDICTOR_LABEL[sport]}>
              <PredictorSportIcon sport={sport} size={15} strokeWidth={2} />
              {PREDICTOR_LABEL[sport]}
            </span>
          {/each}
        </div>

        <div class="predictor-cta">
          <AiPredictorButton label="Open the AI Predictor &amp; Great Minds Engine" accent="#6366f1" />
        </div>
      </div>
    </section>

    <!-- ── Offline Master Model Framework & Interactive Sandbox Section ── -->
    <section class="master-model-section" aria-label="Offline Master Model Framework">
      <MasterModelShowcase />
    </section>

    <!-- ── Coming Soon Sports Section (hidden when empty) ─────────── -->
    {#if comingSoonSports.length > 0}
    <section class="coming-soon-section" aria-label="Coming soon sports">
      <div class="section-head">
        <h2 class="section-title">Coming Soon</h2>
        <span class="cs-count-badge">{comingSoonSports.length} in development</span>
      </div>

      <div class="sport-grid">
        {#each comingSoonSports as cs}
          <SportCard
            short={cs.short}
            title={cs.title}
            description={cs.description}
            accent={cs.accent}
            emoji={cs.emoji}
            comingSoon={true}
          />
        {/each}
      </div>
    </section>
    {/if}

    <!-- ── How to Use PulseOdds ───────────────────────────── -->
    <section class="how-to-use-section" aria-label="How to use PulseOdds">
      <div class="section-head">
        <h2 class="section-title">How to Use PulseOdds</h2>
        <span class="step-count-badge">7 Easy Steps</span>
      </div>

      <p class="section-sub">Follow these 7 steps to master sports screening and unlock your statistical edge.</p>



      <div class="steps-grid">
        {#each steps as step}
          <div class="step-card">
            <div class="step-num-badge">
              <span class="step-num">{step.num}</span>
            </div>
            <div class="step-content">
              <h3 class="step-title">{step.title}</h3>
              <p class="step-desc">{step.desc}</p>
            </div>
          </div>
        {/each}
      </div>
    </section>

    <!-- ── Pricing Section ────────────────────────────────── -->
    <section class="pricing-section" aria-label="Subscription and pricing">
      <div class="section-head">
        <h2 class="section-title">Subscription & Access</h2>
        <span class="pricing-badge">Monthly Pass</span>
      </div>

      <div class="pricing-card">
        <div class="pricing-glow" aria-hidden="true"></div>
        <div class="pricing-header">
          <span class="pass-tag">Punter Access Pass</span>
          <h3 class="pricing-title">Full All-Sport Screener Access</h3>
          <div class="price-box">
            <span class="currency">₦</span>
            <span class="amount">5,000</span>
            <span class="period">/ month</span>
          </div>
          <p class="pricing-copy">
            To access all five sport screeners (Football, Basketball, Tennis, Table Tennis & Ice Hockey), all punters are required to make a monthly donation of <strong>₦5,000 Naira</strong>.
          </p>
        </div>

        <ul class="pricing-features">
          <li>
            <CheckCircle2 class="icon-check" size={18} />
            <span>Unlimited screening access across Football, Basketball, Tennis, Table Tennis & Ice Hockey</span>
          </li>
          <li>
            <CheckCircle2 class="icon-check" size={18} />
            <span>4-Profile mathematical verdict engine with 5-lamp confidence scoring</span>
          </li>
          <li>
            <CheckCircle2 class="icon-check" size={18} />
            <span>Top Pick rankings with gold/silver/bronze value badges</span>
          </li>
          <li>
            <CheckCircle2 class="icon-check" size={18} />
            <span>Sequential decimal odds picker (1.01 - 5.00 by 0.01) & line selector</span>
          </li>
          <li>
            <CheckCircle2 class="icon-check" size={18} />
            <span>Convex-backed history sync & offline-first local storage</span>
          </li>
        </ul>

        <button type="button" class="btn-donate" onclick={handleDonateClick}>
          <HeartHandshake size={20} />
          Donate ₦5,000 / Month & Get Access
        </button>

        <a
          href="https://wa.me/2349025152818?text=Hello%20Founder%2C%20I%20have%20an%20enquiry%20regarding%20PulseOdds%20Screener"
          target="_blank"
          rel="noopener noreferrer"
          class="btn-whatsapp"
        >
          <MessageSquare size={20} />
          Chat / Make Enquiries with Founder on WhatsApp
        </a>
      </div>
    </section>

    <!-- ── Disclaimer Section ─────────────────────────────── -->
    <section class="disclaimer-section" aria-label="Disclaimer">
      <div class="disclaimer-card">
        <div class="disclaimer-head">
          <ShieldAlert class="disc-icon" size={24} />
          <h3 class="disc-title">Important Disclaimer & Responsible Staking</h3>
        </div>

        <div class="disc-body">
          <p>
            <strong>PulseOdds</strong> is an analytical sports odds screening and statistical calculation tool designed exclusively for informational and educational purposes.
          </p>
          <p>
            We are <strong>NOT a bookmaker, gambling operator, or betting service</strong>. We do not accept bets, process wagers, or handle financial gambling transactions.
          </p>
          <p>
            Sports betting inherently involves financial risk. Statistical indicators, confidence ratios, profile ratings, and verdicts generated by PulseOdds do <strong>NOT guarantee winning outcomes or financial profit</strong>. Past performance and statistical metrics do not ensure future results.
          </p>
          <p class="disc-highlight">
            Stake responsibly. Never stake money you cannot afford to lose. Comply strictly with all local gambling laws in your jurisdiction. Strictly 18+ only.
          </p>
        </div>
      </div>
    </section>

    <!-- ── Footer ────────────────────────────────────────── -->
    <!-- itemscope for footer organization schema — reinforces E-WIN entity binding -->
    <footer class="foot" aria-label="App info" itemscope itemtype="https://schema.org/Organization">
      <meta itemprop="name" content="PulseOdds" />
      <meta itemprop="url" content="https://pulseodds.ewinproject.org" />
      <div class="foot-brand">
        <span class="foot-logo" aria-hidden="true">⚡</span>
        <strong itemprop="legalName">PulseOdds</strong>
        <span class="foot-version">v2.0</span>
      </div>
      <p class="foot-copy">Read the odds. Own the edge. Beat the Bookies · Strictly 18+</p>
      <p class="foot-ewin">
        Part of the <a href="https://ewinproject.org" target="_blank" rel="noopener noreferrer" itemprop="memberOf">E-WIN Project</a> Ecosystem
        · Built by <a href="https://omaledanjumaogale.ewinproject.org/" target="_blank" rel="noopener noreferrer" itemprop="founder">Omale Danjuma Ogale</a>
      </p>
      <div class="foot-sports" aria-label="Available sports">
        <span>⚽</span><span>🏀</span><span>🎾</span><span>🏓</span><span>🏒</span><span>⚾</span>
      </div>
    </footer>

  </main>

  <!-- Mobile bottom nav -->
  <BottomNav />
</div>

<style>
  /* ── Root & Centered Alignment ─────────────────────────────── */
  .landing-root {
    position: relative;
    width: 100%;
    min-height: 100dvh;
    overflow: hidden;
  }

  /* ── Aurora Orbs ────────────────────────────────────────────── */
  .aurora-orb {
    position: fixed;
    border-radius: 50%;
    filter: blur(80px);
    pointer-events: none;
    z-index: 0;
  }
  .orb-1 {
    width: 600px; height: 600px;
    top: -200px; right: -100px;
    background: radial-gradient(circle, color-mix(in srgb, var(--c-orange) 22%, transparent) 0%, transparent 70%);
    animation: aurora-drift 18s ease-in-out infinite;
  }
  .orb-2 {
    width: 500px; height: 500px;
    bottom: -100px; left: -150px;
    background: radial-gradient(circle, color-mix(in srgb, var(--c-orange-green) 16%, transparent) 0%, transparent 70%);
    animation: aurora-drift 24s ease-in-out infinite reverse;
  }
  .orb-3 {
    width: 400px; height: 400px;
    top: 40%; left: 40%;
    background: radial-gradient(circle, color-mix(in srgb, var(--c-rally) 10%, transparent) 0%, transparent 70%);
    animation: aurora-drift 30s ease-in-out infinite 8s;
  }

  /* ── Layout — Fully Centered ─────────────────────────────────── */
  .landing-inner {
    position: relative;
    z-index: 1;
    width: min(100%, 960px);
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    padding:
      max(24px, env(safe-area-inset-top))
      max(16px, env(safe-area-inset-right))
      max(100px, calc(env(safe-area-inset-bottom) + 88px))
      max(16px, env(safe-area-inset-left));
    min-width: 320px;
  }

  /* ── Home Topbar ────────────────────────────────────────────── */
  .topbar {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 0 16px;
    margin-bottom: 0;
  }

  /* ── E-WIN Banner Wrapper ────────────────────────────────────── */
  /* Spans full available width, flush against topbar bottom */
  .ewin-banner-wrapper {
    width: calc(100% + 32px); /* bleed past landing-inner padding */
    margin: 0 -16px 16px;
    /* AEO: banner visible immediately on page load for all crawlers */
  }
  @media (max-width: 440px) {
    .ewin-banner-wrapper { width: calc(100% + 24px); margin: 0 -12px 12px; }
  }

  .topbar-brand {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 16px;
    font-weight: 900;
    color: var(--c-text);
  }
  .pulse-icon {
    font-size: 20px;
    filter: drop-shadow(0 0 6px var(--c-orange));
  }

  /* ── Auth Buttons ────────────────────────────────────────────── */
  .header-actions {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-left: auto;
  }
  .auth-btn {
    font-size: 13px;
    font-weight: 800;
    padding: 6px 14px;
    border-radius: 999px;
    text-decoration: none;
    transition: all var(--t-base);
  }
  .login-btn {
    color: var(--c-text);
    background: transparent;
  }
  .login-btn:hover {
    color: var(--c-orange);
  }
  .signup-btn {
    color: var(--c-bg);
    background: var(--c-orange);
    box-shadow: 0 0 10px color-mix(in srgb, var(--c-orange) 40%, transparent);
  }
  .signup-btn:hover {
    background: color-mix(in srgb, var(--c-orange) 80%, white);
    transform: translateY(-1px);
  }
  .logout-btn {
    display: flex;
    align-items: center;
    gap: 6px;
    background: color-mix(in srgb, var(--c-red) 15%, transparent);
    color: var(--c-red);
    border: none;
    cursor: pointer;
  }
  .logout-btn:hover {
    background: color-mix(in srgb, var(--c-red) 30%, transparent);
  }

  /* ── Hero — Centered ────────────────────────────────────────── */
  .hero {
    padding: 24px 0 32px;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    animation: slide-up 0.5s ease both;
    width: 100%;
  }

  .eyebrow-pill {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 6px 14px;
    border-radius: 999px;
    background: color-mix(in srgb, var(--c-orange) 14%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-orange) 35%, transparent);
    color: var(--c-orange);
    font-size: 12px;
    font-weight: 800;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    margin-bottom: 22px;
  }
  .eyebrow-dot {
    width: 7px; height: 7px;
    border-radius: 50%;
    background: var(--c-orange);
    box-shadow: 0 0 8px var(--c-orange);
    animation: dot-pulse 2s ease-in-out infinite;
  }

  .wordmark {
    margin: 0 0 12px;
    font-size: clamp(44px, 13vw, 80px);
    font-weight: 900;
    line-height: 0.92;
    letter-spacing: -0.03em;
    color: var(--c-text);
    text-align: center;
  }
  .wordmark-accent {
    background: var(--c-brand-gradient, linear-gradient(135deg, #ff7700 0%, #ea580c 45%, #22c55e 100%));
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
  }

  .tagline {
    margin: 0 0 16px;
    font-size: clamp(17px, 4.2vw, 24px);
    font-weight: 800;
    letter-spacing: -0.01em;
    text-align: center;
    background: linear-gradient(135deg, var(--c-text) 0%, var(--c-orange) 100%);
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
  }

  .hero-copy {
    margin: 0 auto;
    color: var(--c-muted);
    line-height: 1.65;
    max-width: 680px;
    font-size: clamp(13px, 2.8vw, 15px);
    font-weight: 600;
    text-align: center;
  }

  /* ── Feature Pills — Centered ───────────────────────────────── */
  .feature-pills {
    list-style: none;
    padding: 0;
    margin: 24px 0 0;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 8px;
    width: 100%;
  }
  .pill {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 7px 14px;
    border-radius: 999px;
    background: var(--c-surface-2);
    border: 1px solid var(--c-border);
    color: var(--c-text-2);
    font-size: 12.5px;
    font-weight: 700;
    backdrop-filter: blur(8px);
    transition: background var(--t-base), border-color var(--t-base), color var(--t-base);
  }
  .pill:hover {
    background: color-mix(in srgb, var(--c-orange) 14%, var(--c-surface-2));
    border-color: color-mix(in srgb, var(--c-orange) 35%, transparent);
    color: var(--c-orange);
  }

  /* ── Common Section Headers — Centered ─────────────────────── */
  .sport-section, .coming-soon-section, .how-to-use-section, .pricing-section, .disclaimer-section, .master-model-section, .ai-predictor-section {
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
  }

  .section-head {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    margin: 40px 0 18px;
    flex-wrap: wrap;
  }
  .section-title {
    font-size: 14px;
    color: var(--c-text);
    letter-spacing: 0.08em;
    text-transform: uppercase;
    font-weight: 900;
    margin: 0;
    text-align: center;
  }
  .section-sub {
    margin: -8px 0 24px;
    color: var(--c-muted);
    font-size: 13.5px;
    font-weight: 600;
    max-width: 600px;
    text-align: center;
  }

  .sport-count-badge {
    font-size: 11px;
    font-weight: 800;
    color: var(--c-football);
    background: color-mix(in srgb, var(--c-football) 14%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-football) 30%, transparent);
    padding: 3px 10px;
    border-radius: 999px;
  }
  .cs-count-badge {
    font-size: 11px;
    font-weight: 800;
    color: var(--c-amber);
    background: color-mix(in srgb, var(--c-amber) 14%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-amber) 30%, transparent);
    padding: 3px 10px;
    border-radius: 999px;
  }
  .step-count-badge {
    font-size: 11px;
    font-weight: 800;
    color: var(--c-rally);
    background: color-mix(in srgb, var(--c-rally) 14%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-rally) 30%, transparent);
    padding: 3px 10px;
    border-radius: 999px;
  }
  .pricing-badge {
    font-size: 11px;
    font-weight: 800;
    color: var(--c-orange);
    background: color-mix(in srgb, var(--c-orange) 14%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-orange) 30%, transparent);
    padding: 3px 10px;
    border-radius: 999px;
  }

  .sport-grid {
    display: grid;
    gap: 14px;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    width: 100%;
  }

  /* ── How to Use Section ────────────────────────────────────── */
  .steps-grid {
    display: grid;
    gap: 12px;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    width: 100%;
  }

  .step-card {
    display: flex;
    align-items: flex-start;
    gap: 14px;
    padding: 18px;
    border-radius: 16px;
    background: var(--c-surface-2);
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
    border: 1px solid var(--c-border);
    box-shadow: var(--c-card-shadow);
    text-align: left;
    transition: transform 180ms ease, border-color 180ms ease, background 180ms ease;
  }
  .step-card:hover {
    transform: translateY(-2px);
    border-color: color-mix(in srgb, var(--c-orange) 40%, transparent);
    background: var(--c-surface-3);
  }

  .step-num-badge {
    width: 38px;
    height: 38px;
    border-radius: 12px;
    background: color-mix(in srgb, var(--c-orange) 15%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-orange) 35%, transparent);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }
  .step-num {
    font-size: 16px;
    font-weight: 900;
    color: var(--c-orange);
    font-family: var(--font-mono, 'JetBrains Mono', monospace);
  }

  .step-content {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .step-title {
    margin: 0;
    font-size: 14.5px;
    font-weight: 800;
    color: var(--c-text);
    line-height: 1.3;
  }
  .step-desc {
    margin: 0;
    font-size: 12.5px;
    color: var(--c-muted);
    line-height: 1.55;
    font-weight: 600;
  }

  /* ── Pricing Section ───────────────────────────────────────── */
  .pricing-card {
    position: relative;
    width: min(100%, 640px);
    margin: 0 auto;
    padding: 32px 24px;
    border-radius: 24px;
    background: var(--c-surface-2);
    backdrop-filter: blur(20px);
    -webkit-backdrop-filter: blur(20px);
    border: 1px solid color-mix(in srgb, var(--c-orange) 40%, transparent);
    box-shadow: 0 16px 48px -12px color-mix(in srgb, var(--c-orange) 20%, transparent);
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    overflow: hidden;
  }

  .pricing-glow {
    position: absolute;
    top: -100px; left: 50%;
    transform: translateX(-50%);
    width: 300px; height: 300px;
    border-radius: 50%;
    background: radial-gradient(circle, color-mix(in srgb, var(--c-orange) 25%, transparent) 0%, transparent 70%);
    pointer-events: none;
  }

  .pricing-header {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    margin-bottom: 24px;
    position: relative;
    z-index: 1;
  }

  .pass-tag {
    font-size: 10px;
    font-weight: 900;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--c-orange);
    background: color-mix(in srgb, var(--c-orange) 14%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-orange) 30%, transparent);
    padding: 4px 12px;
    border-radius: 999px;
  }

  .pricing-title {
    font-size: clamp(20px, 4vw, 26px);
    font-weight: 900;
    color: var(--c-text);
    margin: 4px 0;
  }

  .price-box {
    display: flex;
    align-items: baseline;
    justify-content: center;
    gap: 4px;
    margin: 8px 0;
    color: var(--c-text);
  }
  .price-box .currency {
    font-size: 24px;
    font-weight: 900;
    color: var(--c-orange);
  }
  .price-box .amount {
    font-size: 42px;
    font-weight: 900;
    letter-spacing: -0.02em;
    font-family: var(--font-mono, 'JetBrains Mono', monospace);
    color: var(--c-text);
  }
  .price-box .period {
    font-size: 14px;
    color: var(--c-muted);
    font-weight: 700;
  }

  .pricing-copy {
    margin: 0;
    font-size: 13.5px;
    color: var(--c-text-2);
    line-height: 1.6;
    max-width: 500px;
  }

  .pricing-features {
    list-style: none;
    padding: 0;
    margin: 0 0 28px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    text-align: left;
    width: 100%;
    max-width: 520px;
    position: relative;
    z-index: 1;
  }
  .pricing-features li {
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 13px;
    color: var(--c-text);
    font-weight: 700;
    line-height: 1.4;
  }
  .pricing-features :global(.icon-check) {
    color: var(--c-orange);
    flex-shrink: 0;
  }

  .btn-donate {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    width: 100%;
    max-width: 480px;
    min-height: 52px;
    padding: 12px 24px;
    border-radius: 14px;
    background: var(--c-brand-gradient, linear-gradient(135deg, #ff7700 0%, #ea580c 45%, #22c55e 100%));
    border: 1px solid rgba(255, 255, 255, 0.2);
    color: #ffffff;
    font-size: 15px;
    font-weight: 900;
    font-family: var(--font-brand, 'Outfit', system-ui);
    cursor: pointer;
    box-shadow: 0 8px 24px -4px color-mix(in srgb, var(--c-orange) 45%, transparent);
    transition: transform 180ms ease, box-shadow 180ms ease;
    position: relative;
    z-index: 1;
  }
  .btn-donate:hover {
    transform: translateY(-2px);
    box-shadow: 0 12px 32px -4px color-mix(in srgb, var(--c-orange) 65%, transparent);
  }
  .btn-donate:active { transform: scale(0.98); }

  .btn-whatsapp {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    width: 100%;
    max-width: 480px;
    min-height: 50px;
    margin-top: 12px;
    padding: 12px 24px;
    border-radius: 14px;
    background: #25d366;
    border: 1px solid rgba(255, 255, 255, 0.25);
    color: #ffffff;
    font-size: 14.5px;
    font-weight: 800;
    font-family: var(--font-brand, 'Outfit', system-ui);
    text-decoration: none;
    cursor: pointer;
    box-shadow: 0 8px 24px -4px rgba(37, 211, 102, 0.4);
    transition: transform 180ms ease, box-shadow 180ms ease, background 180ms ease;
    position: relative;
    z-index: 1;
  }
  .btn-whatsapp:hover {
    background: #22c55e;
    transform: translateY(-2px);
    box-shadow: 0 12px 32px -4px rgba(37, 211, 102, 0.6);
    color: #ffffff;
  }
  .btn-whatsapp:active { transform: scale(0.98); }

  /* ── AI Predictor Section ─────────────────────────────────── */
  .predictor-badge {
    font-size: 11px;
    font-weight: 800;
    color: var(--c-rally);
    background: color-mix(in srgb, var(--c-rally) 14%, var(--c-surface));
    border: 1px solid color-mix(in srgb, var(--c-rally) 30%, transparent);
    padding: 3px 10px;
    border-radius: 999px;
  }

  .predictor-card {
    width: min(100%, 760px);
    padding: 24px;
    border-radius: 20px;
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--c-rally) 10%, transparent), transparent 55%),
      var(--c-surface-2);
    border: 1px solid color-mix(in srgb, var(--c-rally) 35%, transparent);
    box-shadow: var(--c-card-shadow);
    text-align: left;
  }

  .predictor-orbit-wrap {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: -8px 0 6px;
  }

  .orbit-caption {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    margin-top: -6px;
    font-size: 11.5px;
    font-weight: 700;
    color: var(--c-text-2, var(--c-text-dim));
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    padding: 5px 12px;
    border-radius: 999px;
  }

  .orbit-caption :global(svg) { color: var(--c-rally); }

  .predictor-copy {
    margin: 0 0 16px;
    font-size: 13.5px;
    line-height: 1.65;
    color: var(--c-text-2);
  }
  .predictor-copy strong { color: var(--c-text); }

  .predictor-agents {
    display: flex;
    flex-wrap: wrap;
    gap: 7px;
    margin-bottom: 18px;
  }

  .agent-pill {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 5px 10px;
    border-radius: 999px;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    font-size: 11px;
    font-weight: 700;
    color: var(--c-text-2);
    transition: border-color var(--t-base), color var(--t-base), background var(--t-base);
  }
  .agent-pill:hover {
    border-color: color-mix(in srgb, var(--c-rally) 45%, transparent);
    color: var(--c-text);
    background: var(--c-glass-hover);
  }

  .agent-dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: var(--c-rally);
    box-shadow: 0 0 6px var(--c-rally);
  }

  .predictor-steps {
    margin-bottom: 18px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .predictor-step {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    padding: 10px 12px;
    border-radius: 12px;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
  }

  .predictor-step.title-row {
    align-items: center;
    font-size: 11px;
    font-weight: 900;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--c-rally);
    background: transparent;
    border: none;
    padding: 0 2px 2px;
  }

  .predictor-step.title-row :global(svg) { color: var(--c-rally); }

  .step-ic {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    width: 28px;
    height: 28px;
    border-radius: 9px;
    background: color-mix(in srgb, var(--c-rally) 15%, transparent);
    border: 1px solid color-mix(in srgb, var(--c-rally) 32%, transparent);
    color: var(--c-rally);
  }

  .step-body {
    display: flex;
    flex-direction: column;
    gap: 2px;
    font-size: 12.5px;
    color: var(--c-text-2);
    line-height: 1.5;
  }
  .step-body b { color: var(--c-text); }

  .predictor-sports {
    display: flex;
    flex-wrap: wrap;
    gap: 7px;
    margin-bottom: 18px;
  }

  .psport-chip {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 5px 10px;
    border-radius: 999px;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    font-size: 11px;
    font-weight: 700;
    color: var(--c-text-2);
    transition: border-color var(--t-base), color var(--t-base), transform 80ms ease;
  }
  .psport-chip:hover {
    border-color: color-mix(in srgb, var(--c-rally) 40%, transparent);
    color: var(--c-text);
    transform: translateY(-1px);
  }
  .psport-chip :global(svg) { color: var(--c-rally); }

  .predictor-cta {
    display: flex;
    justify-content: center;
  }

  /* ── Great AI Minds Machine Highlight ──────────────────────── */
  .great-minds-highlight {
    margin: 20px 0;
    padding: 16px;
    border-radius: 14px;
    background: color-mix(in srgb, #6366f1 10%, var(--c-surface));
    border: 1px solid color-mix(in srgb, #6366f1 35%, transparent);
    text-align: left;
  }

  .gm-head {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 13px;
    font-weight: 800;
    color: var(--c-text);
    margin-bottom: 12px;
  }

  .gm-sparkle { font-size: 16px; }

  .gm-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 8px;
  }

  .gm-chip {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 11.5px;
    padding: 6px 10px;
    border-radius: 8px;
    background: var(--c-surface-2);
    border: 1px solid var(--c-border);
    color: var(--c-text);
  }

  .gm-dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: #6366f1;
    box-shadow: 0 0 8px #6366f1;
    flex-shrink: 0;
  }

  /* ── Disclaimer Section ────────────────────────────────────── */
  .disclaimer-card {
    width: min(100%, 720px);
    margin: 28px auto 0;
    padding: 24px;
    border-radius: 18px;
    background: color-mix(in srgb, var(--c-red) 8%, var(--c-surface-2));
    border: 1px solid color-mix(in srgb, var(--c-red) 30%, transparent);
    backdrop-filter: blur(12px);
    text-align: left;
    box-shadow: var(--c-card-shadow);
  }

  .disclaimer-head {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 12px;
  }
  .disclaimer-head :global(.disc-icon) {
    color: var(--c-red);
    flex-shrink: 0;
  }
  .disc-title {
    margin: 0;
    font-size: 15px;
    font-weight: 800;
    color: var(--c-text);
    letter-spacing: -0.01em;
  }

  .disc-body {
    display: flex;
    flex-direction: column;
    gap: 10px;
    font-size: 12.5px;
    color: var(--c-text-2);
    line-height: 1.6;
  }
  .disc-body p { margin: 0; }
  .disc-highlight {
    padding: 8px 12px;
    border-radius: 8px;
    background: color-mix(in srgb, var(--c-red) 14%, transparent);
    border-left: 3px solid var(--c-red);
    color: var(--c-text);
    font-weight: 700;
  }

  /* ── Footer ─────────────────────────────────────────────────── */
  .foot {
    margin-top: 56px;
    padding: 24px 0 8px;
    border-top: 1px solid var(--c-border);
    text-align: center;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    width: 100%;
  }
  .foot-brand {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
  }
  .foot-logo {
    font-size: 18px;
    filter: drop-shadow(0 0 6px var(--c-orange));
  }
  .foot-brand strong {
    font-size: 15px;
    font-weight: 900;
    color: var(--c-text);
    letter-spacing: -0.01em;
  }
  .foot-version {
    font-size: 10px;
    font-weight: 800;
    color: var(--c-orange);
    background: color-mix(in srgb, var(--c-orange) 14%, var(--c-surface));
    padding: 2px 7px;
    border-radius: 999px;
    letter-spacing: 0.04em;
  }
  .foot-copy {
    color: var(--c-muted);
    font-size: 12px;
    font-weight: 600;
    margin: 0;
  }
  .foot-sports {
    display: flex;
    justify-content: center;
    gap: 12px;
    font-size: 18px;
    margin-top: 4px;
  }

  /* ── Footer Extra Attribution ────────────────────────────────── */
  .foot-ewin {
    font-size: 11px;
    font-weight: 600;
    color: var(--c-muted);
    margin: 0;
    text-align: center;
    line-height: 1.5;
  }
  .foot-ewin a {
    color: var(--c-orange);
    text-decoration: none;
    font-weight: 700;
  }
  .foot-ewin a:hover {
    text-decoration: underline;
  }

  /* ── Responsive ─────────────────────────────────────────────── */
  @media (max-width: 440px) {
    .landing-inner { padding-left: 12px; padding-right: 12px; }
    .sport-grid, .steps-grid { grid-template-columns: 1fr; }
    .pricing-card { padding: 24px 16px; }
    .price-box .amount { font-size: 34px; }
    .btn-donate { font-size: 13.5px; padding: 12px 16px; }
  }
  @media (min-width: 768px) {
    .landing-inner { padding-bottom: max(40px, env(safe-area-inset-bottom)); }
  }
  @media (min-width: 1400px) {
    .landing-inner { width: min(100%, 1100px); }
  }
</style>
