<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import SportCard from '$lib/components/SportCard.svelte';
  import BottomNav from '$lib/components/BottomNav.svelte';

  type SportId = 'football' | 'basketball' | 'tennis' | 'rally';

  const sports: {
    id: SportId;
    short: string;
    title: string;
    description: string;
    accent: string;
    path: string;
  }[] = [
    {
      id: 'football',
      short: 'Football',
      title: 'Football Screener',
      description: 'Half-time and full-time profile analysis. Correct score clusters, BTTS, 5-lamp scoreboards, and live market ranking.',
      accent: '#22c55e',
      path: '/football'
    },
    {
      id: 'basketball',
      short: 'Basketball',
      title: 'Basketball Screener',
      description: 'Market Expected Total (MET) analysis. Team totals, quarter pace, spread ranking — all in one view.',
      accent: '#f97316',
      path: '/basketball'
    },
    {
      id: 'tennis',
      short: 'Tennis',
      title: 'Tennis Screener',
      description: 'Market Expected Games (MEG), correct score intelligence, surface modifiers, and dual tiebreak signals.',
      accent: '#e879f9',
      path: '/tennis'
    },
    {
      id: 'rally',
      short: 'Rally / TT',
      title: 'Table Tennis Screener',
      description: 'Full match and first-set multi-market screening. Safest pick, margin rank, sweep shapes and set metrics.',
      accent: '#38bdf8',
      path: '/rally'
    }
  ];

  function nav(p: string) {
    try {
      if (typeof goto === 'function') { void (async () => { await goto(p); })(); }
    } catch (_) { /* ignore */ }
    if (typeof window !== 'undefined') {
      setTimeout(() => { if (window.location.pathname !== p) window.location.assign(p); }, 40);
    }
  }

  const features = [
    { icon: '⚡', label: 'Live Profiles' },
    { icon: '🎯', label: 'Smart Ranking' },
    { icon: '📊', label: 'Decimal Odds' },
    { icon: '💾', label: 'Auto-Save' },
    { icon: '📱', label: 'Works Offline' }
  ];
</script>

<svelte:head>
  <title>PulseOdds — Sports Odds Intelligence</title>
</svelte:head>

<div class="landing-root">
  <!-- Aurora background orbs -->
  <div class="aurora-orb orb-1" aria-hidden="true"></div>
  <div class="aurora-orb orb-2" aria-hidden="true"></div>
  <div class="aurora-orb orb-3" aria-hidden="true"></div>

  <main class="landing-inner">

    <!-- ── Hero ──────────────────────────────────────────── -->
    <section class="hero" aria-label="PulseOdds hero">
      <div class="eyebrow-pill">
        <span class="eyebrow-dot" aria-hidden="true"></span>
        Sports Odds Intelligence
      </div>

      <h1 class="wordmark">
        Pulse<span class="wordmark-accent">Odds</span>
      </h1>

      <p class="tagline">Read the odds. Own the edge.</p>

      <p class="hero-copy">
        A mobile-first workspace for screening football, basketball, tennis and table tennis markets.
        Drop in your odds, get instant profile verdicts, live rankings and smart picks — all saved to your device.
      </p>

      <!-- Feature pills -->
      <ul class="feature-pills" aria-label="Key features">
        {#each features as f}
          <li class="pill">
            <span aria-hidden="true">{f.icon}</span>
            {f.label}
          </li>
        {/each}
      </ul>
    </section>

    <!-- ── Sport Grid ─────────────────────────────────────── -->
    <section class="sport-section" aria-label="Choose a sport">
      <div class="section-head">
        <h2 class="section-title">Choose Your Sport</h2>
        <span class="sport-count-badge">{sports.length} sports</span>
      </div>

      <div class="sport-grid">
        {#each sports as s}
          <SportCard
            sportId={s.id}
            short={s.short}
            title={s.title}
            description={s.description}
            accent={s.accent}
            onClick={() => nav(s.path)}
          />
        {/each}
      </div>
    </section>

    <!-- ── Footer ────────────────────────────────────────── -->
    <footer class="foot" aria-label="App info">
      <div class="foot-brand">
        <span class="foot-logo" aria-hidden="true">⚡</span>
        <strong>PulseOdds</strong>
        <span class="foot-version">v2.0</span>
      </div>
      <p class="foot-copy">Offline-first · Decimal odds · No sign-up required</p>
      <div class="foot-sports" aria-label="Available sports">
        <span>⚽</span><span>🏀</span><span>🎾</span><span>🏓</span>
      </div>
    </footer>

  </main>

  <!-- Mobile bottom nav -->
  <BottomNav />
</div>

<style>
  /* ── Root ──────────────────────────────────────────────────── */
  .landing-root {
    position: relative;
    width: 100%;
    min-height: 100dvh;
    overflow: hidden;
  }

  /* ── Aurora Orbs ────────────────────────────────────────────── */
  .aurora-orb {
    position: fixed;
    border-radius: 50%;
    filter: blur(80px);
    pointer-events: none;
    z-index: 0;
  }
  .orb-1 {
    width: 600px; height: 600px;
    top: -200px; right: -100px;
    background: radial-gradient(circle, rgba(99,102,241,0.22) 0%, transparent 70%);
    animation: aurora-drift 18s ease-in-out infinite;
  }
  .orb-2 {
    width: 500px; height: 500px;
    bottom: -100px; left: -150px;
    background: radial-gradient(circle, rgba(139,92,246,0.18) 0%, transparent 70%);
    animation: aurora-drift 24s ease-in-out infinite reverse;
  }
  .orb-3 {
    width: 400px; height: 400px;
    top: 40%; left: 40%;
    background: radial-gradient(circle, rgba(56,189,248,0.10) 0%, transparent 70%);
    animation: aurora-drift 30s ease-in-out infinite 8s;
  }

  /* ── Layout ─────────────────────────────────────────────────── */
  .landing-inner {
    position: relative;
    z-index: 1;
    width: min(100%, 960px);
    margin: 0 auto;
    padding:
      max(24px, env(safe-area-inset-top))
      max(16px, env(safe-area-inset-right))
      max(100px, calc(env(safe-area-inset-bottom) + 88px))
      max(16px, env(safe-area-inset-left));
    min-width: 320px;
  }

  /* ── Hero ───────────────────────────────────────────────────── */
  .hero {
    padding: 40px 0 32px;
    animation: slide-up 0.5s ease both;
  }

  .eyebrow-pill {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 6px 14px;
    border-radius: 999px;
    background: rgba(99, 102, 241, 0.12);
    border: 1px solid rgba(99, 102, 241, 0.3);
    color: #a5b4fc;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    margin-bottom: 22px;
  }
  .eyebrow-dot {
    width: 7px; height: 7px;
    border-radius: 50%;
    background: #6366f1;
    box-shadow: 0 0 8px #6366f1;
    animation: dot-pulse 2s ease-in-out infinite;
  }

  .wordmark {
    margin: 0 0 12px;
    font-size: clamp(44px, 13vw, 80px);
    font-weight: 900;
    line-height: 0.92;
    letter-spacing: -0.03em;
    color: #f1f5ff;
  }
  .wordmark-accent {
    background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a3e635 100%);
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
  }

  .tagline {
    margin: 0 0 14px;
    font-size: clamp(16px, 4vw, 22px);
    font-weight: 700;
    color: #8899bb;
    letter-spacing: -0.01em;
  }

  .hero-copy {
    margin: 0;
    color: #8899bb;
    line-height: 1.65;
    max-width: 680px;
    font-size: clamp(13px, 2.8vw, 15px);
    font-weight: 500;
  }

  /* ── Feature Pills ──────────────────────────────────────────── */
  .feature-pills {
    list-style: none;
    padding: 0;
    margin: 24px 0 0;
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }
  .pill {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 7px 14px;
    border-radius: 999px;
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    color: #c8d6ee;
    font-size: 12.5px;
    font-weight: 600;
    backdrop-filter: blur(8px);
    transition: background var(--t-base), border-color var(--t-base);
  }
  .pill:hover {
    background: rgba(99, 102, 241, 0.12);
    border-color: rgba(99, 102, 241, 0.3);
    color: #a5b4fc;
  }

  /* ── Sport Section ──────────────────────────────────────────── */
  .sport-section { margin-top: 16px; }

  .section-head {
    display: flex;
    align-items: center;
    gap: 10px;
    margin: 36px 0 18px;
  }
  .section-title {
    font-size: 13px;
    color: #8899bb;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    font-weight: 800;
    margin: 0;
  }
  .sport-count-badge {
    font-size: 11px;
    font-weight: 700;
    color: #6366f1;
    background: rgba(99, 102, 241, 0.12);
    border: 1px solid rgba(99, 102, 241, 0.25);
    padding: 3px 10px;
    border-radius: 999px;
  }

  .sport-grid {
    display: grid;
    gap: 14px;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  }

  /* ── Footer ─────────────────────────────────────────────────── */
  .foot {
    margin-top: 48px;
    padding: 22px 0 8px;
    border-top: 1px solid rgba(255, 255, 255, 0.07);
    text-align: center;
  }
  .foot-brand {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    margin-bottom: 6px;
  }
  .foot-logo {
    font-size: 18px;
    filter: drop-shadow(0 0 6px #6366f1);
  }
  .foot-brand strong {
    font-size: 15px;
    font-weight: 900;
    color: #f1f5ff;
    letter-spacing: -0.01em;
  }
  .foot-version {
    font-size: 10px;
    font-weight: 700;
    color: #6366f1;
    background: rgba(99,102,241,0.12);
    padding: 2px 7px;
    border-radius: 999px;
    letter-spacing: 0.04em;
  }
  .foot-copy {
    color: #5a6e8a;
    font-size: 12px;
    font-weight: 500;
    margin-bottom: 12px;
  }
  .foot-sports {
    display: flex;
    justify-content: center;
    gap: 12px;
    font-size: 18px;
  }

  /* ── Responsive ─────────────────────────────────────────────── */
  @media (max-width: 380px) {
    .landing-inner { padding-left: 12px; padding-right: 12px; }
    .sport-grid { grid-template-columns: 1fr; }
  }
  @media (min-width: 768px) {
    .landing-inner { padding-bottom: max(40px, env(safe-area-inset-bottom)); }
  }
  @media (min-width: 1400px) {
    .landing-inner { width: min(100%, 1100px); }
  }
</style>
