<script lang="ts">
  import { onMount } from 'svelte';
  import { marketEvidence, type EvidenceRow } from '$lib/marketEvidence';
  import { queryConvex, convexErrorMessage } from '$lib/convexClient';
  const sports=['football','basketball','tennis','hockey','baseball','rally','instant-football','instant-basketball','vfootball','rugby','cricket','mma','volleyball'];
  let sport=$state('basketball'),from=$state(new Date(Date.now()-90*86400000).toISOString().slice(0,10)),to=$state(new Date().toISOString().slice(0,10)),mode=$state<'preferred'|'all'>('preferred');
  let data=$state<any>(null),busy=$state(false),error=$state(''),filter=$state('');
  let request=0;
  let evidenceRows=$state<EvidenceRow[]>([]),cursor=$state<string|undefined>(undefined),done=$state(false);
  const groups=$derived((data?.groups??[]).filter((g:any)=>g.title.toLowerCase().includes(filter.toLowerCase())));
  const pct=(v:number|null|undefined)=>v==null?'—':`${v.toFixed(1)}%`;
  async function load(append=false){
    if(append&&(!data||busy||done))return;
    const id=++request;busy=true;error='';
    const selection=append?{sport:data.sport,from:data.from,to:data.to,mode:data.mode,cursor}:{sport,from,to,mode};
    if(!append){data=null;evidenceRows=[];cursor=undefined;done=false;}
    try{const result=await queryConvex<any>('marketAnalytics:report',selection);if(id===request){evidenceRows=append?[...evidenceRows,...result.rows]:result.rows;cursor=result.cursor;done=result.isDone;data={...result,...marketEvidence(evidenceRows,selection.mode),rows:undefined};}}
    catch(reason){if(id===request)error=convexErrorMessage(reason,'Market evidence unavailable.');}finally{if(id===request)busy=false;}
  }
  onMount(()=>{void load();return()=>{request++;};});
  function download(){if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`market-evidence-${data.sport}-${data.from}-${data.to}.json`;a.click();URL.revokeObjectURL(url);}
</script>
<section class="market-workspace" aria-label="Sport and market performance evidence">
  <header><div><h3>Market intelligence by sport</h3><p>Which recorded directions won, at which confidence, and with how much evidence?</p></div><button onclick={download} disabled={!data||busy}>Export evidence</button></header>
  <nav aria-label="Sport categories">{#each sports as name}<button aria-pressed={sport===name} onclick={()=>{sport=name;void load();}}>{name.replaceAll('-',' ')}</button>{/each}</nav>
  <form onsubmit={(e)=>{e.preventDefault();void load();}}><label>From<input type="date" aria-label="Report start date" bind:value={from} required /></label><label>To<input type="date" aria-label="Report end date" bind:value={to} required /></label><label>Selection sample<select aria-label="Selection sample" bind:value={mode}><option value="preferred">Published preferred picks</option><option value="all">All retained candidates</option></select></label><button disabled={busy}>Apply filters</button></form>
  {#if busy}<p role="status">Loading archived outcomes…</p>{/if}{#if error}<p role="alert">{error}</p>{/if}
  {#if data}
    <p class="coverage">{data.sport} · {data.from} to {data.to} · {data.mode==='preferred'?'Published preferred picks':'All retained candidates'}{data.truncated?' · Partial sample: more archived fixtures available':' · All archived fixtures in this window loaded'}</p>
    {#if !data.automatedCoverage}<p class="notice">This sport has screener guidance, but no automated fixture archive. Historical win rates are unavailable.</p>{/if}
    <div class="metrics"><article class="metric-card"><small>Archived fixtures</small><strong>{data.fixtures}</strong><span>{data.fullArchive} with full market capture</span></article><article class="metric-card"><small>Legacy reports</small><strong>{data.legacyArchive}</strong><span>Limited selections; no stored preferred decision</span></article><article class="metric-card"><small>MET direction outcomes</small><strong>{data.met.wins} / {data.met.resolved}</strong><span>{pct(data.met.winRatePct)} observed · {data.met.pushes} pushes · {data.met.unavailable} unresolved</span></article></div>
    {#if !groups.length}<p class="notice">No settled market ranking is available for these filters. New full-market evidence accumulates from pre-kickoff publications; historical predictions are not reconstructed.</p>{/if}
    {#if groups.some((g:any)=>g.resolved)}<h4>Observed directions — ranked by lower confidence bound</h4><div class="bars">{#each groups.filter((g:any)=>g.resolved).slice(0,6) as g}<article class="bar-card"><div><b>{g.title}</b><span>{g.wins}/{g.resolved} · {pct(g.winRatePct)}</span></div><div class="track"><div style={`width:${g.winRatePct??0}%`}></div></div><small>95% interval {pct(g.lowerPct)}–{pct(g.upperPct)} · {g.fixtures} fixtures{g.resolved<30?' · Small sample':''}</small></article>{/each}</div>{/if}
    <label class="search">Find market / direction / confidence band<input type="search" bind:value={filter} placeholder="Example: h1, away, over, 80" /></label>
    <div class="scroll"><table><caption>Recorded market outcomes; wins / resolved selections excludes pushes and unavailable scores</caption><thead><tr><th>Market / period / direction / confidence</th><th>Fixtures</th><th>Wins / resolved</th><th>Rate · 95% interval</th><th>Push / partial / unavailable</th><th>Avg estimate / Brier</th><th>Gross ROI</th></tr></thead><tbody>{#each groups as g}<tr><th>{g.title}</th><td>{g.fixtures}</td><td>{g.wins} / {g.resolved}</td><td>{pct(g.winRatePct)}<small>{pct(g.lowerPct)}–{pct(g.upperPct)}</small></td><td>{g.pushes} / {g.partial} / {g.unavailable}</td><td>{pct(g.averageConfidencePct)} / {g.brierScore?.toFixed(3)??'—'}</td><td>{pct(g.grossRoiPct)}<small>{g.priced} priced observations</small></td></tr>{/each}</tbody></table></div>
    <h4>Highest-confidence plus-handicap cross-check</h4><p class="note">One highest-estimate full-game plus-handicap candidate per fixture. Covering a spread and winning outright are separate outcomes. Team-total rows use the highest-estimate retained line for that same team and direction, and show observations rather than a causal prediction.</p>
    <div class="scroll"><table><thead><tr><th>Condition / outcome</th><th>Fixtures</th><th>Wins / resolved</th><th>Observed rate · 95% interval</th><th>Unavailable / partial / pushes</th></tr></thead><tbody>{#each data.conditionals as g}<tr><th>{g.title}</th><td>{g.fixtures}</td><td>{g.wins}/{g.resolved}</td><td>{pct(g.winRatePct)}<small>{pct(g.lowerPct)}–{pct(g.upperPct)}</small></td><td>{g.unavailable} / {g.partial} / {g.pushes}</td></tr>{/each}</tbody></table></div>
    <button disabled={busy||done} onclick={()=>void load(true)}>{busy?'Loading…':done?'All archived fixtures loaded':'Load next 100 fixtures'}</button>
    <p class="note">{data.interpretation}</p><p class="note">No winning streak or future accuracy is promised. A market-implied MET lean has no independently calibrated confidence. {data.skippedLate} late captures excluded.</p>
  {/if}
</section>
<style>
  .market-workspace{min-width:0}header{display:flex;align-items:center;justify-content:space-between;gap:12px}h3{margin-bottom:4px}p{color:var(--c-muted);line-height:1.6}nav,form{display:flex;flex-wrap:wrap;align-items:end;gap:10px;margin:16px 0}button,input,select{border:1px solid var(--c-border);border-radius:10px;background:var(--c-bg);color:var(--c-text);font:inherit;padding:10px;min-width:0;max-width:100%}button[aria-pressed=true]{color:var(--brand);border-color:var(--brand)}button:disabled{opacity:.5}label{display:grid;gap:5px;font-size:.8rem}.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.metric-card,.bar-card{border:1px solid var(--c-border);border-radius:14px;background:var(--c-bg);padding:16px;box-shadow:var(--depth-card)}.metric-card strong{display:block;font-size:1.8rem;margin:8px 0}.metric-card span,small{display:block;color:var(--c-muted);font-size:.75rem;line-height:1.5}.bars{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.bar-card>div:first-child{display:flex;justify-content:space-between;gap:10px;font-size:.75rem;overflow-wrap:anywhere}.track{height:7px;background:var(--c-border);border-radius:9px;margin:10px 0}.track>div{height:100%;background:var(--brand);border-radius:9px}.search{margin:20px 0;max-width:420px}.scroll{overflow:auto;max-width:100%}table{border-collapse:collapse;width:100%;font-size:.8rem;text-align:left}caption{text-align:left;padding:12px 0;color:var(--c-muted)}th,td{padding:12px;border-bottom:1px solid var(--c-border);vertical-align:top}tbody th{min-width:200px;font-weight:500}.note,.coverage{font-size:.8rem}.notice{border:1px solid var(--c-border);padding:14px;border-radius:12px}[role=alert]{color:var(--c-error)}@media(max-width:700px){header{display:block}.metrics,.bars{grid-template-columns:1fr}form label{flex:1 1 140px}nav button{font-size:.75rem}}
</style>
