<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { Sparkles, ArrowRight } from '@lucide/svelte';

  let {
    sportId = null as string | null,
    accent = '#6366f1',
    label = 'AI Predictor'
  }: {
    sportId?: string | null;
    accent?: string;
    label?: string;
  } = $props();

  function go() {
    const path = sportId ? `/predictor/${sportId}` : '/predictor';
    void goto(path);
  }
</script>

<button
  class="ai-predictor-btn"
  style={`--accent:${accent}`}
  type="button"
  onclick={go}
  aria-label={`Open ${label}`}
>
  <span class="spark" aria-hidden="true">
    <Sparkles size={15} stroke-width={2.4} />
  </span>
  <span class="btn-label">{label}</span>
  <span class="arrow" aria-hidden="true">
    <ArrowRight size={15} stroke-width={2.2} />
  </span>
</button>

<style>
  .ai-predictor-btn {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 16px;
    border-radius: 14px;
    border: 1px solid color-mix(in srgb, var(--accent) 45%, transparent);
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--accent) 16%, transparent), transparent 60%),
      var(--c-glass-sm);
    color: var(--c-text);
    font-weight: 800;
    font-size: 13.5px;
    letter-spacing: -0.01em;
    cursor: pointer;
    transition:
      transform 80ms ease,
      box-shadow var(--t-base, 180ms ease),
      border-color var(--t-base, 180ms ease),
      background var(--t-base, 180ms ease);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
  }

  .ai-predictor-btn:hover {
    border-color: color-mix(in srgb, var(--accent) 75%, transparent);
    box-shadow: 0 0 18px color-mix(in srgb, var(--accent) 28%, transparent);
    transform: translateY(-1px);
  }

  .ai-predictor-btn:active { transform: scale(0.96); }

  .spark {
    display: inline-flex;
    color: var(--accent);
    filter: drop-shadow(0 0 6px color-mix(in srgb, var(--accent) 70%, transparent));
  }

  .btn-label { white-space: nowrap; }

  .arrow {
    display: inline-flex;
    color: color-mix(in srgb, var(--accent) 80%, var(--c-text));
    transition: transform var(--t-base, 180ms ease);
  }

  .ai-predictor-btn:hover .arrow { transform: translateX(3px); }
</style>
