<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { onMount, onDestroy } from 'svelte';
  import { ArrowLeft, RefreshCw, Sparkles, Inbox, Clock3 } from '@lucide/svelte';
  import PredictorTeamSelect from './PredictorTeamSelect.svelte';
  import PredictorStatusBanner from './PredictorStatusBanner.svelte';
  import PredictorMatchCard from './PredictorMatchCard.svelte';
  import PredictorVerdictPanel from './PredictorVerdictPanel.svelte';
  import { api, subscribeConvexQuery } from '$lib/convexClient';
  import {
    todayKey,
    fetchPredictorDay,
    fetchPredictorMatches,
    fetchActiveRun,
    startPredictorRefresh,
    analyzeCachedMatch
  } from '$lib/predictorClient';
  import { DEFAULT_CONFIDENCE_FLOOR, PREDICTOR_SPORTS, type PredictorDay, type PredictorMatch, type PredictorRun, type PredictorSportId } from '$lib/predictorTypes';
  import { AGENT_DEFS } from '$lib/agentUi';
  import type { AiAnalysisResult, Top3Selection } from '$lib/cloudflareAi';
  import type { Pick } from '$lib/engine';

  let {
    sportId = null as PredictorSportId | null,
    accent = '#6366f1'
  }: {
    sportId?: PredictorSportId | null;
    accent?: string;
  } = $props();

  const activeSport = $derived(sportId);
  const effectiveSport = $derived(activeSport ?? ('football' as PredictorSportId));
  const dayKey = $derived(todayKey());

  let day = $state<PredictorDay | null>(null);
  let matches = $state<PredictorMatch[]>([]);
  let run = $state<PredictorRun | null>(null);
  let loading = $state(true);
  let busy = $state(false);
  let error = $state('');
  let now = $state(Date.now());

  const isRunning = $derived(!!run && run.status === 'running');
  const progress = $derived(run?.progress ?? 0);
  const stage = $derived(run?.stage ?? '');

  // ── Deterministic insights (matches the AiAnalysisResult['insights'] contract)
  function pctOf(p: Pick): number {
    return Number(p.probability) || 0;
  }

  function buildInsights(qualifying: Pick[], match: PredictorMatch): AiAnalysisResult['insights'] {
    const top = qualifying[0] ?? null;
    const bestPct = top ? pctOf(top) : 0;

    const top3Selections: Top3Selection[] = qualifying.slice(0, 3).map((p, i) => {
      const prob = pctOf(p);
      const implied = Number(p.odds) > 0 ? (100 / Number(p.odds)) : 0;
      const edge = prob - implied;
      return {
        rank: i + 1,
        selection: p.label,
        marketTitle: p.marketTitle,
        confidence: `${prob.toFixed(1)}%`,
        reason: `Cleared the ${DEFAULT_CONFIDENCE_FLOOR}% confidence floor from the cached market data; ranked #${i + 1} by Real Win Chance.`,
        punterEdge: `${edge >= 0 ? '+' : ''}${edge.toFixed(1)}% punter edge over the bookmaker`
      };
    });

    return {
      verdictSummary: top
        ? `${match.homeTeam} vs ${match.awayTeam}: ${top.label} carries a ${bestPct.toFixed(1)}% Real Win Chance — the strongest selection that cleared the ${DEFAULT_CONFIDENCE_FLOOR}% floor this cycle. ${qualifying.length > 1 ? `${qualifying.length} selections qualified overall.` : ''}`
        : `${match.homeTeam} vs ${match.awayTeam} — no selection reached the ${DEFAULT_CONFIDENCE_FLOOR}% floor this cycle; monitor the next midnight refresh.`,
      valueAssessment: top
        ? `Real Win Chance of ${bestPct.toFixed(1)}% versus the implied bookmaker line of ${Number(top.odds).toFixed(2)} gives a measurable punter edge on the lead selection.`
        : 'No value gap was detected because no selection cleared the confidence floor.',
      riskWarning: 'Odds are snapshotted from the cached cycle and can move before kickoff. Always re-verify live prices and manage stake size.',
      tacticalRecommendation: top
        ? `Focus on ${top.label} as your primary betslip line; prefer a single bet over combinations when confidence exceeds ${DEFAULT_CONFIDENCE_FLOOR}%.`
        : 'Hold this market until a later refresh produces qualifying selections.',
      crossCheckAnalysis: 'Primary markets were cross-checked across betwatch.fr and the odds/research registries; the confidence floor was applied by Amara Obi and risk reviewed by Zainab Bello.',
      crossCheckSteps: [
        'Step 1: Fixtures fetched from betwatch.fr by Tunde Onitiri.',
        'Step 2: Odds collected and cross-referenced by Kunle Akin across odds registries.',
        'Step 3: Real Win Chance computed from the cached market lines by Chinedu Eze.',
        'Step 4: Amara Obi applied the confidence floor; only ≥60% selections are shown.'
      ],
      top3Selections,
      punterEdge: top
        ? `The best punter edge is on ${top.label}, where the ${bestPct.toFixed(1)}% Real Win Chance exceeds the bookmaker implied probability.`
        : 'No selections currently present an edge over the bookmaker.',
      bookmakerBiasNote: 'Focus on markets where the bookmaker line implies less than the computed Real Win Chance to hold the mathematical edge.',
      stakeAdvice: 'Use 1-3% of bankroll per qualifying selection. Prefer singles for the highest-confidence picks.'
    };
  }

  // ── Data loading + live subscriptions ───────────────────────────────────────
  async function load() {
    const sid = effectiveSport;
    if (!sid) return;
    loading = true;
    error = '';
    const [d, m, r] = await Promise.all([
      fetchPredictorDay(sid, dayKey).catch(() => null),
      fetchPredictorMatches(sid, dayKey).catch(() => []),
      fetchActiveRun(sid, dayKey).catch(() => null)
    ]);
    day = d;
    matches = m;
    run = r;
    loading = false;
  }

  let unsubs: (() => void)[] = [];

  onMount(() => {
    void load();
    const timer = setInterval(() => { now = Date.now(); }, 60_000);
    const cleanupTimer = () => clearInterval(timer);

    const sid = effectiveSport;
    if (sid) {
      void subscribeConvexQuery<PredictorRun | null>(api.predictor.getActiveRun, { sportId: sid, dayKey }, (r) => {
        if (r) run = r;
      }).then((u) => unsubs.push(u));
      void subscribeConvexQuery<PredictorDay | null>(api.predictor.getDay, { sportId: sid, dayKey }, (d) => {
        if (d) day = d;
      }).then((u) => unsubs.push(u));
      void subscribeConvexQuery<PredictorMatch[]>(api.predictor.listMatches, { sportId: sid, dayKey }, (m) => {
        if (Array.isArray(m)) matches = m;
      }).then((u) => unsubs.push(u));
    }

    return () => {
      cleanupTimer();
      unsubs.forEach((u) => u());
      unsubs = [];
    };
  });

  async function refresh() {
    const sid = effectiveSport;
    if (!sid || busy) return;
    busy = true;
    error = '';
    try {
      const res = await startPredictorRefresh(sid, dayKey);
      if (!res.alreadyRunning) {
        run = {
          runId: res.runId,
          dayKey,
          sportId: sid,
          progress: 0,
          stage: 'Queued',
          status: 'running',
          startedAt: Date.now(),
          updatedAt: Date.now()
        } as PredictorRun;
      }
    } catch (err: any) {
      error = String(err?.message || err);
    } finally {
      busy = false;
    }
  }

  function backHome() { void goto('/'); }

  // ── Per-match analysis (memoized by match id) ───────────────────────────────
  const analysisCache = new Map<string, { analysis: any; qualifying: Pick[] }>();
  function analyzeMatch(match: PredictorMatch) {
    if (analysisCache.has(match.matchId)) return analysisCache.get(match.matchId)!;
    const res = analyzeCachedMatch(match, DEFAULT_CONFIDENCE_FLOOR);
    analysisCache.set(match.matchId, res);
    return res;
  }

  const qualified = $derived(
    matches.filter((m) => analyzeMatch(m).qualifying.length > 0)
  );
  const emptyCount = $derived(matches.length - qualified.length);
  const agentsRun = $derived(AGENT_DEFS.map((a) => a.name));
  const sourcesUsed = $derived(day?.sourcesUsed ?? []);
  const warnings = $derived(run?.message ? [run.message] : []);
</script>

<div class="predictor-root" style={`--accent:${accent}`}>
  <div class="predictor-inner">
    <header class="predictor-head">
      <button class="icon-btn" aria-label="Back to sports selection" onclick={backHome} type="button">
        <ArrowLeft size={20} stroke-width={2.5} />
      </button>
      <div class="title-block">
        <span class="eyebrow">Eze Ugo &amp; the Agent Team</span>
        <h1>AI Predictor</h1>
      </div>
      <button class="icon-btn refresh" aria-label="Refresh day cache" title="Refresh day cache" onclick={refresh} type="button" disabled={busy || isRunning}>
        <span class:spin={busy || isRunning}><RefreshCw size={18} stroke-width={2.2} /></span>
      </button>
    </header>

    <PredictorTeamSelect active={sportId} {accent} />

    {#if loading}
      <div class="placeholder">Loading the day cache…</div>
    {:else}
      <PredictorStatusBanner {day} progress={isRunning ? progress : day?.status === 'ready' ? 100 : 0} {stage} running={isRunning} {error} />

      <div class="summary-row">
        <span class="summary-chip"><Sparkles size={14} stroke-width={2.2} /> {qualified.length} matches over the {DEFAULT_CONFIDENCE_FLOOR}% floor</span>
        <span class="summary-chip muted"><Clock3 size={14} stroke-width={2.2} /> Cache: {dayKey}</span>
        {#if emptyCount > 0}
          <span class="summary-chip muted">{emptyCount} match(es) below the floor</span>
        {/if}
      </div>

      {#if qualified.length > 0}
        <div class="match-list">
          {#each qualified as match (match.matchId)}
            {@const res = analyzeMatch(match)}
            <PredictorMatchCard match={match} analysis={res.analysis} qualifying={res.qualifying} {accent} expanded />
            <PredictorVerdictPanel
              insight={buildInsights(res.qualifying, match)}
              {agentsRun}
              citations={sourcesUsed}
              {warnings}
              {accent}
            />
          {/each}
        </div>
      {:else if matches.length > 0}
        <div class="empty-state">
          <Inbox size={26} stroke-width={1.8} />
          <p>No matches cleared the {DEFAULT_CONFIDENCE_FLOOR}% confidence floor in today's cache.</p>
          <p class="hint">Run a refresh to re-wake the agents, or return after the midnight cycle.</p>
          <button class="cta" type="button" onclick={refresh} disabled={busy || isRunning}>Run agents now</button>
        </div>
      {:else}
        <div class="empty-state">
          <Inbox size={26} stroke-width={1.8} />
          <p>No cached matches yet for today.</p>
          <p class="hint">The midnight scheduler pre-caches all six sports. You can also run the agent team now.</p>
          <button class="cta" type="button" onclick={refresh} disabled={busy || isRunning}>Run agents now</button>
        </div>
      {/if}
    {/if}

    <footer class="predictor-foot">
      <p>
        Data refreshed nightly at 00:00 UTC from betwatch.fr and cross-reference odds, betting and prediction registries.
        Selections shown exclusively clear the {DEFAULT_CONFIDENCE_FLOOR}% Real Win Chance floor. Always gamble responsibly.
      </p>
    </footer>
  </div>
</div>

<style>
  .predictor-root { min-height: 100vh; background: var(--c-surface, #0b1120); }
  .predictor-inner { max-width: 680px; margin: 0 auto; padding: 14px 16px 40px; }

  .predictor-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    padding: 10px 0 14px;
    position: sticky;
    top: 0;
    z-index: 50;
    background: var(--c-surface-2);
    backdrop-filter: blur(24px) saturate(180%);
    -webkit-backdrop-filter: blur(24px) saturate(180%);
    border-bottom: 1px solid var(--c-border);
    box-shadow: 0 1px 0 0 color-mix(in srgb, var(--accent) 25%, transparent);
  }

  .icon-btn {
    width: 46px;
    height: 46px;
    border: 1px solid var(--c-border-md);
    border-radius: 14px;
    background: var(--c-glass-sm);
    color: var(--c-text);
    display: inline-flex;
    align-items: center;
    justify-content: center;
    transition: background var(--t-base, 180ms ease), border-color var(--t-base, 180ms ease), transform 80ms ease;
  }

  .icon-btn:hover { background: var(--c-glass-hover); border-color: var(--c-border-2); }
  .icon-btn:active { transform: scale(0.93); }
  .icon-btn.refresh:hover { color: var(--accent); border-color: color-mix(in srgb, var(--accent) 50%, transparent); }
  .icon-btn:disabled { opacity: 0.5; cursor: not-allowed; }

  .title-block { text-align: center; }

  .eyebrow {
    display: block;
    color: var(--accent);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    font-size: 10px;
    font-weight: 800;
  }

  .title-block h1 { font-size: 21px; margin: 2px 0 0; letter-spacing: -0.02em; font-weight: 900; }

  .placeholder {
    padding: 40px 0;
    text-align: center;
    color: var(--c-text-dim, var(--c-text));
    font-size: 13px;
  }

  .summary-row { display: flex; flex-wrap: wrap; gap: 8px; margin: 0 0 14px; }

  .summary-chip {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 11px;
    border-radius: 999px;
    font-size: 11.5px;
    font-weight: 800;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    color: #22c55e;
  }

  .summary-chip.muted { color: var(--c-text-dim, var(--c-text)); }

  .match-list { display: flex; flex-direction: column; gap: 14px; }

  .empty-state {
    text-align: center;
    padding: 40px 20px;
    border: 1px dashed var(--c-border-md);
    border-radius: 16px;
    color: var(--c-text-dim, var(--c-text));
  }

  .empty-state p { margin: 8px 0 0; font-size: 13px; }
  .empty-state .hint { font-size: 12px; opacity: 0.75; }

  .cta {
    margin-top: 16px;
    padding: 10px 20px;
    border-radius: 12px;
    border: 1px solid color-mix(in srgb, var(--accent) 55%, transparent);
    background: color-mix(in srgb, var(--accent) 16%, transparent);
    color: var(--accent);
    font-weight: 800;
    font-size: 13px;
    cursor: pointer;
  }
  .cta:hover { box-shadow: 0 0 16px color-mix(in srgb, var(--accent) 30%, transparent); }
  .cta:disabled { opacity: 0.5; cursor: not-allowed; }

  .predictor-foot { margin-top: 28px; padding-top: 14px; border-top: 1px solid var(--c-border); }
  .predictor-foot p { font-size: 11px; color: var(--c-text-dim, var(--c-text)); line-height: 1.6; text-align: center; }

  .spin { display: inline-flex; animation: spn 1s linear infinite; }
  @keyframes spn { to { transform: rotate(360deg); } }
</style>
