<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import { ArrowLeft, ArrowDown, ArrowUp, RefreshCw, Inbox, Clock3, Check, ChevronLeft, ChevronDown, Wand2, Activity, Zap, Search, X } from '@lucide/svelte';
  import PredictorTeamSelect from './PredictorTeamSelect.svelte';
  import PredictorDateFilter, { type TimeBand } from './PredictorDateFilter.svelte';
  import PredictorStatusBanner from './PredictorStatusBanner.svelte';
  import PredictorMatchCard from './PredictorMatchCard.svelte';
  import PredictorVerdictPanel from './PredictorVerdictPanel.svelte';
  import PredictorSportIcon from './PredictorSportIcon.svelte';
  import { displayLeague } from '$lib/leagueCountries';
  import { api, subscribeConvexQuery } from '$lib/convexClient';
  import {
    todayKey,
    dayKeyFor,
    dayBounds,
    fetchPredictorDay,
    fetchPredictorMatchesInRange,
    fetchPredictorDaysInRange,
    fetchPredictorVerdict,
    fetchActiveRun,
    startPredictorRefresh,
    analyzeCachedMatch,
    bootstrapTodayAllSports,
    triggerScoreSync
  } from '$lib/predictorClient';
  import {
    DEFAULT_CONFIDENCE_FLOOR,
    type PredictorDay,
    type PredictorMatch,
    type PredictorRun,
    type PredictorSportId
  } from '$lib/predictorTypes';
  import { buildPredictorInsights } from '$lib/predictorInsights';
  import {
    filterByTimeBand,
    matchesQuery,
    searchPriorityCompare,
    sortMatches,
    groupByLeague,
    statusOfMatch,
    measureFilter,
    FILTER_BUDGET_MS,
    type GameTab,
    type SortOrder
  } from '$lib/predictorFiltering';
  import {
    PREDICTOR_MAX_SELECTIONS,
    clearSelection,
    loadSelection,
    saveSelection,
    toggleSelection
  } from '$lib/predictorSelections';
  import { AGENT_DEFS } from '$lib/agentUi';
  import type { Analysis, Pick } from '$lib/engine';

  let {
    sportId = null as PredictorSportId | null,
    accent = '#6366f1'
  }: {
    sportId?: PredictorSportId | null;
    accent?: string;
  } = $props();

  import { authState, canAccessPredictor } from '$lib/authStore.svelte';
  const predictorLocked = $derived(!canAccessPredictor(authState.user));

  import DailyPnlSummary from './DailyPnlSummary.svelte';
  import AccuracyMonitorPanel from './AccuracyMonitorPanel.svelte';
  import { generateGreatMindsDebate } from '$lib/greatMindsEngine';
  import type { GreatMindsDebateResult } from '$lib/predictorTypes';

  type Phase = 'select' | 'analyzing' | 'results';
  type SelectedAnalysis = {
    match: PredictorMatch;
    analysis: Analysis;
    qualifying: Pick[];
    insight?: Record<string, unknown> | null;
    greatMindsDebate?: GreatMindsDebateResult | null;
  };

  const activeSport = $derived(sportId);
  const effectiveSport = $derived(activeSport ?? ('football' as PredictorSportId));
  const today = $derived(todayKey());

  // Human-readable display name for each sport used in messages and toasts.
  const SPORT_DISPLAY_NAME: Record<PredictorSportId, string> = {
    football: 'Football', basketball: 'Basketball', tennis: 'Tennis',
    rally: 'Table Tennis', hockey: 'Ice Hockey', baseball: 'Baseball',
    americanfootball: 'American Football', rugby: 'Rugby', cricket: 'Cricket',
    mma: 'MMA', volleyball: 'Volleyball'
  };
  const sportDisplayName = $derived(SPORT_DISPLAY_NAME[effectiveSport] ?? effectiveSport);

  // Date window (defaults to today → +6 so the homepage shows up to 7 days where
  // cached data exists). Range is bounded to 7 days and clamped as the user picks.
  let fromDay = $state(dayKeyFor(0));
  let toDay = $state(dayKeyFor(6));
  let timeBand = $state<TimeBand>('all');

  let gameTab = $state<GameTab>('upcoming');

  // ── Search / sort / accordion state ──────────────────────────────────────────
  let searchQuery = $state('');
  let sortOrder = $state<SortOrder>('asc');
  // League accordion: expanded by default; keyed by `dayKey|league` so the same
  // league on different days collapses independently.
  let collapsedLeagues = $state<Record<string, boolean>>({});
  // Filter performance monitoring — surfaced as a badge when over budget.
  let filterMs = $state(0);
  let filterOverBudget = $state(false);

  let day = $state<PredictorDay | null>(null);
  let daysInRange = $state<PredictorDay[]>([]);
  let matches = $state<PredictorMatch[]>([]);
  let run = $state<PredictorRun | null>(null);
  let loading = $state(true);
  let busy = $state(false);
  let error = $state('');
  let now = $state(Date.now());
  let bootstrapping = $state(false);
  let bootstrapMsg = $state('');
  let bootstrapDone = $state(false);

  // ── Selection workflow state ─────────────────────────────────────────────────
  let phase = $state<Phase>('select');
  let selectedIds = $state<string[]>([]);
  let results = $state<SelectedAnalysis[]>([]);
  let agentProgress = $state(0);
  let agentStage = $state('');
  let selectNotice = $state('');
  let progressTimer: ReturnType<typeof setInterval> | null = null;
  let revealTimer: ReturnType<typeof setTimeout> | null = null;

  // ── Per-match cached verdict reveal (clicking a card shows only that match) ──
  let verdictCache = $state<Record<string, any | null>>({});
  let expandedMatches = $state<Record<string, boolean>>({});

  const insightFor = (m: PredictorMatch): ReturnType<typeof buildPredictorInsights> | null => {
    const hit = verdictCache[m.matchId];
    if (hit && typeof hit === 'object') return hit as ReturnType<typeof buildPredictorInsights>;
    // Fallback: build deterministic insight from cached engine picks so the card
    // always shows meaningful analysis when expanded (even before LLM verdict loads).
    const res = analyzeMatch(m);
    if (res.qualifying.length > 0) return buildPredictorInsights(m, res.qualifying);
    return null;
  };

  // Fetch and cache the stored LLM verdict for a specific match when its card expands.
  // Does NOT toggle expanded state — that is handled by the onClick caller.
  async function revealMatch(m: PredictorMatch) {
    if (verdictCache[m.matchId] !== undefined) return; // already fetched
    verdictCache = { ...verdictCache, [m.matchId]: null }; // mark as fetching
    try {
      const verdict = await fetchPredictorVerdict(m.dayKey || today, m.matchId);
      if (verdict?.aiReport && typeof verdict.aiReport === 'object') {
        verdictCache = { ...verdictCache, [m.matchId]: verdict.aiReport };
      }
    } catch (_) {
      /* leave null — card still shows deterministic picks/metrics */
    }
  }

  const isRunning = $derived(!!run && run.status === 'running');
  const refreshProgress = $derived(run?.progress ?? 0);
  const selectedSet = $derived(new Set(selectedIds));
  const isSelected = (id: string) => selectedSet.has(id);
  const qualifiedCount = $derived(results.filter((r) => r.qualifying.length > 0).length);
  const agentsRun = $derived(AGENT_DEFS.map((a) => a.name));
  const sourcesUsed = $derived(day?.sourcesUsed ?? []);
  const warnings = $derived(run?.message ? [run.message] : []);
  const runError = $derived(
    (run?.status === 'error' ? run.message || 'Agent refresh failed.' : '') ||
      (day?.status === 'error' ? day.message || 'Day cache refresh failed.' : '') ||
      ''
  );

  // Sport-scope + time-band + unified text search (team / player / match id).
  // Deriveds stay PURE — the pass duration is measured separately in an $effect
  // so any filter over the 500ms budget is surfaced without state writes here.
  const searchActive = $derived(searchQuery.trim().length > 0);

  const filteredMatches = $derived.by(() => {
    let list = matches;
    if (effectiveSport !== 'football') list = list.filter((m) => m.sportId !== 'football');
    list = filterByTimeBand(list, timeBand);
    if (searchActive) list = list.filter((m) => matchesQuery(m, searchQuery));
    return list;
  });

  // Game status classification — pure client-side, no extra API calls.
  // Upcoming: not started. In-play: started within the 3h window. Finished:
  // ended more than 3h ago.
  const statusOf = (m: PredictorMatch): GameTab => statusOfMatch(m, now);

  const tabFilteredMatches = $derived.by(() =>
    filteredMatches.filter((m) => statusOf(m) === gameTab)
  );

  const tabCounts = $derived.by(() => {
    const counts: Record<GameTab, number> = { upcoming: 0, inplay: 0, finished: 0 };
    for (const m of filteredMatches) counts[statusOf(m)] += 1;
    return counts;
  });

  // Sorted list for the active tab (default 'asc' = most recent & upcoming on
  // top). Grouped by league with accordion collapsibility per day.
  const sortedTabMatches = $derived.by(() => sortMatches(tabFilteredMatches, sortOrder, now));

  // Group the (time-band + tab-filtered + sorted) matches by their own cache day
  // so the page can show a 1–7 day window with each day's fixtures and status.
  const byDay = $derived.by(() => {
    const groups: Record<string, PredictorMatch[]> = {};
    for (const m of sortedTabMatches) {
      const key = m.dayKey || today;
      (groups[key] ??= []).push(m);
    }
    return groups;
  });

  // Search results: matching scheduled → finished → in-play, limited to the
  // existing valid fixture cards in the loaded window.
  const searchResults = $derived.by(() =>
    searchActive ? [...filteredMatches].sort((a, b) => searchPriorityCompare(a, b, now)) : []
  );

  const dayMatchCount = $derived.by(() => {
    const map: Record<string, number> = {};
    for (const m of matches) map[m.dayKey || today] = (map[m.dayKey || today] ?? 0) + 1;
    return map;
  });

  const isPast = (m: PredictorMatch) => m.startTime > 0 && m.startTime < now;
  const dayHasData = $derived((dayKey: string) => daysInRange.some((d) => d.dayKey === dayKey && (d.status === 'ready' || d.status === 'partial')));

  // Ordered list of dayKeys in the selected window (bounded to 7 days).
  const windowDays = $derived.by(() => {
    const keys: string[] = [];
    let cur = fromDay;
    // up to 7 iterations; stops early when the window is exceeded
    for (let i = 0; i < 7; i++) {
      const bounds = dayBounds(cur);
      keys.push(cur);
      if (cur >= toDay) break;
      const next = new Date(bounds.to + 1);
      cur = next.toISOString().slice(0, 10);
    }
    return keys;
  });

  // Time the filter+sort pass on every change — the deriveds above stay pure;
  // this $effect.pre observes them and surfaces the duration via the perf badge.
  // $effect.pre runs before the template consumes the deriveds, so the measured
  // time reflects the real pass rather than a warm cache read.
  $effect.pre(() => {
    const { metrics } = measureFilter(() => {
      void filteredMatches;
      void tabFilteredMatches;
      void sortedTabMatches;
      void byDay;
      void searchResults;
    });
    filterMs = Math.round(metrics.elapsedMs);
    filterOverBudget = metrics.overBudget;
  });

  // ── Deterministic per-match screening (memoized) ─────────────────────────────
  const analysisCache = new Map<string, { analysis: any; qualifying: Pick[] }>();
  function analyzeMatch(match: PredictorMatch) {
    if (analysisCache.has(match.matchId)) return analysisCache.get(match.matchId)!;
    const res = analyzeCachedMatch(match, DEFAULT_CONFIDENCE_FLOOR);
    analysisCache.set(match.matchId, res);
    return res;
  }

  // ── Selection controls ────────────────────────────────────────────────────────
  function toggleMatch(match: PredictorMatch) {
    const dk = match.dayKey || today;
    const res = toggleSelection(effectiveSport, dk, match.matchId);
    selectedIds = res.selection;
    selectNotice = res.capped
      ? `You can analyse up to ${PREDICTOR_MAX_SELECTIONS} matches at a time. Deselect one first to pick this one.`
      : '';
  }

  function selectAll() {
    const eligible = filteredMatches.filter((m) => !isPast(m));
    const ids = eligible.slice(0, PREDICTOR_MAX_SELECTIONS).map((m) => m.matchId);
    selectedIds = ids;
    // Persist selections per day so switching windows keeps them.
    const byDk: Record<string, string[]> = {};
    for (const m of eligible.slice(0, PREDICTOR_MAX_SELECTIONS)) {
      const dk = m.dayKey || today;
      (byDk[dk] ??= []).push(m.matchId);
    }
    for (const [dk, idsList] of Object.entries(byDk)) saveSelection(effectiveSport, dk, idsList);
    selectNotice =
      eligible.length > PREDICTOR_MAX_SELECTIONS
        ? `Analysing the first ${PREDICTOR_MAX_SELECTIONS} matches. Deselect one to make room for another.`
        : '';
  }

  function clearAll() {
    selectedIds = [];
    const dks = new Set(matches.map((m) => m.dayKey || today));
    for (const dk of dks) clearSelection(effectiveSport, dk);
    selectNotice = '';
  }

  // ── Analysis run (deterministic compute + agent progression) ─────────────────
  function stageForPct(p: number): string {
    let acc = 0;
    for (const a of AGENT_DEFS) {
      acc += a.weight;
      if (p <= acc) return a.stage;
    }
    return 'Compiling verdicts';
  }

  function clearProgress() {
    if (progressTimer) {
      clearInterval(progressTimer);
      progressTimer = null;
    }
    if (revealTimer) {
      clearTimeout(revealTimer);
      revealTimer = null;
    }
  }

  function animateAgents() {
    clearProgress();
    const start = Date.now();
    const DURATION = 3600;
    progressTimer = setInterval(() => {
      const pct = Math.min(100, Math.round(((Date.now() - start) / DURATION) * 100));
      agentProgress = pct;
      agentStage = stageForPct(pct);
      if (pct >= 100) {
        clearProgress();
        revealTimer = setTimeout(() => {
          phase = 'results';
        }, 220);
      }
    }, 120);
  }

  function analyzeSelected() {
    const sid = effectiveSport;
    if (!sid) return;
    const selected = matches.filter((m) => selectedIds.includes(m.matchId));
    if (selected.length === 0) return;
    results = selected.map((m) => {
      const res = analyzeMatch(m);
      const greatMindsDebate = generateGreatMindsDebate(m, res.analysis);
      return { match: m, analysis: res.analysis, qualifying: res.qualifying, insight: null, greatMindsDebate };
    });
    phase = 'analyzing';
    agentProgress = 0;
    agentStage = AGENT_DEFS[0]?.stage ?? 'Fixtures fetched';
    animateAgents();
    enrichWithLlmVerdicts(selected);
  }

  // Surface the stored LLM (Agnes/OpenRouter) verdict for each selected match
  // when the cache has one; otherwise the deterministic insights render.
  async function enrichWithLlmVerdicts(selected: PredictorMatch[]) {
    const entries = await Promise.all(
      selected.map(async (m) => {
        let llmInsight: Record<string, unknown> | null = null;
        try {
          const verdict = await fetchPredictorVerdict(m.dayKey || today, m.matchId);
          if (verdict?.aiReport && typeof verdict.aiReport === 'object') {
            llmInsight = verdict.aiReport;
          }
        } catch (_) {
          /* ignore — fall back to deterministic insights */
        }
        return { matchId: m.matchId, llmInsight };
      })
    );
    results = results.map((r) => {
      const hit = entries.find((e) => e.matchId === r.match.matchId);
      return hit?.llmInsight ? { ...r, insight: hit.llmInsight } : r;
    });
  }

  function backToSelection() {
    clearProgress();
    phase = 'select';
  }

  function dayKeyLabel(key: string): string {
    const [y, m, d] = key.split('-').map(Number);
    if (!y || !m || !d) return key;
    return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString(undefined, {
      weekday: 'short',
      month: 'short',
      day: 'numeric'
    });
  }

  async function refreshDay(dk: string) {
    const sid = effectiveSport;
    if (!sid || busy) return;
    busy = true;
    error = '';
    try {
      await startPredictorRefresh(sid, dk, true);
    } catch (err: any) {
      error = String(err?.message || err);
    } finally {
      busy = false;
    }
  }

  // ── Data loading + live subscriptions (reacts to sport/window changes) ───────
  let unsubs: (() => void)[] = [];
  let sportEpoch = 0;

  function disposeSubs() {
    unsubs.forEach((u) => u());
    unsubs = [];
  }

  async function loadRange(sid: PredictorSportId, fromDayArg: string, toDayArg: string, epoch: number) {
    loading = true;
    error = '';
    const [d, windowMatches, daysAll, r] = await Promise.all([
      fetchPredictorDay(sid, today).catch(() => null),
      fetchPredictorMatchesInRange(sid, fromDayArg, toDayArg).catch(() => []),
      fetchPredictorDaysInRange(sid, fromDayArg, toDayArg).catch(() => []),
      fetchActiveRun(sid, fromDayArg).catch(() => null)
    ]);
    if (epoch !== sportEpoch) return; // stale response after a switch
    day = d;
    matches = windowMatches;
    daysInRange = daysAll;
    run = r;
    // Prune stored selections that no longer appear in the window (per day).
    const kept: string[] = [];
    for (const m of windowMatches) {
      if (loadSelection(effectiveSport, m.dayKey || today).includes(m.matchId)) kept.push(m.matchId);
    }
    selectedIds = kept;
    loading = false;

    // Auto-bootstrap: if today has no cached data and nothing is running,
    // trigger a single-sport seed for the active sport. This ensures
    // first-time visitors see data without manually clicking 'Run agents'.
    if (epoch === sportEpoch && windowMatches.length === 0 && !r && !bootstrapping && !bootstrapDone) {
      void autoSeedCurrentSport(sid, fromDayArg);
    }
  }

  // Seed just the currently-viewed sport (lighter than bootstrapping all 11).
  async function autoSeedCurrentSport(sid: PredictorSportId, dayKey: string) {
    if (busy || bootstrapping) return;
    bootstrapping = true;
    const displayName = SPORT_DISPLAY_NAME[sid] ?? sid;
    bootstrapMsg = `Loading ${displayName} matches for today…`;
    try {
      await startPredictorRefresh(sid, dayKey, false);
      bootstrapMsg = `AI agents running for ${displayName}. Data will appear shortly.`;
      bootstrapDone = true;
    } catch (err: any) {
      // Silently swallow — user can still click 'Run agents now'
      console.warn('[autoSeed]', err?.message || err);
    } finally {
      bootstrapping = false;
    }
  }

  // Bootstrap all 11 sports — triggered from empty-state CTA.
  async function runBootstrapAll() {
    if (busy || bootstrapping) return;
    bootstrapping = true;
    bootstrapMsg = 'Starting AI agents for all 11 sports — this takes a few minutes…';
    try {
      const res = await bootstrapTodayAllSports();
      bootstrapMsg = res.message || 'AI agents dispatched for all sports. Data will appear shortly.';
      bootstrapDone = true;
    } catch (err: any) {
      error = String(err?.message || err);
      bootstrapMsg = '';
    } finally {
      bootstrapping = false;
    }
  }

  function subscribe(sid: PredictorSportId, fromDayArg: string, toDayArg: string, epoch: number) {
    void subscribeConvexQuery<PredictorRun | null>(api.predictor.getActiveRun, { sportId: sid, dayKey: fromDayArg }, (r) => {
      if (r && epoch === sportEpoch) run = r;
    }).then((u) => {
      if (epoch === sportEpoch) unsubs.push(u);
      else u();
    });
    void subscribeConvexQuery<PredictorDay | null>(api.predictor.getDay, { sportId: sid, dayKey: today }, (d) => {
      if (d && epoch === sportEpoch) day = d;
    }).then((u) => {
      if (epoch === sportEpoch) unsubs.push(u);
      else u();
    });
    void subscribeConvexQuery<PredictorDay[]>(api.predictor.listDaysInRange, { sportId: sid, fromDay: fromDayArg, toDay: toDayArg }, (d) => {
      if (Array.isArray(d) && epoch === sportEpoch) daysInRange = d;
    }).then((u) => {
      if (epoch === sportEpoch) unsubs.push(u);
      else u();
    });
    void subscribeConvexQuery<PredictorMatch[]>(api.predictor.listMatchesInRange, { sportId: sid, fromDay: fromDayArg, toDay: toDayArg }, (m) => {
      if (Array.isArray(m) && epoch === sportEpoch) matches = m;
    }).then((u) => {
      if (epoch === sportEpoch) unsubs.push(u);
      else u();
    });
  }

$effect(() => {
    const sid = effectiveSport;
    if (!sid) return;
    // Slip the window (clamp to 7 days) so a reopened picker stays fresh.
    if (toDay < fromDay) toDay = fromDay;
    const fj = fromDay;
    const tj = toDay;
    sportEpoch += 1;
    const epoch = sportEpoch;
    clearProgress();
    phase = 'select';
    gameTab = 'upcoming';
    timeBand = 'all';
    searchQuery = '';
    sortOrder = 'asc';
    collapsedLeagues = {};
    results = [];
    selectNotice = '';
    disposeSubs();
    void loadRange(sid, fj, tj, epoch);
    subscribe(sid, fj, tj, epoch);
  });

  let scoreSyncing = $state(false);
  const SCORE_SYNC_THROTTLE_MS = 5 * 60 * 1000;
  const SCORE_SYNC_KEY = 'scoreSyncLastAt_v1';

  // Ask the server to fetch final scorelines for today + the past 7 days so the
  // Finished tab shows scorelines/verdicts immediately instead of waiting for
  // the next 5-minute live-scores cron tick. The reactive listMatchesInRange
  // subscription pushes the updated rows into the UI as soon as they land.
  // `force` skips the 5-minute session throttle (used by the manual button).
  async function syncScoresNow(force = false) {
    if (scoreSyncing) return;
    if (!force) {
      try {
        const last = Number(sessionStorage.getItem(SCORE_SYNC_KEY) || 0);
        if (Date.now() - last < SCORE_SYNC_THROTTLE_MS) return;
        sessionStorage.setItem(SCORE_SYNC_KEY, String(Date.now()));
      } catch (_) {
        /* storage unavailable — proceed */
      }
    }
    scoreSyncing = true;
    try {
      await triggerScoreSync({ includePastDays: true });
    } catch (_) {
      /* non-fatal — cron will retry */
    } finally {
      scoreSyncing = false;
    }
  }

  onMount(() => {
    void syncScoresNow();
    const timer = setInterval(() => {
      now = Date.now();
    }, 60_000);
    return () => {
      clearInterval(timer);
      disposeSubs();
      clearProgress();
    };
  });

  async function refresh() {
    const sid = effectiveSport;
    if (!sid || busy) return;
    busy = true;
    error = '';
    try {
      const res = await startPredictorRefresh(sid, fromDay, true);
      if (!res.alreadyRunning) {
        run = {
          runId: res.runId,
          dayKey: fromDay,
          sportId: sid,
          progress: 0,
          stage: 'Queued',
          status: 'running',
          startedAt: Date.now(),
          updatedAt: Date.now()
        } as PredictorRun;
      }
    } catch (err: any) {
      error = String(err?.message || err);
    } finally {
      busy = false;
    }
  }

  function backHome() {
    void goto('/');
  }
</script>

<div class="predictor-root" style={`--accent:${accent}`}>
  {#if predictorLocked}
    <div class="paywall">
      <div class="paywall-card">
        <span class="pw-badge">Master Pass</span>
        <h2 class="pw-title">The AI Predictor is a Master Pass feature</h2>
        <p class="pw-copy">
          Eze Ugo &amp; the nine-agent team surface only matches clearing the {DEFAULT_CONFIDENCE_FLOOR}% Real
          Win Chance floor across 11 sports. Upgrade your monthly pass to unlock it.
        </p>
        <div class="pw-points">
          <span class="pw-point"><Check size={14} stroke-width={2.6} /> 60%+ Real Win Chance picks</span>
          <span class="pw-point"><Check size={14} stroke-width={2.6} /> 9 specialist AI agents</span>
          <span class="pw-point"><Check size={14} stroke-width={2.6} /> All 11 sports, refreshed nightly</span>
        </div>
        {#if !authState.isAuthenticated}
          <button class="cta pw-cta" type="button" onclick={() => void goto('/auth?mode=signup&redirect=checkout')}>
            <Wand2 size={15} stroke-width={2.4} />
            Sign in to upgrade
          </button>
          <p class="pw-hint">Already a Master member? Sign in with the account that purchased the pass.</p>
        {:else}
          <button class="cta pw-cta" type="button" onclick={() => void goto('/checkout?tier=master')}>
            <Wand2 size={15} stroke-width={2.4} />
            Upgrade to Master Pass — ₦10,000 / month
          </button>
        {/if}
      </div>
    </div>
  {:else}
  <div class="predictor-inner">
    <header class="predictor-head">
      <button class="icon-btn" aria-label="Back to sports selection" onclick={backHome} type="button">
        <ArrowLeft size={20} stroke-width={2.5} />
      </button>
      <div class="title-block">
        <span class="eyebrow">Eze Ugo &amp; the Agent Team</span>
        <h1>AI Predictor</h1>
        <div class="title-sport-ic" style={`color:${accent}`}>
          <PredictorSportIcon sport={effectiveSport} size={20} strokeWidth={2} />
        </div>
      </div>
      <button
        class="icon-btn refresh"
        aria-label="Refresh day cache"
        title="Refresh day cache"
        onclick={refresh}
        type="button"
        disabled={busy || isRunning || phase === 'analyzing'}
      >
        <span class:spin={busy || isRunning}><RefreshCw size={18} stroke-width={2.2} /></span>
      </button>
    </header>

    <PredictorTeamSelect active={sportId} {accent} />

    {#if loading}
      <div class="placeholder">
        <span class="ph-icon"><Activity size={22} stroke-width={1.8} /></span>
        Loading scheduled matches for the selected window…
      </div>
    {:else}
      <PredictorDateFilter bind:fromDay bind:toDay bind:timeBand />

      <div class="filter-toolbar">
        <div class="search-box">
          <Search size={15} stroke-width={2.2} class="search-ic" />
          <input
            type="search"
            placeholder="Search team, player or match id…"
            aria-label="Search matches"
            bind:value={searchQuery}
          />
          {#if searchActive}
            <button class="search-clear" type="button" aria-label="Clear search" onclick={() => (searchQuery = '')}>
              <X size={13} stroke-width={2.4} />
            </button>
          {/if}
          {#if filterOverBudget}
            <span class="perf-badge warn" title="Filter took longer than 500ms">⚠ {filterMs.toFixed(0)}ms</span>
          {:else if filterMs > 0}
            <span class="perf-badge" title="Filter pass duration">{filterMs.toFixed(0)}ms</span>
          {/if}
        </div>

        <div class="sort-row" role="group" aria-label="Sort matches">
          <span class="sort-label">Sort</span>
          <button
            class="sort-btn {sortOrder === 'asc' ? 'is-active' : ''}"
            type="button"
            aria-pressed={sortOrder === 'asc'}
            onclick={() => (sortOrder = 'asc')}
          >
            <ArrowUp size={13} stroke-width={2.4} />
            Soonest
          </button>
          <button
            class="sort-btn {sortOrder === 'desc' ? 'is-active' : ''}"
            type="button"
            aria-pressed={sortOrder === 'desc'}
            onclick={() => (sortOrder = 'desc')}
          >
            <ArrowDown size={13} stroke-width={2.4} />
            Latest
          </button>
        </div>
      </div>

      <div class="tabs-row">
      <div class="game-tabs" role="tablist" aria-label="Filter matches by status">
        <button
          class="game-tab {gameTab === 'upcoming' ? 'is-active' : ''}"
          type="button"
          role="tab"
          aria-selected={gameTab === 'upcoming'}
          onclick={() => (gameTab = 'upcoming')}
        >
          Upcoming
          <span class="tab-count">{tabCounts.upcoming}</span>
        </button>
        <button
          class="game-tab {gameTab === 'inplay' ? 'is-active' : ''}"
          type="button"
          role="tab"
          aria-selected={gameTab === 'inplay'}
          onclick={() => (gameTab = 'inplay')}
        >
          {#if tabCounts.inplay > 0}
            <span class="live-dot" aria-hidden="true"></span>
          {/if}
          In-Play
          <span class="tab-count">{tabCounts.inplay}</span>
        </button>
        <button
          class="game-tab {gameTab === 'finished' ? 'is-active' : ''}"
          type="button"
          role="tab"
          aria-selected={gameTab === 'finished'}
          onclick={() => (gameTab = 'finished')}
        >
          Finished
          <span class="tab-count">{tabCounts.finished}</span>
        </button>
      </div>

      <button
        class="scores-sync-btn"
        type="button"
        onclick={() => syncScoresNow(true)}
        disabled={scoreSyncing}
        title="Fetch final scorelines for finished matches now"
        aria-label="Sync live scores"
      >
        <span class:spin={scoreSyncing}><RefreshCw size={13} stroke-width={2.4} /></span>
        {scoreSyncing ? 'Syncing…' : 'Sync scores'}
      </button>
      </div>

      <PredictorStatusBanner
        {day}
        progress={phase === 'analyzing' ? agentProgress : isRunning ? refreshProgress : day?.status === 'ready' ? 100 : 0}
        stage={phase === 'analyzing' ? agentStage : ''}
        running={phase === 'analyzing' || isRunning}
        error={error || runError}
      />

      {#if phase === 'select'}
        <div class="selection-bar">
          <div class="sel-row">
            <span class="summary-chip">
              <Check size={14} stroke-width={2.6} />
              {selectedIds.length} of {PREDICTOR_MAX_SELECTIONS} selected
            </span>
            {#if matches.length > 0}
              <span class="summary-chip muted">
                {matches.length} scheduled {effectiveSport === 'mma' ? 'bouts' : 'matches'}
              </span>
            {/if}
            <span class="sel-actions">
              {#if matches.length > 0}
                <button class="link-btn" type="button" onclick={selectAll}>
                  Select {Math.min(PREDICTOR_MAX_SELECTIONS, matches.length)}
                </button>
              {/if}
              <button class="link-btn" type="button" onclick={clearAll} disabled={selectedIds.length === 0}>Clear</button>
            </span>
          </div>

          {#if selectNotice}
            <p class="notice" role="status">{selectNotice}</p>
          {/if}

          <button class="cta analyze" type="button" onclick={analyzeSelected} disabled={selectedIds.length === 0}>
            <Wand2 size={15} stroke-width={2.4} />
            Analyse selected {selectedIds.length > 0 ? `(${selectedIds.length})` : ''}
          </button>
        </div>

        {#if searchActive}
          <section class="day-group search-group">
            <h2 class="day-title">
              <span class="day-name">Search results</span>
              <span class="day-badge">{searchResults.length} matching</span>
            </h2>

            {#if searchResults.length > 0}
              {#each Object.entries(groupByLeague(searchResults, displayLeague)) as [league, group]}
                {@const lgKey = 'search:' + league}
                {@const collapsed = collapsedLeagues[lgKey] ?? false}
                <div class="league-group">
                  <button class="league-accordion" type="button" aria-expanded={!collapsed} onclick={() => (collapsedLeagues = { ...collapsedLeagues, [lgKey]: !collapsed })}>
                    <span class="league-name">{displayLeague(league)}</span>
                    <span class="league-count">{group.length}</span>
                    <ChevronDown size={15} stroke-width={2.4} class="accordion-caret {collapsed ? 'is-collapsed' : ''}" />
                  </button>
                  {#if !collapsed}
                    <div class="match-list">
                      {#each group as match (match.matchId)}
                        {@const res = analyzeMatch(match)}
                        <PredictorMatchCard
                          match={match}
                          analysis={res.analysis}
                          qualifying={res.qualifying}
                          insight={insightFor(match)}
                          expanded={expandedMatches[match.matchId] ?? false}
                          {accent}
                          selectable
                          selected={isSelected(match.matchId)}
                          inPlay={statusOf(match) === 'inplay'}
                          finished={statusOf(match) === 'finished'}
                          finalScore={match.finalScore ?? match.oddsSnapshot?.finalScore}
                          onSelect={() => toggleMatch(match)}
                          onClick={() => {
                            const nowOpen = !(expandedMatches[match.matchId] ?? false);
                            expandedMatches = { ...expandedMatches, [match.matchId]: nowOpen };
                            if (nowOpen) void revealMatch(match);
                          }}
                        />
                      {/each}
                    </div>
                  {/if}
                </div>
              {/each}
            {:else}
              <div class="day-empty">
                <Search size={18} stroke-width={1.8} />
                <span>No matches match “{searchQuery.trim()}”.</span>
              </div>
            {/if}
          </section>
        {/if}

        {#if windowDays.length > 0}
          {#each windowDays as dk (dk)}
            {@const dayMatches = byDay[dk] ?? []}
            <section class="day-group">
              <h2 class="day-title">
                <span class="day-name">{dk === today ? 'Today' : dayKeyLabel(dk)}</span>
                <span class="day-key">{dk}</span>
                {#if dayHasData(dk) && (dayMatches.length === 0 || timeBand !== 'all')}
                  <span class="day-badge has">{dayMatchCount[dk] ?? 0} cached</span>
                {/if}
                {#if dayMatches.length > 0}
                  <span class="day-badge">{dayMatches.length} shown</span>
                {/if}
              </h2>

              {#if dayMatches.length > 0}
                {#each Object.entries(groupByLeague(dayMatches, displayLeague)) as [league, group] (dk + ':' + league)}
                  {@const lgKey = dk + ':' + league}
                  {@const collapsed = collapsedLeagues[lgKey] ?? false}
                  <div class="league-group">
                    <button
                      class="league-accordion"
                      type="button"
                      aria-expanded={!collapsed}
                      onclick={() => (collapsedLeagues = { ...collapsedLeagues, [lgKey]: !collapsed })}
                    >
                      <span class="league-name">{displayLeague(league)}</span>
                      <span class="league-count">{group.length}</span>
                      <ChevronDown size={15} stroke-width={2.4} class="accordion-caret {collapsed ? 'is-collapsed' : ''}" />
                    </button>
                    {#if !collapsed}
                      <div class="match-list">
                        {#each group as match (match.matchId)}
                          {@const res = analyzeMatch(match)}
                          <PredictorMatchCard
                            match={match}
                            analysis={res.analysis}
                            qualifying={res.qualifying}
                            insight={insightFor(match)}
                            expanded={expandedMatches[match.matchId] ?? false}
                            {accent}
                            selectable
                            selected={isSelected(match.matchId)}
                            inPlay={statusOf(match) === 'inplay'}
                            finished={statusOf(match) === 'finished'}
                            finalScore={match.finalScore ?? match.oddsSnapshot?.finalScore}
                            onSelect={() => toggleMatch(match)}
                            onClick={() => {
                              const nowOpen = !(expandedMatches[match.matchId] ?? false);
                              expandedMatches = { ...expandedMatches, [match.matchId]: nowOpen };
                              if (nowOpen) void revealMatch(match);
                            }}
                          />
                        {/each}
                      </div>
                    {/if}
                  </div>
                {/each}
              {:else}
                <div class="day-empty">
                  <PredictorSportIcon sport={effectiveSport} size={22} strokeWidth={1.6} />
                  <span>
                    {timeBand !== 'all' && gameTab === 'upcoming'
                      ? 'No matches in this time band.'
                      : gameTab !== 'upcoming'
                        ? `No ${gameTab === 'inplay' ? 'in-play' : 'finished'} matches in this window.`
                        : dayHasData(dk)
                          ? 'No matches for this day in the cache.'
                          : 'No data cached for this day yet.'}
                  </span>
                  {#if !dayHasData(dk)}
                    <button class="day-refresh" type="button" onclick={() => refreshDay(dk)} disabled={busy || isRunning}>
                      Run agents
                    </button>
                  {/if}
                </div>
              {/if}
            </section>
          {/each}
        {:else if !searchActive}
          <div class="empty-state">
            <div class="empty-ic">
              <PredictorSportIcon sport={effectiveSport} size={34} strokeWidth={1.6} />
            </div>
            <p>No scheduled matches cached in the {fromDay}…{toDay} window.</p>
            {#if bootstrapMsg}
              <p class="bootstrap-msg" role="status">{bootstrapMsg}</p>
            {:else}
              <p class="hint">The agent team runs automatically three times daily. You can also load all sports right now.</p>
            {/if}
            <div class="empty-actions">
              <button class="cta" type="button" onclick={runBootstrapAll} disabled={busy || isRunning || bootstrapping}>
                <Zap size={15} stroke-width={2.4} />
                {bootstrapping ? 'Agents running…' : 'Load all sports now'}
              </button>
              <button class="cta secondary" type="button" onclick={refresh} disabled={busy || isRunning || bootstrapping}>Run {effectiveSport} only</button>
            </div>
          </div>
        {/if}
      {:else if phase === 'analyzing'}
        <div class="working">
          <p class="working-title">
            Eze Ugo &amp; team are preparing verdicts for your {results.length} selected match{results.length === 1 ? '' : 'es'}…
          </p>
          <p class="working-sub">
            Screening runs deterministically over the cached scopes — no network round-trip required.
          </p>
        </div>
      {:else}
        <div class="results-bar">
          <button
            class="icon-btn"
            aria-label="Back to match selection"
            title="Change selection"
            onclick={backToSelection}
            type="button"
          >
            <ChevronLeft size={20} stroke-width={2.5} />
          </button>
          <div class="results-meta">
            <span class="summary-chip">
              <Check size={14} stroke-width={2.6} />
              {results.length} match{results.length === 1 ? '' : 'es'} analysed
            </span>
            <span class="summary-chip">{qualifiedCount} over the {DEFAULT_CONFIDENCE_FLOOR}% floor</span>
            <span class="summary-chip muted"><Clock3 size={14} stroke-width={2.2} /> Cache: {fromDay}…{toDay}</span>
          </div>
          <button class="link-btn" type="button" onclick={backToSelection}>Change selection</button>
        </div>

        {#if results.length > 0}
          <div class="match-list">
            {#each results as r (r.match.matchId)}
              <PredictorMatchCard
                match={r.match}
                analysis={r.analysis}
                qualifying={r.qualifying}
                {accent}
                expanded
                inPlay={statusOf(r.match) === 'inplay'}
                finished={statusOf(r.match) === 'finished'}
                finalScore={r.match.finalScore ?? r.match.oddsSnapshot?.finalScore}
              />
              <PredictorVerdictPanel
                insight={r.insight ? (r.insight as import('$lib/cloudflareAi').AiAnalysisResult['insights']) : buildPredictorInsights(r.match, r.qualifying)}
                greatMindsDebate={r.greatMindsDebate}
                picks={r.qualifying}
                metrics={r.analysis?.metrics}
                {agentsRun}
                citations={sourcesUsed}
                {warnings}
                {accent}
                finalScore={r.match.finalScore ?? r.match.oddsSnapshot?.finalScore}
              />
            {/each}
          </div>
        {:else}
          <div class="empty-state">
            <div class="empty-ic"><Inbox size={30} stroke-width={1.8} /></div>
            <p>No matches were analysed.</p>
            <p class="hint">Go back and select at least one scheduled match to generate a verdict.</p>
            <button class="cta" type="button" onclick={backToSelection}>Select matches</button>
          </div>
        {/if}
      {/if}
    {/if}

    <DailyPnlSummary matches={matches} />

    <AccuracyMonitorPanel matches={matches} />

<footer class="predictor-foot">
      <p>
        Data refreshed 3× daily at 1:00 AM WAT, 7:00 AM WAT & 1:00 PM WAT from betwatch.fr and cross-reference odds, betting and prediction registries.
        Select any scheduled match to run the agent team, which surfaces only selections that clear the
        {DEFAULT_CONFIDENCE_FLOOR}% Real Win Chance floor. All match times shown in West Africa Time (WAT). Always gamble responsibly.
      </p>
</footer>
  </div>
  {/if}
</div>

<style>
  .predictor-root { min-height: 100vh; background: var(--c-surface, #0b1120); }
  .predictor-inner { max-width: 680px; margin: 0 auto; padding: 14px 16px 40px; }

  /* Paywall */
  .paywall {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px 16px;
  }
  .paywall-card {
    max-width: 460px;
    width: 100%;
    background: var(--c-surface-2, #16213a);
    border: 1px solid color-mix(in srgb, var(--accent) 40%, transparent);
    border-radius: 20px;
    padding: 32px 28px;
    text-align: center;
    box-shadow: 0 20px 60px -12px color-mix(in srgb, var(--accent) 25%, transparent);
  }
  .pw-badge {
    display: inline-block;
    font-size: 10px;
    font-weight: 900;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--accent);
    background: color-mix(in srgb, var(--accent) 14%, transparent);
    border: 1px solid color-mix(in srgb, var(--accent) 35%, transparent);
    padding: 4px 12px;
    border-radius: 999px;
    margin-bottom: 14px;
  }
  .pw-title { font-size: 22px; font-weight: 900; color: var(--c-text, #f1f5ff); margin: 0 0 10px; }
  .pw-copy { font-size: 14px; line-height: 1.6; color: var(--c-text-2, #cbd5e1); margin: 0 0 18px; }
  .pw-points { display: flex; flex-direction: column; gap: 8px; align-items: flex-start; margin: 0 0 22px; padding: 0; }
  .pw-point { display: inline-flex; align-items: center; gap: 8px; font-size: 13px; font-weight: 700; color: var(--c-text, #f1f5ff); }
  .pw-point :global(svg) { color: var(--accent); flex-shrink: 0; }
  .pw-cta { width: 100%; }
  .pw-hint { font-size: 11.5px; color: var(--c-muted, #94a3b8); margin: 12px 0 0; }

  .predictor-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    padding: 10px 0 14px;
    position: sticky;
    top: 0;
    z-index: 50;
    background: var(--c-surface-2);
    backdrop-filter: blur(24px) saturate(180%);
    -webkit-backdrop-filter: blur(24px) saturate(180%);
    border-bottom: 1px solid var(--c-border);
    box-shadow: 0 1px 0 0 color-mix(in srgb, var(--accent) 25%, transparent);
  }

  .icon-btn {
    width: 46px;
    height: 46px;
    border: 1px solid var(--c-border-md);
    border-radius: 14px;
    background: var(--c-glass-sm);
    color: var(--c-text);
    display: inline-flex;
    align-items: center;
    justify-content: center;
    transition: background var(--t-base, 180ms ease), border-color var(--t-base, 180ms ease), transform 80ms ease;
  }

  .icon-btn:hover { background: var(--c-glass-hover); border-color: var(--c-border-2); }
  .icon-btn:active { transform: scale(0.93); }
  .icon-btn.refresh:hover { color: var(--accent); border-color: color-mix(in srgb, var(--accent) 50%, transparent); }
  .icon-btn:disabled { opacity: 0.5; cursor: not-allowed; }

  .title-block { text-align: center; }

  .eyebrow {
    display: block;
    color: var(--accent);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    font-size: 10px;
    font-weight: 800;
  }

  .title-block h1 { font-size: 21px; margin: 2px 0 0; letter-spacing: -0.02em; font-weight: 900; }

  .title-sport-ic {
    display: inline-flex;
    margin-top: 3px;
    filter: drop-shadow(0 0 8px color-mix(in srgb, var(--accent) 60%, transparent));
  }

  .placeholder {
    padding: 40px 0;
    text-align: center;
    color: var(--c-text-dim, var(--c-text));
    font-size: 13px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
  }

  .ph-icon {
    display: inline-flex;
    color: var(--accent);
    animation: ph-pulse 1.8s ease-in-out infinite;
  }

  @keyframes ph-pulse {
    0%, 100% { opacity: 0.45; transform: scale(1); }
    50% { opacity: 1; transform: scale(1.12); }
  }

  /* ── Selection bar ── */
  .selection-bar {
    border: 1px solid var(--c-border-md);
    border-radius: 16px;
    padding: 12px 14px;
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--accent) 10%, transparent), transparent 55%),
      var(--c-surface-2);
    margin-bottom: 16px;
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .sel-row {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 8px;
  }

  .summary-chip {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 11px;
    border-radius: 999px;
    font-size: 11.5px;
    font-weight: 800;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    color: #22c55e;
  }

  .summary-chip.muted { color: var(--c-text-dim, var(--c-text)); }

  .sel-actions { margin-left: auto; display: inline-flex; gap: 4px; }

  .link-btn {
    border: none;
    background: transparent;
    color: var(--accent);
    font-size: 12px;
    font-weight: 800;
    padding: 4px 8px;
    border-radius: 8px;
    cursor: pointer;
    transition: background var(--t-base, 180ms ease);
  }

  .link-btn:hover { background: var(--c-glass-sm); }
  .link-btn:disabled { opacity: 0.4; cursor: not-allowed; }

  .notice {
    margin: 0;
    font-size: 12px;
    color: #f59e0b;
    background: color-mix(in srgb, #f59e0b 8%, transparent);
    border: 1px solid color-mix(in srgb, #f59e0b 28%, transparent);
    border-radius: 10px;
    padding: 8px 10px;
  }

  .cta {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    width: 100%;
    padding: 13px 20px;
    border-radius: 14px;
    border: 1px solid color-mix(in srgb, var(--accent) 60%, transparent);
    background: color-mix(in srgb, var(--accent) 20%, transparent);
    color: var(--accent);
    font-weight: 800;
    font-size: 14px;
    cursor: pointer;
    transition: box-shadow var(--t-base, 180ms ease), transform 80ms ease;
  }
  .cta:hover { box-shadow: 0 0 20px color-mix(in srgb, var(--accent) 32%, transparent); }
  .cta:active { transform: scale(0.985); }
  .cta:disabled { opacity: 0.5; cursor: not-allowed; box-shadow: none; }

  /* ── League groups ── */
  .league-group { margin-bottom: 18px; }

  /* ── Day groups (date-window view) ── */
  .day-group { margin-bottom: 26px; }

  .day-title {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 8px;
    margin: 0 0 10px;
    padding-bottom: 8px;
    border-bottom: 1px solid var(--c-border);
  }

  .day-name {
    font-size: 14px;
    font-weight: 900;
    letter-spacing: -0.01em;
    color: var(--c-text);
  }

  .day-key {
    font-size: 11px;
    font-weight: 700;
    color: var(--c-text-dim, var(--c-text));
    font-variant-numeric: tabular-nums;
  }

  .day-badge {
    font-size: 10.5px;
    font-weight: 800;
    padding: 2px 8px;
    border-radius: 999px;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    color: var(--c-text-dim, var(--c-text));
  }

  .day-badge.has { color: var(--accent); border-color: color-mix(in srgb, var(--accent) 40%, transparent); }

  .day-empty {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 12px 14px;
    border-radius: 12px;
    border: 1px dashed var(--c-border-md);
    background: var(--c-glass-sm);
    color: var(--c-text-dim, var(--c-text));
    font-size: 12.5px;
  }

  .day-empty span { flex: 1; min-width: 0; }

  .day-refresh {
    flex-shrink: 0;
    border: 1px solid color-mix(in srgb, var(--accent) 50%, transparent);
    background: color-mix(in srgb, var(--accent) 14%, transparent);
    color: var(--accent);
    font-size: 12px;
    font-weight: 800;
    padding: 7px 12px;
    border-radius: 10px;
    cursor: pointer;
    transition: box-shadow var(--t-base, 180ms ease), transform 80ms ease;
  }
  .day-refresh:hover { box-shadow: 0 0 14px color-mix(in srgb, var(--accent) 26%, transparent); }
  .day-refresh:active { transform: scale(0.97); }
  .day-refresh:disabled { opacity: 0.5; cursor: not-allowed; }

  .league-count {
    font-size: 10.5px;
    font-weight: 800;
    padding: 2px 8px;
    border-radius: 999px;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    color: var(--accent);
  }

  /* ── League accordion headers ── */
  .league-accordion {
    width: 100%;
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 0 0 8px;
    padding: 10px 12px;
    border-radius: 12px;
    border: 1px solid var(--c-border);
    background: var(--c-glass-sm);
    color: var(--c-text);
    cursor: pointer;
    font: inherit;
    font-size: 12.5px;
    font-weight: 900;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    text-align: left;
    transition:
      background var(--t-base, 180ms ease),
      border-color var(--t-base, 180ms ease),
      box-shadow var(--t-base, 180ms ease);
  }
  .league-accordion:hover {
    border-color: color-mix(in srgb, var(--accent) 45%, transparent);
    background: color-mix(in srgb, var(--accent) 8%, transparent);
  }
  .league-accordion:focus-visible {
    outline: 2px solid color-mix(in srgb, var(--accent) 60%, transparent);
    outline-offset: 2px;
  }
  .league-name { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  :global(.accordion-caret) {
    flex-shrink: 0;
    color: var(--c-text-dim, var(--c-text));
    transition: transform var(--t-base, 180ms ease);
  }
  :global(.accordion-caret.is-collapsed) { transform: rotate(-90deg); }

  /* ── Filter toolbar (search + sort + perf) ── */
  .filter-toolbar {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-bottom: 14px;
  }

  .search-box {
    position: relative;
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 0 12px;
    height: 44px;
    border-radius: 12px;
    border: 1px solid var(--c-border-md);
    background: var(--c-surface-1);
    transition: border-color var(--t-base, 180ms ease), box-shadow var(--t-base, 180ms ease);
  }
  .search-box:focus-within {
    border-color: color-mix(in srgb, var(--accent) 55%, transparent);
    box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent) 14%, transparent);
  }
  :global(.search-ic) { flex-shrink: 0; color: var(--c-text-dim, var(--c-text)); }
  .search-box input {
    flex: 1;
    min-width: 0;
    border: none;
    background: transparent;
    color: var(--c-text);
    font-size: 13.5px;
    font-weight: 600;
    outline: none;
  }
  .search-box input::placeholder { color: var(--c-text-dim, var(--c-text)); opacity: 0.7; }
  .search-box input::-webkit-search-cancel-button { display: none; }

  .search-clear {
    flex-shrink: 0;
    width: 24px;
    height: 24px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    border: none;
    background: var(--c-glass-sm);
    color: var(--c-text-dim, var(--c-text));
    cursor: pointer;
    transition: background var(--t-base, 180ms ease), color var(--t-base, 180ms ease);
  }
  .search-clear:hover { color: var(--c-text); background: var(--c-glass-lg); }

  .perf-badge {
    flex-shrink: 0;
    font-size: 10px;
    font-weight: 800;
    font-variant-numeric: tabular-nums;
    padding: 2px 7px;
    border-radius: 999px;
    background: color-mix(in srgb, #22c55e 10%, transparent);
    border: 1px solid color-mix(in srgb, #22c55e 35%, transparent);
    color: #22c55e;
  }
  .perf-badge.warn {
    background: color-mix(in srgb, #f59e0b 12%, transparent);
    border-color: color-mix(in srgb, #f59e0b 45%, transparent);
    color: #f59e0b;
  }

  .sort-row {
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .sort-label {
    font-size: 10.5px;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--c-text-dim, var(--c-text));
    margin-right: 2px;
  }
  .sort-btn {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    padding: 7px 12px;
    border-radius: 999px;
    border: 1px solid var(--c-border);
    background: var(--c-glass-sm);
    color: var(--c-text-dim, var(--c-text));
    font-size: 12px;
    font-weight: 800;
    cursor: pointer;
    transition:
      background var(--t-base, 180ms ease),
      border-color var(--t-base, 180ms ease),
      color var(--t-base, 180ms ease),
      transform 80ms ease;
  }
  .sort-btn:hover { border-color: color-mix(in srgb, var(--accent) 45%, transparent); }
  .sort-btn:active { transform: scale(0.96); }
  .sort-btn.is-active {
    background: color-mix(in srgb, var(--accent) 16%, transparent);
    border-color: color-mix(in srgb, var(--accent) 60%, transparent);
    color: var(--accent);
  }

  .match-list { display: flex; flex-direction: column; gap: 14px; }

  /* ── Agent working state ── */
  .working {
    text-align: center;
    padding: 34px 20px 40px;
    border: 1px dashed var(--c-border-md);
    border-radius: 16px;
    background: var(--c-surface-2);
  }

  .working-title { margin: 0 0 8px; font-size: 14.5px; font-weight: 800; color: var(--c-text); }
  .working-sub { margin: 0; font-size: 12.5px; color: var(--c-text-dim, var(--c-text)); line-height: 1.55; }

  /* ── Results bar ── */
  .results-bar {
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
    margin-bottom: 16px;
    padding: 10px 12px;
    border: 1px solid var(--c-border-md);
    border-radius: 16px;
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--accent) 10%, transparent), transparent 55%),
      var(--c-surface-2);
  }

  .results-bar .icon-btn {
    width: 40px;
    height: 40px;
    border-radius: 12px;
  }

  .results-meta { display: flex; flex-wrap: wrap; gap: 8px; flex: 1; }

  .empty-state {
    text-align: center;
    padding: 40px 20px;
    border: 1px dashed var(--c-border-md);
    border-radius: 16px;
    color: var(--c-text-dim, var(--c-text));
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 6px;
  }

  .empty-ic {
    width: 60px;
    height: 60px;
    border-radius: 18px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 4px;
    background: color-mix(in srgb, var(--accent) 12%, transparent);
    border: 1px solid color-mix(in srgb, var(--accent) 30%, transparent);
    color: var(--accent);
    box-shadow: 0 0 26px color-mix(in srgb, var(--accent) 20%, transparent);
  }

  .empty-state p { margin: 0; font-size: 13px; }
  .empty-state .hint { font-size: 12px; opacity: 0.75; }

  .bootstrap-msg {
    font-size: 12.5px;
    color: var(--accent);
    font-weight: 700;
    padding: 8px 14px;
    border-radius: 10px;
    background: color-mix(in srgb, var(--accent) 12%, transparent);
    border: 1px solid color-mix(in srgb, var(--accent) 30%, transparent);
    animation: pulse-glow 2s ease-in-out infinite;
  }

  @keyframes pulse-glow {
    0%, 100% { box-shadow: 0 0 10px color-mix(in srgb, var(--accent) 20%, transparent); }
    50% { box-shadow: 0 0 22px color-mix(in srgb, var(--accent) 40%, transparent); }
  }

  .empty-actions {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 6px;
  }

  .cta.secondary {
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border-md);
    color: var(--c-text);
    box-shadow: none;
  }
  .cta.secondary:hover:not(:disabled) {
    background: color-mix(in srgb, var(--accent) 10%, transparent);
    border-color: color-mix(in srgb, var(--accent) 40%, transparent);
    color: var(--accent);
  }

  .predictor-foot { margin-top: 28px; padding-top: 14px; border-top: 1px solid var(--c-border); }
  .predictor-foot p { font-size: 11px; color: var(--c-text-dim, var(--c-text)); line-height: 1.6; text-align: center; }

  .spin { display: inline-flex; animation: spn 1s linear infinite; }
  @keyframes spn { to { transform: rotate(360deg); } }

  /* ── Game status tabs ── */
  .tabs-row {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 16px;
  }

  .tabs-row .game-tabs {
    flex: 1;
    margin-bottom: 0;
  }

  .scores-sync-btn {
    flex-shrink: 0;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    padding: 10px 12px;
    border-radius: 10px;
    border: 1px solid var(--c-border-md);
    background: var(--c-glass-sm);
    color: var(--c-text-dim, var(--c-text));
    font-size: 12px;
    font-weight: 800;
    cursor: pointer;
    transition:
      background var(--t-base, 180ms ease),
      border-color var(--t-base, 180ms ease),
      color var(--t-base, 180ms ease),
      transform 80ms ease;
  }

  .scores-sync-btn:hover:not(:disabled) {
    color: #22c55e;
    border-color: color-mix(in srgb, #22c55e 45%, transparent);
    background: color-mix(in srgb, #22c55e 8%, transparent);
  }

  .scores-sync-btn:active:not(:disabled) { transform: scale(0.96); }
  .scores-sync-btn:disabled { opacity: 0.5; cursor: not-allowed; }

  .game-tabs {
    display: flex;
    gap: 6px;
    margin-bottom: 16px;
    padding: 5px;
    border-radius: 14px;
    background: var(--c-surface-2);
    border: 1px solid var(--c-border-md);
  }

  .game-tab {
    flex: 1;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 7px;
    padding: 10px 8px;
    border-radius: 10px;
    border: 1px solid transparent;
    background: transparent;
    color: var(--c-text-dim, var(--c-text));
    font-size: 13px;
    font-weight: 800;
    cursor: pointer;
    transition:
      background var(--t-base, 180ms ease),
      border-color var(--t-base, 180ms ease),
      color var(--t-base, 180ms ease);
  }

  .game-tab:hover { color: var(--accent); }
  .game-tab.is-active {
    background: color-mix(in srgb, var(--accent) 14%, transparent);
    border-color: color-mix(in srgb, var(--accent) 55%, transparent);
    color: var(--accent);
  }

  .tab-count {
    font-size: 10.5px;
    font-weight: 800;
    padding: 2px 7px;
    border-radius: 999px;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    color: var(--c-text-dim, var(--c-text));
    font-variant-numeric: tabular-nums;
  }

  .game-tab.is-active .tab-count {
    color: var(--accent);
    border-color: color-mix(in srgb, var(--accent) 40%, transparent);
  }

  .live-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: #22c55e;
    animation: tab-live-pulse 1.2s ease-in-out infinite;
  }

  @keyframes tab-live-pulse {
    0%, 100% { opacity: 1; transform: scale(1); box-shadow: 0 0 0 0 color-mix(in srgb, #22c55e 55%, transparent); }
    50% { opacity: 0.6; transform: scale(1.3); box-shadow: 0 0 0 5px color-mix(in srgb, #22c55e 0%, transparent); }
  }
</style>
