<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import { ArrowLeft, RefreshCw, Inbox, Clock3, Check, ChevronLeft, Wand2, Activity } from '@lucide/svelte';
  import PredictorTeamSelect from './PredictorTeamSelect.svelte';
  import PredictorStatusBanner from './PredictorStatusBanner.svelte';
  import PredictorMatchCard from './PredictorMatchCard.svelte';
  import PredictorVerdictPanel from './PredictorVerdictPanel.svelte';
  import PredictorSportIcon from './PredictorSportIcon.svelte';
  import { api, subscribeConvexQuery } from '$lib/convexClient';
  import {
    todayKey,
    fetchPredictorDay,
    fetchPredictorMatches,
    fetchPredictorVerdict,
    fetchActiveRun,
    startPredictorRefresh,
    analyzeCachedMatch
  } from '$lib/predictorClient';
  import {
    DEFAULT_CONFIDENCE_FLOOR,
    type PredictorDay,
    type PredictorMatch,
    type PredictorRun,
    type PredictorSportId
  } from '$lib/predictorTypes';
  import { buildPredictorInsights } from '$lib/predictorInsights';
  import {
    PREDICTOR_MAX_SELECTIONS,
    clearSelection,
    saveSelection,
    toggleSelection,
    pruneSelection
  } from '$lib/predictorSelections';
  import { AGENT_DEFS } from '$lib/agentUi';
  import type { Analysis, Pick } from '$lib/engine';

  let {
    sportId = null as PredictorSportId | null,
    accent = '#6366f1'
  }: {
    sportId?: PredictorSportId | null;
    accent?: string;
  } = $props();

  import DailyPnlSummary from './DailyPnlSummary.svelte';
  import { generateGreatMindsDebate } from '$lib/greatMindsEngine';
  import type { GreatMindsDebateResult } from '$lib/predictorTypes';

  type Phase = 'select' | 'analyzing' | 'results';
  type SelectedAnalysis = {
    match: PredictorMatch;
    analysis: Analysis;
    qualifying: Pick[];
    insight?: Record<string, unknown> | null;
    greatMindsDebate?: GreatMindsDebateResult | null;
  };

  const activeSport = $derived(sportId);
  const effectiveSport = $derived(activeSport ?? ('football' as PredictorSportId));
  const dayKey = $derived(todayKey());

  let day = $state<PredictorDay | null>(null);
  let matches = $state<PredictorMatch[]>([]);
  let run = $state<PredictorRun | null>(null);
  let loading = $state(true);
  let busy = $state(false);
  let error = $state('');
  let now = $state(Date.now());

  // ── Selection workflow state ─────────────────────────────────────────────────
  let phase = $state<Phase>('select');
  let selectedIds = $state<string[]>([]);
  let results = $state<SelectedAnalysis[]>([]);
  let agentProgress = $state(0);
  let agentStage = $state('');
  let selectNotice = $state('');
  let progressTimer: ReturnType<typeof setInterval> | null = null;
  let revealTimer: ReturnType<typeof setTimeout> | null = null;

  // ── Per-match cached verdict reveal (clicking a card shows only that match) ──
  let verdictCache = $state<Record<string, any | null>>({});
  let expandedMatches = $state<Record<string, boolean>>({});

  const insightFor = (m: PredictorMatch) => {
    const hit = verdictCache[m.matchId];
    return hit && typeof hit === 'object' ? hit : null;
  };

  async function revealMatch(m: PredictorMatch) {
    expandedMatches = { ...expandedMatches, [m.matchId]: !expandedMatches[m.matchId] };
    if (verdictCache[m.matchId] !== undefined) return;
    verdictCache = { ...verdictCache, [m.matchId]: null };
    try {
      const verdict = await fetchPredictorVerdict(dayKey, m.matchId);
      if (verdict?.aiReport && typeof verdict.aiReport === 'object') {
        verdictCache = { ...verdictCache, [m.matchId]: verdict.aiReport };
      }
    } catch (_) {
      /* leave null — card still shows engine picks/metrics */
    }
  }

  const isRunning = $derived(!!run && run.status === 'running');
  const refreshProgress = $derived(run?.progress ?? 0);
  const selectedSet = $derived(new Set(selectedIds));
  const isSelected = (id: string) => selectedSet.has(id);
  const qualifiedCount = $derived(results.filter((r) => r.qualifying.length > 0).length);
  const agentsRun = $derived(AGENT_DEFS.map((a) => a.name));
  const sourcesUsed = $derived(day?.sourcesUsed ?? []);
  const warnings = $derived(run?.message ? [run.message] : []);
  const runError = $derived(
    (run?.status === 'error' ? run.message || 'Agent refresh failed.' : '') ||
      (day?.status === 'error' ? day.message || 'Day cache refresh failed.' : '') ||
      ''
  );

  const byLeague = $derived.by(() => {
    const groups: Record<string, PredictorMatch[]> = {};
    for (const m of matches) {
      const key = m.league || 'Other';
      (groups[key] ??= []).push(m);
    }
    return groups;
  });

  const isPast = (m: PredictorMatch) => m.startTime > 0 && m.startTime < now;

  // ── Deterministic per-match screening (memoized) ─────────────────────────────
  const analysisCache = new Map<string, { analysis: any; qualifying: Pick[] }>();
  function analyzeMatch(match: PredictorMatch) {
    if (analysisCache.has(match.matchId)) return analysisCache.get(match.matchId)!;
    const res = analyzeCachedMatch(match, DEFAULT_CONFIDENCE_FLOOR);
    analysisCache.set(match.matchId, res);
    return res;
  }

  // ── Selection controls ────────────────────────────────────────────────────────
  function toggleMatch(matchId: string) {
    const res = toggleSelection(effectiveSport, dayKey, matchId);
    selectedIds = res.selection;
    selectNotice = res.capped
      ? `You can analyse up to ${PREDICTOR_MAX_SELECTIONS} matches at a time. Deselect one first to pick this one.`
      : '';
  }

  function selectAll() {
    const eligible = matches.filter((m) => !isPast(m));
    selectedIds = eligible.slice(0, PREDICTOR_MAX_SELECTIONS).map((m) => m.matchId);
    saveSelection(effectiveSport, dayKey, selectedIds);
    selectNotice =
      eligible.length > PREDICTOR_MAX_SELECTIONS
        ? `Analysing the first ${PREDICTOR_MAX_SELECTIONS} matches. Deselect one to make room for another.`
        : '';
  }

  function clearAll() {
    selectedIds = [];
    clearSelection(effectiveSport, dayKey);
    selectNotice = '';
  }

  // ── Analysis run (deterministic compute + agent progression) ─────────────────
  function stageForPct(p: number): string {
    let acc = 0;
    for (const a of AGENT_DEFS) {
      acc += a.weight;
      if (p <= acc) return a.stage;
    }
    return 'Compiling verdicts';
  }

  function clearProgress() {
    if (progressTimer) {
      clearInterval(progressTimer);
      progressTimer = null;
    }
    if (revealTimer) {
      clearTimeout(revealTimer);
      revealTimer = null;
    }
  }

  function animateAgents() {
    clearProgress();
    const start = Date.now();
    const DURATION = 3600;
    progressTimer = setInterval(() => {
      const pct = Math.min(100, Math.round(((Date.now() - start) / DURATION) * 100));
      agentProgress = pct;
      agentStage = stageForPct(pct);
      if (pct >= 100) {
        clearProgress();
        revealTimer = setTimeout(() => {
          phase = 'results';
        }, 220);
      }
    }, 120);
  }

  function analyzeSelected() {
    const sid = effectiveSport;
    if (!sid) return;
    const selected = matches.filter((m) => selectedIds.includes(m.matchId));
    if (selected.length === 0) return;
    results = selected.map((m) => {
      const res = analyzeMatch(m);
      const greatMindsDebate = generateGreatMindsDebate(m, res.analysis);
      return { match: m, analysis: res.analysis, qualifying: res.qualifying, insight: null, greatMindsDebate };
    });
    phase = 'analyzing';
    agentProgress = 0;
    agentStage = AGENT_DEFS[0]?.stage ?? 'Fixtures fetched';
    animateAgents();
    enrichWithLlmVerdicts(selected);
  }

  // Surface the stored LLM (Agnes/OpenRouter) verdict for each selected match
  // when the cache has one; otherwise the deterministic insights render.
  async function enrichWithLlmVerdicts(selected: PredictorMatch[]) {
    const dk = dayKey;
    const entries = await Promise.all(
      selected.map(async (m) => {
        let llmInsight: Record<string, unknown> | null = null;
        try {
          const verdict = await fetchPredictorVerdict(dk, m.matchId);
          if (verdict?.aiReport && typeof verdict.aiReport === 'object') {
            llmInsight = verdict.aiReport;
          }
        } catch (_) {
          /* ignore — fall back to deterministic insights */
        }
        return { matchId: m.matchId, llmInsight };
      })
    );
    results = results.map((r) => {
      const hit = entries.find((e) => e.matchId === r.match.matchId);
      return hit?.llmInsight ? { ...r, insight: hit.llmInsight } : r;
    });
  }

  function backToSelection() {
    clearProgress();
    phase = 'select';
  }

  // ── Data loading + live subscriptions (reacts to sport/day changes) ──────────
  let unsubs: (() => void)[] = [];
  let sportEpoch = 0;

  function disposeSubs() {
    unsubs.forEach((u) => u());
    unsubs = [];
  }

  async function load(sid: PredictorSportId, dk: string, epoch: number) {
    loading = true;
    error = '';
    const [d, m, r] = await Promise.all([
      fetchPredictorDay(sid, dk).catch(() => null),
      fetchPredictorMatches(sid, dk).catch(() => []),
      fetchActiveRun(sid, dk).catch(() => null)
    ]);
    if (epoch !== sportEpoch) return; // stale response after a sport switch
    day = d;
    matches = m;
    run = r;
    selectedIds = pruneSelection(sid, dk, m.map((x) => x.matchId));
    loading = false;
  }

  function subscribe(sid: PredictorSportId, dk: string, epoch: number) {
    void subscribeConvexQuery<PredictorRun | null>(api.predictor.getActiveRun, { sportId: sid, dayKey: dk }, (r) => {
      if (r && epoch === sportEpoch) run = r;
    }).then((u) => {
      if (epoch === sportEpoch) unsubs.push(u);
      else u();
    });
    void subscribeConvexQuery<PredictorDay | null>(api.predictor.getDay, { sportId: sid, dayKey: dk }, (d) => {
      if (d && epoch === sportEpoch) day = d;
    }).then((u) => {
      if (epoch === sportEpoch) unsubs.push(u);
      else u();
    });
    void subscribeConvexQuery<PredictorMatch[]>(api.predictor.listMatches, { sportId: sid, dayKey: dk }, (m) => {
      if (Array.isArray(m) && epoch === sportEpoch) matches = m;
    }).then((u) => {
      if (epoch === sportEpoch) unsubs.push(u);
      else u();
    });
  }

  $effect(() => {
    const sid = effectiveSport;
    const dk = dayKey;
    if (!sid) return;
    sportEpoch += 1;
    const epoch = sportEpoch;
    clearProgress();
    phase = 'select';
    results = [];
    selectNotice = '';
    disposeSubs();
    void load(sid, dk, epoch);
    subscribe(sid, dk, epoch);
  });

  onMount(() => {
    const timer = setInterval(() => {
      now = Date.now();
    }, 60_000);
    return () => {
      clearInterval(timer);
      disposeSubs();
      clearProgress();
    };
  });

  async function refresh() {
    const sid = effectiveSport;
    if (!sid || busy) return;
    busy = true;
    error = '';
    try {
      const res = await startPredictorRefresh(sid, dayKey);
      if (!res.alreadyRunning) {
        run = {
          runId: res.runId,
          dayKey,
          sportId: sid,
          progress: 0,
          stage: 'Queued',
          status: 'running',
          startedAt: Date.now(),
          updatedAt: Date.now()
        } as PredictorRun;
      }
    } catch (err: any) {
      error = String(err?.message || err);
    } finally {
      busy = false;
    }
  }

  function backHome() {
    void goto('/');
  }
</script>

<div class="predictor-root" style={`--accent:${accent}`}>
  <div class="predictor-inner">
    <header class="predictor-head">
      <button class="icon-btn" aria-label="Back to sports selection" onclick={backHome} type="button">
        <ArrowLeft size={20} stroke-width={2.5} />
      </button>
      <div class="title-block">
        <span class="eyebrow">Eze Ugo &amp; the Agent Team</span>
        <h1>AI Predictor</h1>
        <div class="title-sport-ic" style={`color:${accent}`}>
          <PredictorSportIcon sport={effectiveSport} size={20} strokeWidth={2} />
        </div>
      </div>
      <button
        class="icon-btn refresh"
        aria-label="Refresh day cache"
        title="Refresh day cache"
        onclick={refresh}
        type="button"
        disabled={busy || isRunning || phase === 'analyzing'}
      >
        <span class:spin={busy || isRunning}><RefreshCw size={18} stroke-width={2.2} /></span>
      </button>
    </header>

    <PredictorTeamSelect active={sportId} {accent} />

    {#if loading}
      <div class="placeholder">
        <span class="ph-icon"><Activity size={22} stroke-width={1.8} /></span>
        Loading today's scheduled matches…
      </div>
    {:else}
      <DailyPnlSummary />

      <PredictorStatusBanner
        {day}
        progress={phase === 'analyzing' ? agentProgress : isRunning ? refreshProgress : day?.status === 'ready' ? 100 : 0}
        stage={phase === 'analyzing' ? agentStage : ''}
        running={phase === 'analyzing' || isRunning}
        error={error || runError}
      />

      {#if phase === 'select'}
        <div class="selection-bar">
          <div class="sel-row">
            <span class="summary-chip">
              <Check size={14} stroke-width={2.6} />
              {selectedIds.length} of {PREDICTOR_MAX_SELECTIONS} selected
            </span>
            {#if matches.length > 0}
              <span class="summary-chip muted">
                {matches.length} scheduled {effectiveSport === 'rally' ? 'games' : 'matches'}
              </span>
            {/if}
            <span class="sel-actions">
              {#if matches.length > 0}
                <button class="link-btn" type="button" onclick={selectAll}>
                  Select {Math.min(PREDICTOR_MAX_SELECTIONS, matches.length)}
                </button>
              {/if}
              <button class="link-btn" type="button" onclick={clearAll} disabled={selectedIds.length === 0}>Clear</button>
            </span>
          </div>

          {#if selectNotice}
            <p class="notice" role="status">{selectNotice}</p>
          {/if}

          <button class="cta analyze" type="button" onclick={analyzeSelected} disabled={selectedIds.length === 0}>
            <Wand2 size={15} stroke-width={2.4} />
            Analyse selected {selectedIds.length > 0 ? `(${selectedIds.length})` : ''}
          </button>
        </div>

        {#if matches.length > 0}
          {#each Object.entries(byLeague) as [league, group] (league)}
            <section class="league-group">
              <h2 class="league-title">
                <span class="league-name">{league}</span>
                <span class="league-count">{group.length}</span>
              </h2>
              <div class="match-list">
                {#each group as match (match.matchId)}
                  {@const res = analyzeMatch(match)}
                  <PredictorMatchCard
                    match={match}
                    analysis={res.analysis}
                    qualifying={res.qualifying}
                    insight={insightFor(match)}
                    expanded={expandedMatches[match.matchId] ?? false}
                    {accent}
                    selectable
                    selected={isSelected(match.matchId)}
                    inPlay={isPast(match)}
                    onSelect={() => toggleMatch(match.matchId)}
                    onClick={() => {
                      expandedMatches = { ...expandedMatches, [match.matchId]: !expandedMatches[match.matchId] };
                      void revealMatch(match);
                    }}
                  />
                {/each}
              </div>
            </section>
          {/each}
        {:else}
          <div class="empty-state">
            <div class="empty-ic">
              <PredictorSportIcon sport={effectiveSport} size={34} strokeWidth={1.6} />
            </div>
            <p>No scheduled matches cached for today ({dayKey}).</p>
            <p class="hint">The midnight scheduler pre-caches all six sports. You can also run the agent team now.</p>
            <button class="cta" type="button" onclick={refresh} disabled={busy || isRunning}>Run agents now</button>
          </div>
        {/if}
      {:else if phase === 'analyzing'}
        <div class="working">
          <p class="working-title">
            Eze Ugo &amp; team are preparing verdicts for your {results.length} selected match{results.length === 1 ? '' : 'es'}…
          </p>
          <p class="working-sub">
            Screening runs deterministically over the cached scopes — no network round-trip required.
          </p>
        </div>
      {:else}
        <div class="results-bar">
          <button
            class="icon-btn"
            aria-label="Back to match selection"
            title="Change selection"
            onclick={backToSelection}
            type="button"
          >
            <ChevronLeft size={20} stroke-width={2.5} />
          </button>
          <div class="results-meta">
            <span class="summary-chip">
              <Check size={14} stroke-width={2.6} />
              {results.length} match{results.length === 1 ? '' : 'es'} analysed
            </span>
            <span class="summary-chip">{qualifiedCount} over the {DEFAULT_CONFIDENCE_FLOOR}% floor</span>
            <span class="summary-chip muted"><Clock3 size={14} stroke-width={2.2} /> Cache: {dayKey}</span>
          </div>
          <button class="link-btn" type="button" onclick={backToSelection}>Change selection</button>
        </div>

        {#if results.length > 0}
          <div class="match-list">
            {#each results as r (r.match.matchId)}
              <PredictorMatchCard match={r.match} analysis={r.analysis} qualifying={r.qualifying} {accent} expanded />
              <PredictorVerdictPanel
                insight={r.insight ? (r.insight as import('$lib/cloudflareAi').AiAnalysisResult['insights']) : buildPredictorInsights(r.match, r.qualifying)}
                greatMindsDebate={r.greatMindsDebate}
                picks={r.qualifying}
                metrics={r.analysis?.metrics}
                {agentsRun}
                citations={sourcesUsed}
                {warnings}
                {accent}
              />
            {/each}
          </div>
        {:else}
          <div class="empty-state">
            <div class="empty-ic"><Inbox size={30} stroke-width={1.8} /></div>
            <p>No matches were analysed.</p>
            <p class="hint">Go back and select at least one scheduled match to generate a verdict.</p>
            <button class="cta" type="button" onclick={backToSelection}>Select matches</button>
          </div>
        {/if}
      {/if}
    {/if}

    <footer class="predictor-foot">
      <p>
        Data refreshed nightly at 00:00 WAT (23:00 UTC) from betwatch.fr and cross-reference odds, betting and prediction registries.
        Select any scheduled match to run the agent team, which surfaces only selections that clear the
        {DEFAULT_CONFIDENCE_FLOOR}% Real Win Chance floor. All match times shown in West Africa Time (WAT, UTC+1). Always gamble responsibly.
      </p>
    </footer>
  </div>
</div>

<style>
  .predictor-root { min-height: 100vh; background: var(--c-surface, #0b1120); }
  .predictor-inner { max-width: 680px; margin: 0 auto; padding: 14px 16px 40px; }

  .predictor-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    padding: 10px 0 14px;
    position: sticky;
    top: 0;
    z-index: 50;
    background: var(--c-surface-2);
    backdrop-filter: blur(24px) saturate(180%);
    -webkit-backdrop-filter: blur(24px) saturate(180%);
    border-bottom: 1px solid var(--c-border);
    box-shadow: 0 1px 0 0 color-mix(in srgb, var(--accent) 25%, transparent);
  }

  .icon-btn {
    width: 46px;
    height: 46px;
    border: 1px solid var(--c-border-md);
    border-radius: 14px;
    background: var(--c-glass-sm);
    color: var(--c-text);
    display: inline-flex;
    align-items: center;
    justify-content: center;
    transition: background var(--t-base, 180ms ease), border-color var(--t-base, 180ms ease), transform 80ms ease;
  }

  .icon-btn:hover { background: var(--c-glass-hover); border-color: var(--c-border-2); }
  .icon-btn:active { transform: scale(0.93); }
  .icon-btn.refresh:hover { color: var(--accent); border-color: color-mix(in srgb, var(--accent) 50%, transparent); }
  .icon-btn:disabled { opacity: 0.5; cursor: not-allowed; }

  .title-block { text-align: center; }

  .eyebrow {
    display: block;
    color: var(--accent);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    font-size: 10px;
    font-weight: 800;
  }

  .title-block h1 { font-size: 21px; margin: 2px 0 0; letter-spacing: -0.02em; font-weight: 900; }

  .title-sport-ic {
    display: inline-flex;
    margin-top: 3px;
    filter: drop-shadow(0 0 8px color-mix(in srgb, var(--accent) 60%, transparent));
  }

  .placeholder {
    padding: 40px 0;
    text-align: center;
    color: var(--c-text-dim, var(--c-text));
    font-size: 13px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
  }

  .ph-icon {
    display: inline-flex;
    color: var(--accent);
    animation: ph-pulse 1.8s ease-in-out infinite;
  }

  @keyframes ph-pulse {
    0%, 100% { opacity: 0.45; transform: scale(1); }
    50% { opacity: 1; transform: scale(1.12); }
  }

  /* ── Selection bar ── */
  .selection-bar {
    border: 1px solid var(--c-border-md);
    border-radius: 16px;
    padding: 12px 14px;
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--accent) 10%, transparent), transparent 55%),
      var(--c-surface-2);
    margin-bottom: 16px;
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .sel-row {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 8px;
  }

  .summary-chip {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 11px;
    border-radius: 999px;
    font-size: 11.5px;
    font-weight: 800;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    color: #22c55e;
  }

  .summary-chip.muted { color: var(--c-text-dim, var(--c-text)); }

  .sel-actions { margin-left: auto; display: inline-flex; gap: 4px; }

  .link-btn {
    border: none;
    background: transparent;
    color: var(--accent);
    font-size: 12px;
    font-weight: 800;
    padding: 4px 8px;
    border-radius: 8px;
    cursor: pointer;
    transition: background var(--t-base, 180ms ease);
  }

  .link-btn:hover { background: var(--c-glass-sm); }
  .link-btn:disabled { opacity: 0.4; cursor: not-allowed; }

  .notice {
    margin: 0;
    font-size: 12px;
    color: #f59e0b;
    background: color-mix(in srgb, #f59e0b 8%, transparent);
    border: 1px solid color-mix(in srgb, #f59e0b 28%, transparent);
    border-radius: 10px;
    padding: 8px 10px;
  }

  .cta {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    width: 100%;
    padding: 13px 20px;
    border-radius: 14px;
    border: 1px solid color-mix(in srgb, var(--accent) 60%, transparent);
    background: color-mix(in srgb, var(--accent) 20%, transparent);
    color: var(--accent);
    font-weight: 800;
    font-size: 14px;
    cursor: pointer;
    transition: box-shadow var(--t-base, 180ms ease), transform 80ms ease;
  }
  .cta:hover { box-shadow: 0 0 20px color-mix(in srgb, var(--accent) 32%, transparent); }
  .cta:active { transform: scale(0.985); }
  .cta:disabled { opacity: 0.5; cursor: not-allowed; box-shadow: none; }

  /* ── League groups ── */
  .league-group { margin-bottom: 18px; }

  .league-title {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 0 0 8px;
    font-size: 12.5px;
    font-weight: 900;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    color: var(--c-text-dim, var(--c-text));
  }

  .league-count {
    font-size: 10.5px;
    font-weight: 800;
    padding: 2px 8px;
    border-radius: 999px;
    background: var(--c-glass-sm);
    border: 1px solid var(--c-border);
    color: var(--accent);
  }

  .match-list { display: flex; flex-direction: column; gap: 14px; }

  /* ── Agent working state ── */
  .working {
    text-align: center;
    padding: 34px 20px 40px;
    border: 1px dashed var(--c-border-md);
    border-radius: 16px;
    background: var(--c-surface-2);
  }

  .working-title { margin: 0 0 8px; font-size: 14.5px; font-weight: 800; color: var(--c-text); }
  .working-sub { margin: 0; font-size: 12.5px; color: var(--c-text-dim, var(--c-text)); line-height: 1.55; }

  /* ── Results bar ── */
  .results-bar {
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
    margin-bottom: 16px;
    padding: 10px 12px;
    border: 1px solid var(--c-border-md);
    border-radius: 16px;
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--accent) 10%, transparent), transparent 55%),
      var(--c-surface-2);
  }

  .results-bar .icon-btn {
    width: 40px;
    height: 40px;
    border-radius: 12px;
  }

  .results-meta { display: flex; flex-wrap: wrap; gap: 8px; flex: 1; }

  .empty-state {
    text-align: center;
    padding: 40px 20px;
    border: 1px dashed var(--c-border-md);
    border-radius: 16px;
    color: var(--c-text-dim, var(--c-text));
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 6px;
  }

  .empty-ic {
    width: 60px;
    height: 60px;
    border-radius: 18px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 4px;
    background: color-mix(in srgb, var(--accent) 12%, transparent);
    border: 1px solid color-mix(in srgb, var(--accent) 30%, transparent);
    color: var(--accent);
    box-shadow: 0 0 26px color-mix(in srgb, var(--accent) 20%, transparent);
  }

  .empty-state p { margin: 0; font-size: 13px; }
  .empty-state .hint { font-size: 12px; opacity: 0.75; }

  .predictor-foot { margin-top: 28px; padding-top: 14px; border-top: 1px solid var(--c-border); }
  .predictor-foot p { font-size: 11px; color: var(--c-text-dim, var(--c-text)); line-height: 1.6; text-align: center; }

  .spin { display: inline-flex; animation: spn 1s linear infinite; }
  @keyframes spn { to { transform: rotate(360deg); } }
</style>
