<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { PREDICTOR_SPORTS, type PredictorSportId } from '$lib/predictorTypes';

  const SPORT_LABEL: Record<PredictorSportId, string> = {
    football: 'Football',
    basketball: 'Basketball',
    tennis: 'Tennis',
    rally: 'Rally',
    hockey: 'Hockey',
    baseball: 'Baseball'
  };

  const SPORT_COLOR: Record<PredictorSportId, string> = {
    football: '#22c55e',
    basketball: '#f97316',
    tennis: '#a3e635',
    rally: '#38bdf8',
    hockey: '#6366f1',
    baseball: '#e11d48'
  };

  let {
    active = null as PredictorSportId | null,
    accent = '#6366f1'
  }: {
    active?: PredictorSportId | null;
    accent?: string;
  } = $props();

  function pick(sport: PredictorSportId) {
    void goto(sport === active ? '/predictor' : `/predictor/${sport}`);
  }
</script>

<div class="team-select" role="tablist" aria-label="Predictor sport" style={`--accent:${accent}`}>
  <button
    class="team-btn {active === null ? 'is-active' : ''}"
    type="button"
    role="tab"
    aria-selected={active === null}
    onclick={() => pick(active ?? PREDICTOR_SPORTS[0])}
    title="Overall AI Predictor"
  >
    <span class="dot all">All</span>
  </button>

  {#each PREDICTOR_SPORTS as sport}
    <button
      class="team-btn {active === sport ? 'is-active' : ''}"
      type="button"
      role="tab"
      aria-selected={active === sport}
      onclick={() => pick(sport)}
      title={`${SPORT_LABEL[sport]} AI Predictor`}
    >
      <span class="dot" style={`background:${SPORT_COLOR[sport]}`}></span>
      <span class="lbl">{SPORT_LABEL[sport]}</span>
    </button>
  {/each}
</div>

<style>
  .team-select {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    margin: 14px 0 18px;
  }

  .team-btn {
    display: inline-flex;
    align-items: center;
    gap: 7px;
    padding: 8px 13px;
    border-radius: 999px;
    border: 1px solid var(--c-border-md);
    background: var(--c-glass-sm);
    color: var(--c-text);
    font-size: 12.5px;
    font-weight: 800;
    cursor: pointer;
    transition:
      border-color var(--t-base, 180ms ease),
      background var(--t-base, 180ms ease),
      transform 80ms ease;
  }

  .team-btn:hover {
    border-color: color-mix(in srgb, var(--accent) 55%, transparent);
    background: var(--c-glass-hover);
  }

  .team-btn.is-active {
    border-color: color-mix(in srgb, var(--accent) 70%, transparent);
    background: color-mix(in srgb, var(--accent) 16%, transparent);
    box-shadow: 0 0 14px color-mix(in srgb, var(--accent) 22%, transparent);
  }

  .team-btn:active { transform: scale(0.95); }

  .dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    font-size: 9px;
    font-weight: 900;
    color: var(--c-surface-2);
  }

  .dot.all {
    background: var(--accent);
  }

  .lbl { white-space: nowrap; }
</style>
