<script lang="ts">
  // @ts-ignore: svelte-kit ambient path shims generated by prepare
  import { goto } from '$app/navigation';
  import { onMount, onDestroy } from 'svelte';
  import Header from './Header.svelte';
  import ScopeTabs from './ScopeTabs.svelte';
  import VerdictHero from './VerdictHero.svelte';
  import MetricStrip from './MetricStrip.svelte';
  import ProfileCard from './ProfileCard.svelte';
  import RankingPanel from './RankingPanel.svelte';
  import MarketAccordion from './MarketAccordion.svelte';
  import LineRowOu from './LineRowOu.svelte';
  import LineRowHandicap from './LineRowHandicap.svelte';
  import OddsGrid from './OddsGrid.svelte';
  import TeamInputs from './TeamInputs.svelte';
  import SaveHistory from './SaveHistory.svelte';
  import BottomNav from './BottomNav.svelte';
  import MasterVerdictCard from './MasterVerdictCard.svelte';
  import CloudflareAiBanner from './CloudflareAiBanner.svelte';
  import AiPredictorButton from './AiPredictorButton.svelte';
  import {
    analyzeScope,
    scopeSignature,
    buildConfluenceLedger,
    sortCandidatesByTierAndProbability,
    clearScopes,
    clearScopeState,
    lineOptionsFor,
    loadScopes,
    saveScopes,
    saveScopesDebounced,
    flushSaveScopes,
    mergeScopeOnto,
    autoFillLinePairs,
    autoFillHandicapPairs,
    type Analysis,
    type ScopeState,
    type SportId
  } from '../engine';
  import type { SavedScreenerDoc, ConvexSportId } from '../convexClient';
  import { pushDraft, pullDraft, flushPendingDrafts, subscribeDraft } from '../draftSync';
  import { authState, setSubscribedStatus } from '$lib/authStore.svelte';
  import { notify } from '$lib/notificationStore';
  import { getConvexClient, api } from '$lib/convexClient';

  let {
    sportId,
    sportShort,
    sportTitle,
    accent,
    factory
  }: {
    sportId: SportId;
    sportShort: string;
    sportTitle: string;
    accent: string;
    factory: () => ScopeState[];
  } = $props();

  // Derive the SportId union for SVG icon
  type SportIconId = 'football' | 'basketball' | 'tennis' | 'rally' | 'hockey' | 'instant-football' | 'instant-basketball' | 'vfootball' | 'baseball' | 'americanfootball' | 'rugby' | 'cricket' | 'mma' | 'volleyball' | 'predictor';
  const iconId = $derived(sportId as SportIconId);

  let scopes: ScopeState[] = $state([]);
  let selectedScopeIndex: number = $state(0);
  let refreshTick: number = $state(0);
  let mounted: boolean = $state(false);
  let loadBanner: string | null = $state(null);
  let restoredAiResult: any = $state(null);
  let aiResult: any = $state(null);
  let draftPushTimer: ReturnType<typeof setTimeout> | null = null;
  let draftUnsub: (() => void) | null = null;

  let scope: ScopeState | null = $derived(scopes[selectedScopeIndex] ?? null);

  // Debounced analysis: inputs mutate `scopes` instantly (fast typing); the full
  // engine only recomputes ~40ms after the last change so panels never block input.
  let analysis: Analysis | null = $state(null);
  let analysisTimer: ReturnType<typeof setTimeout> | null = null;
  let analysisCache: { sig: string; value: Analysis } | null = null;

  function allScopesSignature(): string {
    let parts: string[] = [];
    for (const s of scopes) parts.push(scopeSignature(s));
    return String(selectedScopeIndex) + '|' + parts.join('~');
  }

  function runAnalysis(sid: SportId, s: ScopeState, _t: number): Analysis {
    const sig = allScopesSignature();
    if (analysisCache && analysisCache.sig === sig) return analysisCache.value;
    const res = analyzeScope(sid, s);
    const masterLedger = buildConfluenceLedger(sid, s, scopes, res);
    const masterRankings = sortCandidatesByTierAndProbability(res.picks, masterLedger);
    const value: Analysis = { ...res, masterLedger, masterRankings };
    analysisCache = { sig, value };
    return value;
  }

  // Push the live draft to Convex (debounced) so work syncs across devices.
  function scheduleDraftPush() {
    if (draftPushTimer) clearTimeout(draftPushTimer);
    draftPushTimer = setTimeout(() => {
      draftPushTimer = null;
      void pushDraft(sportId, scopes, authState.user?.id);
    }, 1500);
  }

  function scopesHaveData(list: ScopeState[]): boolean {
    return list.some((s) => {
      if (s.teamA || s.teamB || s.leaguePreset) return true;
      return Object.values(s.markets || {}).some((m: any) =>
        m.odds && typeof m.odds === 'object'
          ? Object.values(m.odds).some((o: any) => Number(o) > 0)
          : false
      );
    });
  }

  $effect(() => {
    const s = scope;
    const t = refreshTick;
    if (!mounted || !s) return;

    // Nothing relevant changed (e.g. lock toggles, tab switches) — keep current result.
    const sig = allScopesSignature();
    if (analysis && analysisCache && analysisCache.sig === sig) return;

    const run = () => { analysis = runAnalysis(sportId, s, t); };
    if (!analysis) { run(); return; }
    if (analysisTimer) clearTimeout(analysisTimer);
    analysisTimer = setTimeout(run, 40);
    return () => { if (analysisTimer) { clearTimeout(analysisTimer); analysisTimer = null; } };
  });

  function refresh() {
    refreshTick += 1;
    if (mounted) {
      saveScopesDebounced(sportId, scopes);
      scheduleDraftPush();
    }
  }

  function clearCurrent() {
    if (!scope) return;
    clearScopeState(scope);
    saveScopes(sportId, scopes);
    void pushDraft(sportId, scopes, authState.user?.id);
    loadBanner = null;
    restoredAiResult = null;
    aiResult = null;
    refresh();
  }

  function clearAll() {
    scopes.forEach(clearScopeState);
    clearScopes(sportId);
    void pushDraft(sportId, scopes, authState.user?.id);
    loadBanner = null;
    restoredAiResult = null;
    aiResult = null;
    refresh();
  }

  function backHome() {
    void goto('/');
  }

  function onChangeAny() {
    refresh();
  }

  function onLoadFromHistory(e: { detail: { scopes: any[]; doc: SavedScreenerDoc } }) {
    const { scopes: loadedScopes, doc } = e.detail;
    if (!Array.isArray(loadedScopes) || !loadedScopes.length) return;
    const freshScopes = factory();
    for (let i = 0; i < freshScopes.length; i += 1) {
      const dst = freshScopes[i];
      const src = loadedScopes[i] ?? loadedScopes.find((s: any) => s?.id === dst.id);
      if (src) mergeScopeOnto(dst, src);
    }
    scopes = freshScopes;
    saveScopes(sportId, scopes);
    loadBanner = `Loaded from history: ${doc.title}`;
    if ((doc as any).verdict?.aiInsights) {
      restoredAiResult = {
        success: true,
        isOffline: false,
        model: 'Saved Analysis',
        insights: (doc as any).verdict.aiInsights
      };
    } else {
      restoredAiResult = null;
    }
    refresh();
  }

  onMount(async () => {
    // Flush any pending debounced save when the page is closed or hidden.
    if (typeof window !== 'undefined') {
      window.addEventListener('beforeunload', flushSaveScopes);
      window.addEventListener('pagehide', flushSaveScopes);
    }

    // ── Access Control & Subscription Guard ──
    if (!authState.isAuthenticated) {
      notify(
        'Subscription required. Please sign up and complete your ₦5,000 monthly donation to unlock all sports screeners.',
        'warning',
        'Access Restricted'
      );
      void goto('/auth?mode=signup&redirect=checkout');
      return;
    }

    if (!authState.user?.isSubscribed) {
      if (authState.user?.isTester) {
        notify(
          'Your 1-month free trial for tester@gmail.com has expired. Please sign up with your own account and subscribe to continue using PulseOdds screeners.',
          'warning',
          'Free Trial Expired'
        );
        void goto('/auth?mode=signup&redirect=checkout');
        return;
      }

      // Re-verify against Convex DB in case user paid via webhook
      if (authState.user?.email) {
        try {
          const client = await getConvexClient();
          const sub = await client.query(api.users.checkSubscription, { email: authState.user.email });
          if (sub?.isSubscribed) {
            setSubscribedStatus(true, sub.txRef);
          }
        } catch (_) { /* fallback */ }
      }

      if (!authState.user?.isSubscribed) {
        notify(
          'Monthly subscription pass required. Please complete your ₦5,000 donation payment to unlock sports screeners.',
          'warning',
          'Subscription Required'
        );
        void goto('/checkout');
        return;
      }
    }

    scopes = loadScopes(sportId, factory());
    if (!scopes.length) scopes = factory();
    mounted = true;
    analysis = runAnalysis(sportId, scope, refreshTick);

    // ── Convex draft sync (non-blocking, best-effort) ─────────────────────
    // If the server holds a draft and this device has no local data, restore
    // it (new device / cleared storage). Otherwise push local state up so it
    // is available on the user's other devices. Offline => localStorage only.
    (async () => {
      try {
        const remote = await pullDraft(sportId, authState.user?.id);
        if (remote?.scopes && Array.isArray(remote.scopes) && !scopesHaveData(scopes)) {
          const fresh = factory();
          for (let i = 0; i < fresh.length; i += 1) {
            const dst = fresh[i];
            const src = remote.scopes[i] ?? remote.scopes.find((s: any) => s?.id === dst.id);
            if (src) mergeScopeOnto(dst, src);
          }
          scopes = fresh;
          saveScopes(sportId, scopes);
          loadBanner = 'Restored your draft from the cloud';
        } else {
          void pushDraft(sportId, scopes, authState.user?.id);
        }
        await flushPendingDrafts(authState.user?.id);

        // Live draft subscription: push updates from other devices. Only applied
        // when this device has no local data, so we never clobber active edits.
        draftUnsub = await subscribeDraft(sportId, authState.user?.id, (draft) => {
          if (!draft?.scopes || !Array.isArray(draft.scopes)) return;
          if (scopesHaveData(scopes)) return;
          const fresh = factory();
          for (let i = 0; i < fresh.length; i += 1) {
            const dst = fresh[i];
            const src = draft.scopes[i] ?? draft.scopes.find((s: any) => s?.id === dst.id);
            if (src) mergeScopeOnto(dst, src);
          }
          scopes = fresh;
          saveScopes(sportId, scopes);
          loadBanner = 'Live draft update applied';
          refreshTick += 1;
        });
      } catch (_) { /* offline — skip Convex draft sync */ }
    })();
  });

  onDestroy(() => {
    if (analysisTimer) { clearTimeout(analysisTimer); analysisTimer = null; }
    if (draftPushTimer) { clearTimeout(draftPushTimer); draftPushTimer = null; }
    if (draftUnsub) { draftUnsub(); draftUnsub = null; }
    if (typeof window !== 'undefined') {
      window.removeEventListener('beforeunload', flushSaveScopes);
      window.removeEventListener('pagehide', flushSaveScopes);
    }
  });

  const threewayLabels: Record<string, Record<string, string>> = {
    result: { home: 'Home Win', draw: 'Draw', away: 'Away Win' },
    doubleChance: { hd: 'Home / Draw', ha: 'Home / Away', da: 'Draw / Away' }
  };
  const yesNoLabels: Record<string, Record<string, string>> = {
    btts: { yes: 'BTTS Yes (GG)', no: 'BTTS No (NG)' },
    tiebreak: { yes: 'Tiebreak Yes', no: 'Tiebreak No' },
    oddEven: { yes: 'Odd', no: 'Even' },
    noneOdds: { none: 'None (No Goal)', goal: 'Goal in Half' }
  };
  const winnerLabels: Record<string, Record<string, string>> = {
    winner: { a: 'Side A', b: 'Side B' },
    matchWinner: { a: 'Player A Wins', b: 'Player B Wins' },
    setWinner: { a: 'Player A (Set)', b: 'Player B (Set)' }
  };
  const handicapLabels: Record<string, [string, string]> = {
    football: ['Home', 'Away'],
    basketball: ['Team 1', 'Team 2'],
    tennis: ['Player 1', 'Player 2'],
    rally: ['Player A', 'Player B'],
    hockey: ['Team 1', 'Team 2'],
    baseball: ['Home', 'Away'],
    americanfootball: ['Home', 'Away'],
    rugby: ['Home', 'Away'],
    cricket: ['Team 1', 'Team 2'],
    mma: ['Fighter A', 'Fighter B'],
    volleyball: ['Team 1', 'Team 2']
  };
</script>

{#if scope && analysis}
  <div class="page-root" style={`--accent:${accent}`}>
    <div class="page-inner">
      <Header
        title={sportTitle}
        short={sportShort}
        {accent}
        sportId={iconId}
        onBack={backHome}
        onClear={clearAll}
      />

      <div class="scope-toolbar">
        <button
          class="clear-scope-btn"
          type="button"
          onclick={clearCurrent}
        >
          <svg width="13" height="13" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path d="M12 4L4 12M4 4l8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
          </svg>
          Clear {scope.title}
        </button>
        <AiPredictorButton sportId={sportId} {accent} />
      </div>

      {#if loadBanner}
        <div class="load-banner" role="status">
          <span class="tick" aria-hidden="true">
            <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
              <path d="M3 8l4 4 6-7" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </span>
          {loadBanner}
          <button type="button" class="dismiss" onclick={() => { loadBanner = null; }} aria-label="Dismiss">&times;</button>
        </div>
      {/if}

      <ScopeTabs
        tabs={scopes.map((s) => ({ id: s.id, title: s.title }))}
        selectedIndex={selectedScopeIndex}
        onSelect={(i) => { selectedScopeIndex = i; }}
      />

      <VerdictHero headline={analysis.headline} chips={analysis.chips} />

      {#if analysis.masterLedger}
        <div class="spacer"></div>
        <MasterVerdictCard ledger={analysis.masterLedger} />
      {/if}

      <CloudflareAiBanner
        {sportId}
        {sportTitle}
        scopeTitle={scope.title}
        ledger={analysis.masterLedger ?? null}
        profiles={analysis.profiles}
        picks={analysis.masterRankings ?? analysis.picks}
        metrics={analysis.metrics}
        initialResult={restoredAiResult}
        onResultChange={(r) => { aiResult = r; }}
        {accent}
      />

      <div class="spacer"></div>

      <MetricStrip metrics={analysis.metrics} />

      <div class="spacer"></div>

      <section class="profiles-grid" aria-label="Screening profiles">
        {#each analysis.profiles as profile}
          <ProfileCard profile={profile} {accent} />
        {/each}
      </section>

      <div class="spacer"></div>

      <RankingPanel picks={analysis.masterRankings ?? analysis.picks} limit={12} {accent} />

      <div class="spacer"></div>

      <TeamInputs scope={scope} sportId={sportId} onChange={onChangeAny} />

      <div class="spacer"></div>

      <section class="markets" aria-label="Market inputs">
        {#each Object.values(scope.markets) as m (m.id)}
          {#if !(sportId === 'basketball' && (m.id === 'correctScore' || m.id === 'tiebreak'))}
              <MarketAccordion title={m.title} primary={!!m.primary} open={false} {accent}>
                {#if m.kind === 'ou' && m.pairs}
                  <div class="line-list">
                    {#each m.pairs as pair, index (index)}
                      <LineRowOu
                        pair={pair}
                        lineOptions={lineOptionsFor(sportId, scope.id, m.id)}
                        index={index}
                        onChange={onChangeAny}
                        onAutoFillLine={(i, v) => {
                          if (m.pairs) autoFillLinePairs(
                            m.pairs, i, v,
                            (sportId === 'basketball' || sportId === 'instant-basketball' || sportId === 'tennis') ? 1 : undefined
                          );
                          refresh();
                        }}
                      />
                    {/each}
                  </div>
                {:else if m.kind === 'handicap' && m.handicapPairs}
                  <div class="line-list">
                    {#each m.handicapPairs as pair, index (index)}
                      <LineRowHandicap
                        pair={pair}
                        lineOptions={lineOptionsFor(sportId, scope.id, m.id)}
                        sideALabel={handicapLabels[sportId]?.[0] ?? 'A'}
                        sideBLabel={handicapLabels[sportId]?.[1] ?? 'B'}
                        index={index}
                        onChange={onChangeAny}
                        onAutoFillLine={(i, v) => {
                          if (m.handicapPairs) autoFillHandicapPairs(
                            m.handicapPairs, i, v,
                            (sportId === 'basketball' || sportId === 'instant-basketball' || sportId === 'tennis') ? 1 : undefined
                          );
                          refresh();
                        }}
                      />
                    {/each}
                  </div>
                {:else if m.odds && Object.keys(m.odds).length}
                  {#if m.kind === 'threeway'}
                    <OddsGrid
                      odds={m.odds}
                      labels={threewayLabels[m.id] ?? {}}
                      columns={3}
                      onChange={onChangeAny}
                    />
                  {:else if m.kind === 'yesno'}
                    <OddsGrid
                      odds={m.odds}
                      labels={yesNoLabels[m.id] ?? { yes: 'Yes', no: 'No' }}
                      columns={2}
                      onChange={onChangeAny}
                    />
                  {:else if m.kind === 'winner'}
                    <OddsGrid
                      odds={m.odds}
                      labels={winnerLabels[m.id] ?? { a: 'Side A', b: 'Side B' }}
                      columns={2}
                      onChange={onChangeAny}
                    />
                  {:else if m.kind === 'correctScore'}
                    <OddsGrid
                      odds={m.odds}
                      labels={Object.fromEntries(Object.keys(m.odds).map((k) => [k, k]))}
                      columns="auto"
                      onChange={onChangeAny}
                    />
                  {/if}
                {/if}
              </MarketAccordion>
          {/if}
        {/each}
      </section>

      <div class="spacer"></div>

      <SaveHistory
        sportId={sportId as ConvexSportId}
        sportTitle={sportTitle}
        scopes={scopes}
        analysis={analysis}
        aiResult={aiResult}
        {accent}
        on:load={onLoadFromHistory}
      />

      <footer class="foot" aria-label="App info">
        <div class="foot-brand">
          <span aria-hidden="true">⚡</span>
          <strong>PulseOdds</strong>
          <span class="foot-sep">·</span>
          <span>{sportShort} Screener</span>
        </div>
        <button type="button" class="reset-link" onclick={clearAll}>Reset all</button>
      </footer>
    </div>
  </div>
  <BottomNav />
{/if}

<style>
  .page-root {
    width: 100%;
    min-height: 100dvh;
  }
  .page-inner {
    width: min(100%, 960px);
    margin: 0 auto;
    padding:
      max(14px, env(safe-area-inset-top))
      max(14px, env(safe-area-inset-right))
      max(100px, calc(env(safe-area-inset-bottom) + 88px))
      max(14px, env(safe-area-inset-left));
    min-height: 100dvh;
    min-width: 320px;
  }
  .spacer { height: 14px; }

  /* Scope toolbar */
  .scope-toolbar {
    display: flex;
    justify-content: flex-end;
    gap: 8px;
    flex-wrap: wrap;
    margin: 8px 0 2px;
  }

  .clear-scope-btn {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    border: 1px solid var(--c-border-md);
    background: var(--c-glass-sm);
    backdrop-filter: blur(8px);
    color: var(--c-muted);
    padding: 7px 14px;
    border-radius: 999px;
    font-size: 12px;
    font-weight: 700;
    font-family: var(--font-brand, 'Outfit', system-ui);
    cursor: pointer;
    transition:
      border-color var(--t-base, 180ms ease),
      color var(--t-base, 180ms ease),
      background var(--t-base, 180ms ease),
      box-shadow var(--t-base, 180ms ease);
    touch-action: manipulation;
  }
  .clear-scope-btn:hover {
    border-color: color-mix(in srgb, var(--accent) 40%, var(--c-border-md));
    color: var(--accent);
    background: color-mix(in srgb, var(--accent) 8%, var(--c-glass-sm));
    box-shadow: 0 0 10px color-mix(in srgb, var(--accent) 12%, transparent);
  }
  .clear-scope-btn:active { transform: scale(0.96); }

  /* Load banner */
  .load-banner {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 11px 14px;
    border-radius: 12px;
    background: color-mix(in srgb, var(--accent) 12%, var(--c-glass-sm));
    border: 1px solid color-mix(in srgb, var(--accent) 40%, transparent);
    color: var(--c-text);
    font-size: 13px;
    font-weight: 600;
    margin: 4px 0 10px;
    backdrop-filter: blur(10px);
    box-shadow: 0 0 16px color-mix(in srgb, var(--accent) 10%, transparent);
    animation: slide-up 0.3s ease both;
  }
  .load-banner .tick {
    font-weight: 900;
    color: var(--accent);
    width: 20px; height: 20px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    background: color-mix(in srgb, var(--accent) 15%, var(--c-glass-sm));
    border-radius: 50%;
    flex-shrink: 0;
  }
  .load-banner .dismiss {
    margin-left: auto;
    background: transparent;
    border: 0;
    color: var(--c-muted);
    cursor: pointer;
    font-size: 20px;
    line-height: 1;
    width: 26px; height: 26px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 6px;
    transition: color var(--t-fast), background var(--t-fast);
  }
  .load-banner .dismiss:hover {
    color: var(--c-red);
    background: color-mix(in srgb, var(--c-red) 12%, transparent);
  }

  /* Profiles */
  .profiles-grid {
    display: grid;
    gap: 12px;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  }

  /* Markets */
  .markets { display: grid; gap: 10px; }
  .line-list { display: grid; gap: 10px; padding-top: 10px; }

  /* Skip rendering for content below the fold — large speedup on long pages */
  .profiles-grid,
  .markets {
    content-visibility: auto;
    contain-intrinsic-size: auto 600px;
  }

  /* Footer */
  .foot {
    margin-top: 36px;
    padding: 18px 0 4px;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
    gap: 10px;
    color: var(--c-faint);
    font-size: 12.5px;
    border-top: 1px solid var(--c-border-sm);
  }
  .foot-brand {
    display: flex;
    align-items: center;
    gap: 6px;
    font-weight: 600;
    color: var(--c-muted);
  }
  .foot-brand strong { color: var(--c-text); font-weight: 800; }
  .foot-sep { color: var(--c-faint); }
  .reset-link {
    background: transparent;
    border: 0;
    padding: 0;
    color: var(--c-orange);
    text-decoration: underline;
    cursor: pointer;
    font: inherit;
    font-size: 12px;
    transition: color var(--t-fast);
  }
  .reset-link:hover { color: var(--c-orange-deep); }

  @media (max-width: 380px) {
    .page-inner { padding-left: 10px; padding-right: 10px; }
  }
  @media (min-width: 768px) {
    .page-inner { padding-bottom: max(40px, env(safe-area-inset-bottom)); }
  }
  @media (min-width: 1400px) {
    .page-inner { width: min(100%, 1100px); }
  }
  @media (min-width: 2000px) {
    .page-inner { width: min(100%, 1280px); }
  }
</style>
